default:
  image: cirrusci/flutter:2.2.1
  before_script:
    - export PUB_CACHE=$PWD/.pub_cache/
    - flutter pub version
    - flutter pub get
    - flutter pub upgrade
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pub_cache/

stages:
  - verify
  - deploy

test:
  stage: verify
  script:
    - flutter test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lint:
  stage: verify
  script:
    - dart analyze
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  image: node:latest
  stage: deploy
  before_script: []
  script:
    - cd website
    - yarn install --frozen-lockfile
    - yarn build
    - cd $CI_PROJECT_DIR
    - ci/pages-preparation.sh
  cache:
    key: website-${CI_COMMIT_REF_SLUG}
    paths:
      - website/node_modules/
      - website/.next/cache/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - website/**/*

create release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: deploy
  before_script: []
  cache: {}
  script:
    - echo "Creating a new release for tag $CI_COMMIT_TAG..."
  release:
    name: Version $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    ref: $CI_DEFAULT_BRANCH
    description: "./store_listing/whats-new.md"
    assets:
      links:
        - name: "Google Play"
          url: "https://play.google.com/store/apps/details?id=io.nathanfriend.inspiral"
        - name: "App Store"
          url: "https://apps.apple.com/us/app/inspiral-gear-art/id1558340425"
        - name: "Website"
          url: "https://inspiral.nathanfriend.io/"
  rules:
    - if: $CI_COMMIT_TAG
