default:
  image: cirrusci/flutter:2.1.0-12.1.pre
  before_script:
    - export PUB_CACHE=$PWD/.pub_cache/
    - flutter pub version
    - flutter pub get
    - flutter pub upgrade
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pub_cache/

stages:
  - verify
  - deploy

test:
  stage: verify
  script:
    - flutter test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lint:
  stage: verify
  script:
    - dart analyze
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  image: node:latest
  stage: deploy
  before_script: []
  script:
    - cd website
    - yarn install --frozen-lockfile
    - yarn build
    - cd $CI_PROJECT_DIR
    - ci/pages-preparation.sh
  cache:
    key: website-${CI_COMMIT_REF_SLUG}
    paths:
      - website/node_modules/
      - website/.next/cache/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - website/**/*
