image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cd landing-page
    - yarn install --frozen-lockfile
    - yarn build
    - cd $CI_PROJECT_DIR
    - ci/pages-preparation.sh
  cache:
    key: landing-page-${CI_COMMIT_REF_SLUG}
    paths:
      - landing-page/node_modules/
      - landing-page/.next/cache/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - landing-page/*
