// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/gear_hole.dart';

final circle63 = GearDefinition(
    image: 'images/circle_63.png',
    size: Size(552, 552),
    toothCount: 63,
    points: [
      ContactPoint(position: Offset(264, 0), direction: 0),
      ContactPoint(
          position: Offset(262.7073841920196, -26.279072352182286),
          direction: 0.09876952738560352),
      ContactPoint(
          position: Offset(258.8151420586967, -52.31194853815376),
          direction: 0.19851329353110891),
      ContactPoint(
          position: Offset(252.3361067452491, -77.83194995263152),
          direction: 0.298879646828758),
      ContactPoint(
          position: Offset(243.3289360206859, -102.57377267087965),
          direction: 0.39930944188852724),
      ContactPoint(
          position: Offset(231.8899126555978, -126.28585860091573),
          direction: 0.4994631648801864),
      ContactPoint(
          position: Offset(218.14420807834108, -148.7340038562292),
          direction: 0.5992102635663032),
      ContactPoint(
          position: Offset(202.23832998797005, -169.7017465676038),
          direction: 0.6985997508984756),
      ContactPoint(
          position: Offset(184.334772117778, -188.98859679309103),
          direction: 0.7977975704764377),
      ContactPoint(
          position: Offset(164.60966421299747, -206.40861100138446),
          direction: 0.8970177590252169),
      ContactPoint(
          position: Offset(143.25257043241123, -221.78919651611508),
          direction: 0.9964820054378629),
      ContactPoint(
          position: Offset(120.46748563360862, -234.97123529224137),
          direction: 1.09633738449845),
      ContactPoint(
          position: Offset(96.47524199619372, -245.81296104571953),
          direction: 1.1965764653300752),
      ContactPoint(
          position: Offset(71.5146991777274, -254.19598244321713),
          direction: 1.2970299579095812),
      ContactPoint(
          position: Offset(45.841157722700785, -260.0321051472192),
          direction: 1.3973070597886137),
      ContactPoint(
          position: Offset(19.72226932993976, -263.27361801767614),
          direction: 1.4967966152296404),
      ContactPoint(
          position: Offset(-6.579049598630755, -263.91929757843025),
          direction: 1.595432346540572),
      ContactPoint(
          position: Offset(-32.82051455606293, -261.97851543770906),
          direction: 1.6944021596461933),
      ContactPoint(
          position: Offset(-58.75062539848915, -257.4363415463902),
          direction: 1.7943721085939321),
      ContactPoint(
          position: Offset(-84.1003794573785, -250.31809896205877),
          direction: 1.8947912421553523),
      ContactPoint(
          position: Offset(-108.60779562749022, -240.69290680748068),
          direction: 1.9951742490191586),
      ContactPoint(
          position: Offset(-132.02521016344187, -228.66446250271403),
          direction: 2.0952346810710356),
      ContactPoint(
          position: Offset(-154.12296743651623, -214.36429754562258),
          direction: 2.1948873203830317),
      ContactPoint(
          position: Offset(-174.68850484823398, -197.94297017402258),
          direction: 2.2942123048815626),
      ContactPoint(
          position: Offset(-193.52548678673097, -179.56700054145733),
          direction: 2.393384769287218),
      ContactPoint(
          position: Offset(-210.45137871759067, -159.4158068610888),
          direction: 2.4926450566655918),
      ContactPoint(
          position: Offset(-225.29678365544862, -137.68190014176383),
          direction: 2.5922010174184016),
      ContactPoint(
          position: Offset(-237.9062995907948, -114.57356486321758),
          direction: 2.6921640264729514),
      ContactPoint(
          position: Offset(-248.14324920769695, -90.31606648064849),
          direction: 2.792480595334121),
      ContactPoint(
          position: Offset(-255.89637437285754, -65.15287839470372),
          direction: 2.892930186438611),
      ContactPoint(
          position: Offset(-261.0866958588193, -39.34257122350716),
          direction: 2.993076772524504),
      ContactPoint(
          position: Offset(-263.6774090044221, -13.154184743358002),
          direction: 3.092297418476547),
      ContactPoint(
          position: Offset(-263.67739547992954, 13.154483604666648),
          direction: 3.1908886349692955),
      ContactPoint(
          position: Offset(-261.0866769773947, 39.342732088815296),
          direction: 3.2901092321177385),
      ContactPoint(
          position: Offset(-255.89634930129185, 65.15300718586745),
          direction: 3.3902556985850105),
      ContactPoint(
          position: Offset(-248.14319203847117, 90.31625468501575),
          direction: 3.49070516403098),
      ContactPoint(
          position: Offset(-237.90625543520622, 114.57367622312896),
          direction: 3.591021701528515),
      ContactPoint(
          position: Offset(-225.296743227268, 137.6820044486838),
          direction: 3.690984045030212),
      ContactPoint(
          position: Offset(-210.45135166492707, 159.4159115333031),
          direction: 3.790540824752205),
      ContactPoint(
          position: Offset(-193.52539471217796, 179.5671237635923),
          direction: 3.889801536335767),
      ContactPoint(
          position: Offset(-174.688453824186, 197.943023507805),
          direction: 3.9889744339443465),
      ContactPoint(
          position: Offset(-154.12282043468232, 214.36437149628432),
          direction: 4.088298196629286),
      ContactPoint(
          position: Offset(-132.0251004540415, 228.66454368901026),
          direction: 4.187950170597036),
      ContactPoint(
          position: Offset(-108.60782738914938, 240.69290169569777),
          direction: 4.288012339734376),
      ContactPoint(
          position: Offset(-84.10036658107211, 250.31806669069942),
          direction: 4.388393855587244),
      ContactPoint(
          position: Offset(-58.75066903048385, 257.43634333283694),
          direction: 4.488812077822652),
      ContactPoint(
          position: Offset(-32.82048254675132, 261.9785453061539),
          direction: 4.588783272800237),
      ContactPoint(
          position: Offset(-6.57901182553781, 263.9193022533552),
          direction: 4.687754837400467),
      ContactPoint(
          position: Offset(19.72238907979505, 263.2735559028494),
          direction: 4.786388498047856),
      ContactPoint(
          position: Offset(45.84127530821863, 260.0321118936479),
          direction: 4.885877867962282),
      ContactPoint(
          position: Offset(71.51467441670842, 254.19596461421116),
          direction: 4.986155847539115),
      ContactPoint(
          position: Offset(96.47533058561537, 245.81295076539675),
          direction: 5.086608576545957),
      ContactPoint(
          position: Offset(120.4674644983505, 234.97122856623918),
          direction: 5.186848801629967),
      ContactPoint(
          position: Offset(143.2526634788575, 221.7891345144191),
          direction: 5.286703450004215),
      ContactPoint(
          position: Offset(164.60966108681023, 206.40858297982504),
          direction: 5.386167214788161),
      ContactPoint(
          position: Offset(184.33482781964273, 188.98858673694423),
          direction: 5.485387115819567),
      ContactPoint(
          position: Offset(202.23842890673916, 169.70166150349127),
          direction: 5.584586510709025),
      ContactPoint(
          position: Offset(218.14424075055965, 148.7339472956939),
          direction: 5.683975361975757),
      ContactPoint(
          position: Offset(231.88994191779878, 126.28584564301349),
          direction: 5.7837219238762),
      ContactPoint(
          position: Offset(243.32896860047944, 102.57373726629422),
          direction: 5.883876307315858),
      ContactPoint(
          position: Offset(252.33610753326357, 77.8319473950481),
          direction: 5.984305883369881),
      ContactPoint(
          position: Offset(258.81514234248476, 52.31197764499284),
          direction: 6.084672133565123),
      ContactPoint(
          position: Offset(262.70738426296873, 26.279041118611595),
          direction: 6.184415839752251),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(
          name: '8', angle: 1.5957296018233869, distance: 7.999999999999999),
      GearHole(name: '9', angle: 2.3935944027350806, distance: 9),
      GearHole(
          name: '10', angle: 3.091726103532812, distance: 9.999999999999998),
      GearHole(name: '11', angle: -2.39359440273508, distance: 11),
      GearHole(
          name: '12', angle: -1.5957296018233873, distance: 12.000000000000007),
      GearHole(name: '13', angle: -0.7978648009116931, distance: 13),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7978648009116941, distance: 14.999999999999996),
      GearHole(
          name: '16', angle: 1.5957296018233873, distance: 15.999999999999998),
      GearHole(
          name: '17', angle: 2.3935944027350806, distance: 17.000000000000004),
      GearHole(name: '18', angle: 3.0917261035328125, distance: 18),
      GearHole(name: '19', angle: -2.3935944027350806, distance: 19),
      GearHole(
          name: '20', angle: -1.5957296018233875, distance: 19.999999999999993),
      GearHole(
          name: '21', angle: -0.7978648009116932, distance: 21.000000000000004),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(
          name: '23', angle: 0.7978648009116937, distance: 22.999999999999996),
      GearHole(name: '24', angle: 1.595729601823387, distance: 24),
      GearHole(name: '25', angle: 2.3935944027350806, distance: 25),
      GearHole(
          name: '26', angle: 3.0917261035328125, distance: 25.999999999999996),
      GearHole(
          name: '27', angle: -2.39359440273508, distance: 27.000000000000004),
      GearHole(
          name: '28', angle: -1.5957296018233875, distance: 28.000000000000007),
      GearHole(
          name: '29', angle: -0.7978648009116937, distance: 28.999999999999996),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
      GearHole(
          name: '31', angle: 0.7978648009116937, distance: 30.999999999999996),
      GearHole(
          name: '32', angle: 1.5957296018233873, distance: 31.999999999999996),
      GearHole(name: '33', angle: 2.3935944027350806, distance: 33),
      GearHole(name: '34', angle: 3.0917261035328125, distance: 34),
      GearHole(
          name: '35', angle: -2.39359440273508, distance: 34.99999999999999),
      GearHole(
          name: '36', angle: -1.5957296018233873, distance: 35.99999999999999),
      GearHole(name: '37', angle: -0.7978648009116935, distance: 37),
      GearHole(name: '38', angle: -1.8698493046318425e-16, distance: 38),
      GearHole(name: '39', angle: 0.7978648009116935, distance: 39),
      GearHole(name: '40', angle: 1.595729601823387, distance: 40),
      GearHole(name: '41', angle: 2.39359440273508, distance: 41),
      GearHole(name: '42', angle: 3.0917261035328125, distance: 42),
      GearHole(
          name: '43', angle: -2.3935944027350806, distance: 42.99999999999999),
      GearHole(
          name: '44', angle: -1.5957296018233873, distance: 44.00000000000001),
      GearHole(
          name: '45', angle: -0.7978648009116933, distance: 44.99999999999999),
      GearHole(name: '46', angle: -3.089316242435218e-16, distance: 46),
      GearHole(
          name: '47', angle: 0.7978648009116938, distance: 46.99999999999999),
      GearHole(name: '48', angle: 1.5957296018233873, distance: 48),
      GearHole(name: '49', angle: 2.3935944027350806, distance: 49),
      GearHole(
          name: '50', angle: 3.0917261035328125, distance: 49.99999999999999),
      GearHole(name: '51', angle: -2.39359440273508, distance: 51),
      GearHole(
          name: '52', angle: -1.5957296018233875, distance: 51.99999999999999),
      GearHole(
          name: '53', angle: -0.7978648009116933, distance: 52.99999999999999),
      GearHole(name: '54', angle: -2.631639762074445e-16, distance: 54),
      GearHole(
          name: '55', angle: 0.7978648009116938, distance: 54.99999999999999),
    ]);
