// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle52Noholes = GearDefinition(
    id: 'circle52Noholes',
    image: 'images/gears/circle_52_noholes.png',
    thumbnailImage: 'images/gears/circle_52_noholes_thumb.png',
    size: Size(464, 464),
    center: Offset(232, 232),
    toothCount: 52,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(position: Offset(220, -1.449290039090556e-7), direction: 0),
      ContactPoint(
          position: Offset(218.41754196496763, -26.5117445448749),
          direction: 0.11987726461895143),
      ContactPoint(
          position: Offset(213.65574138803453, -52.654608369997256),
          direction: 0.24096419447809936),
      ContactPoint(
          position: Offset(205.75590064802844, -78.0331000506194),
          direction: 0.3626133201011541),
      ContactPoint(
          position: Offset(194.83523298659978, -102.2628614861132),
          direction: 0.48404687325715745),
      ContactPoint(
          position: Offset(181.06892471067113, -124.9891794543098),
          direction: 0.6049260395648872),
      ContactPoint(
          position: Offset(164.6726012086567, -145.8900233480202),
          direction: 0.7253034979469515),
      ContactPoint(
          position: Offset(145.8901226265582, -164.6726151816016),
          direction: 0.8454902530532582),
      ContactPoint(
          position: Offset(124.9892551141875, -181.0689204847988),
          direction: 0.9658718826781865),
      ContactPoint(
          position: Offset(102.26294712140134, -194.83516520146446),
          direction: 1.0867485604115883),
      ContactPoint(
          position: Offset(78.03327526126694, -205.75589317578735),
          direction: 1.2081823374322038),
      ContactPoint(
          position: Offset(52.654707445650935, -213.65570477454037),
          direction: 1.3298327837151271),
      ContactPoint(
          position: Offset(26.51181364356512, -218.4175289617973),
          direction: 1.4509183731927244),
      ContactPoint(
          position: Offset(0.00008114281866940156, -219.99999999999903),
          direction: 1.5707959227221169),
      ContactPoint(
          position: Offset(-26.511650001407006, -218.41755055891883),
          direction: 1.6906733525492204),
      ContactPoint(
          position: Offset(-52.65451400533418, -213.65575785894112),
          direction: 1.8117589830147),
      ContactPoint(
          position: Offset(-78.03305402257314, -205.7559771274026),
          direction: 1.9334096373815104),
      ContactPoint(
          position: Offset(-102.26279847127884, -194.83523962164554),
          direction: 2.054843745613997),
      ContactPoint(
          position: Offset(-124.98910338025675, -181.0689885589297),
          direction: 2.175720857427626),
      ContactPoint(
          position: Offset(-145.8899531473665, -164.67270263495362),
          direction: 2.296100519454101),
      ContactPoint(
          position: Offset(-164.67253251050423, -145.8901474099065),
          direction: 2.416287234575009),
      ContactPoint(
          position: Offset(-181.06886790855987, -124.98928777273586),
          direction: 2.5366672343047334),
      ContactPoint(
          position: Offset(-194.83516061416998, -102.26294445849638),
          direction: 2.6575444332596208),
      ContactPoint(
          position: Offset(-205.7558938654155, -78.03325794767285),
          direction: 2.778978860287527),
      ContactPoint(
          position: Offset(-213.6557355609254, -52.65458577704994),
          direction: 2.9006290884748527),
      ContactPoint(
          position: Offset(-218.41753452866735, -26.511776428388693),
          direction: 3.021715274320057),
      ContactPoint(
          position: Offset(-220, 0.00003091458053669652),
          direction: 3.1415926987507445),
      ContactPoint(
          position: Offset(-218.41753244768245, 26.51182038742454),
          direction: 3.2614699046499656),
      ContactPoint(
          position: Offset(-213.65575091865367, 52.65457926328217),
          direction: 3.3825556846149567),
      ContactPoint(
          position: Offset(-205.75594948986802, 78.03318054323039),
          direction: 3.504206373749194),
      ContactPoint(
          position: Offset(-194.83521375771667, 102.26285348853398),
          direction: 3.625640237774907),
      ContactPoint(
          position: Offset(-181.06897207912178, 124.98919082704782),
          direction: 3.746516782925972),
      ContactPoint(
          position: Offset(-164.67266085472264, 145.89006139945332),
          direction: 3.8668987220951374),
      ContactPoint(
          position: Offset(-145.8900515503489, 164.67256570670446),
          direction: 3.9870848744942617),
      ContactPoint(
          position: Offset(-124.98920902924854, 181.0689198423603),
          direction: 4.107462248690219),
      ContactPoint(
          position: Offset(-102.26294480736016, 194.8352025644536),
          direction: 4.228342150169194),
      ContactPoint(
          position: Offset(-78.03317229024962, 205.75587146870006),
          direction: 4.3497760087236985),
      ContactPoint(
          position: Offset(-52.65456510454665, 213.65574059046068),
          direction: 4.471424558001562),
      ContactPoint(
          position: Offset(-26.511744399945897, 218.41754182003862),
          direction: 4.592511715765738),
      ContactPoint(
          position: Offset(0.00005307818223122993, 219.99999985506878),
          direction: 4.712389588869277),
      ContactPoint(
          position: Offset(26.511843150431858, 218.41751043545443),
          direction: 4.832266849152075),
      ContactPoint(
          position: Offset(52.65466004191019, 213.65570924114624),
          direction: 4.953353693211682),
      ContactPoint(
          position: Offset(78.03320671721383, 205.7558394679432),
          direction: 5.075002300485844),
      ContactPoint(
          position: Offset(102.2628974743817, 194.8352073941325),
          direction: 5.196434945744301),
      ContactPoint(
          position: Offset(124.98920641112076, 181.06895744500582),
          direction: 5.3173146738853045),
      ContactPoint(
          position: Offset(145.89011630530723, 164.67255564567282),
          direction: 5.437694350166326),
      ContactPoint(
          position: Offset(164.6726517908652, 145.8900195906787),
          direction: 5.557880496107113),
      ContactPoint(
          position: Offset(181.06895995161688, 124.98917233277807),
          direction: 5.678259959742897),
      ContactPoint(
          position: Offset(194.83529623891303, 102.26278068530004),
          direction: 5.79913883095095),
      ContactPoint(
          position: Offset(205.75590365414433, 78.03310709597814),
          direction: 5.920572693299454),
      ContactPoint(
          position: Offset(213.65574325943004, 52.65458520595719),
          direction: 6.042221766198127),
      ContactPoint(
          position: Offset(218.4175419127502, 26.5116226182065),
          direction: 6.163308006174327),
    ],
    holes: [],
    isRing: false,
    isRound: true,
    smallestConvexDiff: 0.11987720589922102,
    biggestConvexDiff: 0.12165068913423749,
    smallestConcaveDiff: 6.283185307179586,
    biggestConcaveDiff: 0);
