// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle24 = GearDefinition(
    id: 'circle24',
    image: 'images/gears/circle_24.png',
    thumbnailImage: 'images/gears/circle_24_thumb.png',
    size: Size(240, 240),
    center: Offset(120, 120),
    toothCount: 24,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(
          position: Offset(107.99999999999943, 0.000003635399678455832),
          direction: 6.283185000203807),
      ContactPoint(
          position: Offset(104.34381338244286, -27.95549304619701),
          direction: 0.26147899743745473),
      ContactPoint(
          position: Offset(93.54275560407962, -54.01109925059309),
          direction: 0.5240641313868144),
      ContactPoint(
          position: Offset(76.36756027709944, -76.36752125748032),
          direction: 0.7853981091295879),
      ContactPoint(
          position: Offset(54.01116149612856, -93.5427009242661),
          direction: 1.0467313399217062),
      ContactPoint(
          position: Offset(27.9555862446484, -104.34379543853902),
          direction: 1.309316525066702),
      ContactPoint(
          position: Offset(0.000030198044332531628, -107.99999999999777),
          direction: 1.570795717639835),
      ContactPoint(
          position: Offset(-27.955470513474502, -104.34382810465303),
          direction: 1.8322753590638836),
      ContactPoint(
          position: Offset(-54.011084153482436, -93.54275046521425),
          direction: 2.094860845561403),
      ContactPoint(
          position: Offset(-76.36752513898811, -76.36753732210533),
          direction: 2.3561944494915292),
      ContactPoint(
          position: Offset(-93.54275166344391, -54.01108699515357),
          direction: 2.617527865959609),
      ContactPoint(
          position: Offset(-104.34381665874594, -27.955508535014822),
          direction: 2.880113636308767),
      ContactPoint(
          position: Offset(-107.99999999999991, 0.000013829087320922724),
          direction: 3.1415925384737875),
      ContactPoint(
          position: Offset(-104.34382122659734, 27.95550512203682),
          direction: 3.4030720429375263),
      ContactPoint(
          position: Offset(-93.54273526429745, 54.01111062433879),
          direction: 3.665657154673573),
      ContactPoint(
          position: Offset(-76.36754332544511, 76.3675400198616),
          direction: 3.9269902878757508),
      ContactPoint(
          position: Offset(-54.01114212996254, 93.54273973865563),
          direction: 4.188324756018603),
      ContactPoint(
          position: Offset(-27.95549436594945, 104.34381296803173),
          direction: 4.450909864930516),
      ContactPoint(
          position: Offset(-0.000007629394533454364, 107.99999995169034),
          direction: 4.71238898038469),
      ContactPoint(
          position: Offset(27.955484448378108, 104.34381358036123),
          direction: 4.973867898447886),
      ContactPoint(
          position: Offset(54.01110406993526, 93.5427571519764),
          direction: 5.236452845951263),
      ContactPoint(
          position: Offset(76.36751404025419, 76.36757502710078),
          direction: 5.497787143782138),
      ContactPoint(
          position: Offset(93.54275195038473, 54.01111310495345),
          direction: 5.759120567334307),
      ContactPoint(
          position: Offset(104.34379824676783, 27.9555535246765),
          direction: 6.021706349429267),
    ],
    holes: [
      GearHole(
          name: '0',
          angle: 1.5707963267948966,
          distance: 1.2077417288480774e-8),
      GearHole(
          name: '8', angle: 1.5707963267948966, distance: 8.000000012077418),
      GearHole(
          name: '9', angle: 2.356194489243453, distance: 9.000000008540026),
      GearHole(name: '10', angle: 3.1415926523820517, distance: 10),
      GearHole(
          name: '11', angle: -2.3561944909687114, distance: 10.999999991459978),
      GearHole(
          name: '12', angle: -1.570796326794897, distance: 11.999999987922582),
      GearHole(
          name: '13', angle: -0.7853981627405238, distance: 12.999999991459976),
      GearHole(name: '14', angle: 8.626724096976496e-10, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981639667819, distance: 15.000000008540024),
      GearHole(
          name: '16', angle: 1.5707963267948966, distance: 16.000000012077418),
    ]);
