// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle72 = GearDefinition(
    id: 'circle72',
    image: 'images/gears/circle_72.png',
    thumbnailImage: 'images/gears/circle_72_thumb.png',
    size: Size(624, 624),
    center: Offset(312, 312),
    toothCount: 72,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(
          position: Offset(299.99999996542465, -1.3154931366443634e-8),
          direction: 0),
      ContactPoint(
          position: Offset(298.87597333194014, -26.139860905355444),
          direction: 0.08632176772631084),
      ContactPoint(
          position: Offset(295.49112819926694, -52.093680596868666),
          direction: 0.17345872103431326),
      ContactPoint(
          position: Offset(289.8481432129344, -77.6591140997881),
          direction: 0.26120457248920914),
      ContactPoint(
          position: Offset(281.9814230408822, -102.63213364682386),
          direction: 0.34911716919636326),
      ContactPoint(
          position: Offset(271.95340397859104, -126.8169971863485),
          direction: 0.4369191379735833),
      ContactPoint(
          position: Offset(259.84691494764564, -150.0277559223159),
          direction: 0.52445941677402),
      ContactPoint(
          position: Offset(245.76325569410687, -172.09032965835888),
          direction: 0.6116687454546454),
      ContactPoint(
          position: Offset(229.81682602285937, -192.84240031838928),
          direction: 0.6986070297509297),
      ContactPoint(
          position: Offset(212.13197113233988, -212.13210203172062),
          direction: 0.7853991304091341),
      ContactPoint(
          position: Offset(192.84226400584063, -229.81689261984428),
          direction: 0.8721900115074774),
      ContactPoint(
          position: Offset(172.09023532464806, -245.76330497191387),
          direction: 0.9591286361376898),
      ContactPoint(
          position: Offset(150.02773154879458, -259.8468363172766),
          direction: 1.0463377829273917),
      ContactPoint(
          position: Offset(126.81700434792499, -271.9533434389525),
          direction: 1.133876525757163),
      ContactPoint(
          position: Offset(102.63210489288906, -281.9813823748997),
          direction: 1.2216789969602342),
      ContactPoint(
          position: Offset(77.65910476217448, -289.8480971065658),
          direction: 1.3095925556442713),
      ContactPoint(
          position: Offset(52.093706707134174, -295.49103240031735),
          direction: 1.3973366836559205),
      ContactPoint(
          position: Offset(26.139819910522828, -298.8759807012032),
          direction: 1.4844728788076695),
      ContactPoint(
          position: Offset(-0.0000939804873915519, -299.9999999999998),
          direction: 1.5707965262263688),
      ContactPoint(
          position: Offset(-26.140004912405317, -298.8759705294941),
          direction: 1.6571199276231567),
      ContactPoint(
          position: Offset(-52.09377243956726, -295.4910344503966),
          direction: 1.7442563614868813),
      ContactPoint(
          position: Offset(-77.6591765391332, -289.84808567057536),
          direction: 1.8320010185607192),
      ContactPoint(
          position: Offset(-102.63221526570459, -281.98132388320096),
          direction: 1.9199139663236497),
      ContactPoint(
          position: Offset(-126.81709547615729, -271.95330742987574),
          direction: 2.00771608242972),
      ContactPoint(
          position: Offset(-150.0277656781627, -259.84681519438254),
          direction: 2.0952552117224847),
      ContactPoint(
          position: Offset(-172.09034648290566, -245.7632371217444),
          direction: 2.1824644528607227),
      ContactPoint(
          position: Offset(-192.84229995953257, -229.81684233571522),
          direction: 2.2694032261545267),
      ContactPoint(
          position: Offset(-212.1320615067871, -212.13201172643164),
          direction: 2.3561942753010205),
      ContactPoint(
          position: Offset(-229.81685865769688, -192.8422986977737),
          direction: 2.4429858892128964),
      ContactPoint(
          position: Offset(-245.76327614737062, -172.09029946295175),
          direction: 2.529924651926403),
      ContactPoint(
          position: Offset(-259.8468270957319, -150.02775830919668),
          direction: 2.6171344760314943),
      ContactPoint(
          position: Offset(-271.9533416046929, -126.81698494217375),
          direction: 2.7046732383520347),
      ContactPoint(
          position: Offset(-281.98137071956984, -102.63209032095173),
          direction: 2.7924752670758313),
      ContactPoint(
          position: Offset(-289.84810052195684, -77.65907943390393),
          direction: 2.8803884389304697),
      ContactPoint(
          position: Offset(-295.4910564082078, -52.09364489439324),
          direction: 2.9681330802748738),
      ContactPoint(
          position: Offset(-298.87598760637235, -26.1397551416778),
          direction: 3.0552695218985626),
      ContactPoint(
          position: Offset(-299.99999999999915, 0.00006558043774016056),
          direction: 3.141593033459495),
      ContactPoint(
          position: Offset(-298.87596798019007, 26.140036160280022),
          direction: 3.2279163194959475),
      ContactPoint(
          position: Offset(-295.4910257344475, 52.0938037900215),
          direction: 3.3150527627836572),
      ContactPoint(
          position: Offset(-289.84808574002375, 77.65917274408409),
          direction: 3.402797022114587),
      ContactPoint(
          position: Offset(-281.981352269332, 102.63217011605593),
          direction: 3.490710352930795),
      ContactPoint(
          position: Offset(-271.9532922096401, 126.8171259093196),
          direction: 3.578512405850524),
      ContactPoint(
          position: Offset(-259.84676604285056, 150.02788697798997),
          direction: 3.6660514689356765),
      ContactPoint(
          position: Offset(-245.76324837777793, 172.09033691369203),
          direction: 3.753261363647326),
      ContactPoint(
          position: Offset(-229.8167375562573, 192.84245010580992),
          direction: 3.8401992924295163),
      ContactPoint(
          position: Offset(-212.13197268917278, 212.1321310353145),
          direction: 3.926990709541591),
      ContactPoint(
          position: Offset(-192.84217658070483, 229.81701766311505),
          direction: 4.013783053713669),
      ContactPoint(
          position: Offset(-172.09022637321016, 245.763319643588),
          direction: 4.1007206547506385),
      ContactPoint(
          position: Offset(-150.0276772787148, 259.8469773758857),
          direction: 4.1879297918810785),
      ContactPoint(
          position: Offset(-126.81686954453711, 271.95346764718386),
          direction: 4.2754703568105334),
      ContactPoint(
          position: Offset(-102.63199516689164, 281.9814845241914),
          direction: 4.363271915147228),
      ContactPoint(
          position: Offset(-77.65896681657647, 289.8482069360832),
          direction: 4.451185268377483),
      ContactPoint(
          position: Offset(-52.093593271078305, 295.49113015743063),
          direction: 4.538931194488706),
      ContactPoint(
          position: Offset(-26.139800204858666, 298.87597332625387),
          direction: 4.626067186457568),
      ContactPoint(
          position: Offset(0.00007558759517102415, 299.9999999868362),
          direction: 4.7123901959692125),
      ContactPoint(
          position: Offset(26.139904914347653, 298.87591114656215),
          direction: 4.79871188058977),
      ContactPoint(
          position: Offset(52.09377072764406, 295.4910700999496),
          direction: 4.885846294217499),
      ContactPoint(
          position: Offset(77.65919653911978, 289.848145657712),
          direction: 4.973592770875585),
      ContactPoint(
          position: Offset(102.63217699754378, 281.9814183732916),
          direction: 5.061507291897442),
      ContactPoint(
          position: Offset(126.81709008958414, 271.9533423118498),
          direction: 5.149308246958307),
      ContactPoint(
          position: Offset(150.02776889751792, 259.8469162625052),
          direction: 5.236848181906269),
      ContactPoint(
          position: Offset(172.09033835199517, 245.7632549355837),
          direction: 5.324057839025325),
      ContactPoint(
          position: Offset(192.84236075437377, 229.81685771195703),
          direction: 5.410995861116959),
      ContactPoint(
          position: Offset(212.1320440196899, 212.13203674746163),
          direction: 5.497787573564509),
      ContactPoint(
          position: Offset(229.81691872569283, 192.84226922305982),
          direction: 5.584578426447317),
      ContactPoint(
          position: Offset(245.76325491416327, 172.0903383734156),
          direction: 5.671516448538951),
      ContactPoint(
          position: Offset(259.8469782689066, 150.02767565026792),
          direction: 5.758726270856147),
      ContactPoint(
          position: Offset(271.9534063064935, 126.81696165789353),
          direction: 5.846266627653246),
      ContactPoint(
          position: Offset(281.9814230408822, 102.632133620514),
          direction: 5.934068137983223),
      ContactPoint(
          position: Offset(289.84814296971825, 77.65908446575956),
          direction: 6.021980656206553),
      ContactPoint(
          position: Offset(295.49112928558196, 52.093689629603425),
          direction: 6.10972711066166),
      ContactPoint(
          position: Offset(298.87597335904684, 26.13967746033799),
          direction: 6.196863565654069),
    ],
    holes: [
      GearHole(
          name: '0', angle: 2.7780338062838332, distance: 9.248334604016268e-9),
      GearHole(
          name: '8', angle: 1.5707963278753765, distance: 8.000000003288733),
      GearHole(
          name: '9', angle: 2.3561944906130816, distance: 9.000000008437594),
      GearHole(
          name: '10', angle: 3.1415926532609197, distance: 10.000000008643838),
      GearHole(
          name: '11', angle: -2.3561944909593997, distance: 11.00000000378664),
      GearHole(
          name: '12', angle: -1.5707963275152166, distance: 11.999999996711267),
      GearHole(
          name: '13', angle: -0.7853981636887276, distance: 12.999999991562403),
      GearHole(
          name: '14',
          angle: 2.349094888315306e-10,
          distance: 13.999999991356162),
      GearHole(
          name: '15', angle: 0.7853981639599551, distance: 14.99999999621337),
      GearHole(
          name: '16', angle: 1.5707963273351366, distance: 16.000000003288733),
      GearHole(
          name: '17', angle: 2.356194490415088, distance: 17.0000000084376),
      GearHole(
          name: '18', angle: 3.141592653407086, distance: 18.000000008643838),
      GearHole(
          name: '19', angle: -2.3561944906364296, distance: 19.000000003786628),
      GearHole(
          name: '20', angle: -1.5707963272270886, distance: 19.999999996711267),
      GearHole(
          name: '21', angle: -0.7853981635777645, distance: 20.999999991562397),
      GearHole(
          name: '22',
          angle: 1.4948785649559352e-10,
          distance: 21.999999991356162),
      GearHole(
          name: '23', angle: 0.7853981637643003, distance: 22.99999999621337),
      GearHole(
          name: '24', angle: 1.5707963271550567, distance: 24.000000003288733),
      GearHole(
          name: '25', angle: 2.3561944903438103, distance: 25.000000008437603),
      GearHole(
          name: '26', angle: 3.1415926534633036, distance: 26.000000008643838),
      GearHole(
          name: '27', angle: -2.3561944905048486, distance: 27.000000003786635),
      GearHole(
          name: '28', angle: -1.5707963271036052, distance: 27.999999996711267),
      GearHole(
          name: '29', angle: -0.785398163528022, distance: 28.9999999915624),
      GearHole(
          name: '30',
          angle: 1.0962395439012549e-10,
          distance: 29.999999991356162),
      GearHole(
          name: '31', angle: 0.7853981636696287, distance: 30.99999999621337),
      GearHole(
          name: '32', angle: 1.5707963270650167, distance: 32.00000000328873),
      GearHole(
          name: '33', angle: 2.3561944903070913, distance: 33.0000000084376),
      GearHole(
          name: '34', angle: 3.1415926534930656, distance: 34.00000000864384),
      GearHole(
          name: '35', angle: -2.356194490433419, distance: 35.00000000378663),
      GearHole(
          name: '36', angle: -1.5707963270350034, distance: 35.99999999671127),
      GearHole(
          name: '37', angle: -0.78539816349979, distance: 36.999999991562404),
      GearHole(
          name: '38',
          angle: 8.654522714484937e-11,
          distance: 37.99999999135616),
      GearHole(
          name: '39', angle: 0.7853981636137968, distance: 38.99999999621337),
      GearHole(
          name: '40', angle: 1.5707963270109926, distance: 40.00000000328873),
      GearHole(
          name: '41', angle: 2.3561944902847016, distance: 41.0000000084376),
      GearHole(
          name: '42', angle: 3.14159265351149, distance: 42.00000000864384),
      GearHole(
          name: '43', angle: -2.3561944903885683, distance: 43.00000000378663),
      GearHole(
          name: '44', angle: -1.5707963269913479, distance: 43.99999999671127),
      GearHole(
          name: '45', angle: -0.7853981634815959, distance: 44.99999999156239),
      GearHole(
          name: '46',
          angle: 7.149388329074294e-11,
          distance: 45.99999999135616),
      GearHole(
          name: '47', angle: 0.7853981635769713, distance: 46.99999999621337),
      GearHole(
          name: '48', angle: 1.5707963269749767, distance: 48.00000000328873),
      GearHole(
          name: '49', angle: 2.356194490269623, distance: 49.0000000084376),
      GearHole(
          name: '50', angle: 3.1415926535240186, distance: 50.00000000864384),
      GearHole(
          name: '51', angle: -2.356194490357788, distance: 51.00000000378664),
      GearHole(
          name: '52', angle: -1.5707963269611247, distance: 51.99999999671127),
      GearHole(
          name: '53', angle: -0.7853981634688946, distance: 52.999999991562404),
      GearHole(
          name: '54',
          angle: 6.090219687560411e-11,
          distance: 53.99999999135616),
      GearHole(
          name: '55', angle: 0.785398163550859, distance: 54.99999999621336),
      GearHole(
          name: '56', angle: 1.5707963269492509, distance: 56.00000000328873),
      GearHole(
          name: '57', angle: 2.356194490258777, distance: 57.0000000084376),
      GearHole(
          name: '58', angle: 3.141592653533091, distance: 58.00000000864384),
      GearHole(
          name: '59', angle: -2.3561944903353553, distance: 59.00000000378663),
      GearHole(
          name: '60', angle: -1.5707963269389609, distance: 59.99999999671127),
      GearHole(
          name: '61', angle: -0.7853981634595245, distance: 60.99999999156238),
      GearHole(
          name: '62',
          angle: 5.304384889055961e-11,
          distance: 61.99999999135616),
      GearHole(
          name: '63', angle: 0.7853981635313781, distance: 62.999999996213376),
      GearHole(
          name: '64', angle: 1.5707963269299567, distance: 64.00000000328873),
    ],
    isRing: false,
    isRound: true,
    smallestConvexDiff: 0.08632168462055745,
    biggestConvexDiff: 0.08791452102185726,
    smallestConcaveDiff: 6.283185307179586,
    biggestConcaveDiff: 0);
