// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle100 = GearDefinition(
    id: 'circle100',
    image: 'images/gears/circle_100.png',
    thumbnailImage: 'images/gears/circle_100_thumb.png',
    size: Size(848, 848),
    center: Offset(424, 424),
    toothCount: 100,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(
          position: Offset(411.99999942027955, -5.797160156362224e-7),
          direction: 0),
      ContactPoint(
          position: Offset(411.2003894408638, -25.863812783237087),
          direction: 0.062004133785092286),
      ContactPoint(
          position: Offset(408.7940332677862, -51.633591415833955),
          direction: 0.12449099033269118),
      ContactPoint(
          position: Offset(404.77505740261694, -77.20697282189758),
          direction: 0.18743349589787517),
      ContactPoint(
          position: Offset(399.1505325944066, -102.47889900490543),
          direction: 0.2506282747513353),
      ContactPoint(
          position: Offset(391.9387801417405, -127.34608360451698),
          direction: 0.3139507589829593),
      ContactPoint(
          position: Offset(383.1668703454566, -151.706508080004),
          direction: 0.37726020513210834),
      ContactPoint(
          position: Offset(372.87328337979716, -175.46245053131554),
          direction: 0.44044795047253427),
      ContactPoint(
          position: Offset(361.10231499562957, -198.52034218143655),
          direction: 0.5035047613406407),
      ContactPoint(
          position: Offset(347.9043134101822, -220.78980606848825),
          direction: 0.5663910767775926),
      ContactPoint(
          position: Offset(333.3362366147612, -242.1855915426372),
          direction: 0.6290995273551889),
      ContactPoint(
          position: Offset(317.4584914092891, -262.6263010070889),
          direction: 0.6916779325406281),
      ContactPoint(
          position: Offset(300.33527989351137, -282.0341801035231),
          direction: 0.7541666982714439),
      ContactPoint(
          position: Offset(282.03444408578247, -300.3351702337832),
          direction: 0.8166263550092223),
      ContactPoint(
          position: Offset(262.62643668659973, -317.4584319394959),
          direction: 0.8791184472890796),
      ContactPoint(
          position: Offset(242.1857563367248, -333.33620863433765),
          direction: 0.941696994556219),
      ContactPoint(
          position: Offset(220.78994939841243, -347.9042340548037),
          direction: 1.0044075566571342),
      ContactPoint(
          position: Offset(198.52051657021636, -361.1021440658989),
          direction: 1.0672908327255026),
      ContactPoint(
          position: Offset(175.46269081758476, -372.87319044199216),
          direction: 1.1303486245937924),
      ContactPoint(
          position: Offset(151.70668293829874, -383.166685485816),
          direction: 1.193536756985024),
      ContactPoint(
          position: Offset(127.3463507308689, -391.93864376176805),
          direction: 1.2568434523105516),
      ContactPoint(
          position: Offset(102.47919706391208, -399.15042065459386),
          direction: 1.3201659393489873),
      ContactPoint(
          position: Offset(77.2072982066614, -404.77501874651824),
          direction: 1.383361018451426),
      ContactPoint(
          position: Offset(51.63385317835259, -408.7940237322969),
          direction: 1.446303759144345),
      ContactPoint(
          position: Offset(25.864058964400446, -411.2004421384651),
          direction: 1.5087919258318134),
      ContactPoint(
          position: Offset(0.00034398307804013443, -411.9999999999967),
          direction: 1.5707955876749704),
      ContactPoint(
          position: Offset(-25.86349090484504, -411.2004805077743),
          direction: 1.632799066015595),
      ContactPoint(
          position: Offset(-51.633255427122094, -408.7941040824081),
          direction: 1.6952872923225453),
      ContactPoint(
          position: Offset(-77.2067003625306, -404.77514445254906),
          direction: 1.7582300091952092),
      ContactPoint(
          position: Offset(-102.47857119682968, -399.1505918166019),
          direction: 1.821425279845121),
      ContactPoint(
          position: Offset(-127.34575207273232, -391.93884670716136),
          direction: 1.884747450397679),
      ContactPoint(
          position: Offset(-151.7061296905812, -383.1669281529496),
          direction: 1.9480540725375475),
      ContactPoint(
          position: Offset(-175.46215691644733, -372.8734689500944),
          direction: 2.0112425308708834),
      ContactPoint(
          position: Offset(-198.520062760107, -361.10242559041575),
          direction: 2.074300634968596),
      ContactPoint(
          position: Offset(-220.78956649286275, -347.9044989192051),
          direction: 2.137184840638927),
      ContactPoint(
          position: Offset(-242.1853103849414, -333.33650190352944),
          direction: 2.199895184284925),
      ContactPoint(
          position: Offset(-262.62608566761344, -317.45870499117274),
          direction: 2.262472422613559),
      ContactPoint(
          position: Offset(-282.03409632656974, -300.33550216787654),
          direction: 2.324963041803163),
      ContactPoint(
          position: Offset(-300.33513146108754, -282.03449070358056),
          direction: 2.387424462805366),
      ContactPoint(
          position: Offset(-317.45833513530755, -262.62654178621295),
          direction: 2.44991508476437),
      ContactPoint(
          position: Offset(-333.33614362045444, -242.18580873979704),
          direction: 2.5124927578715415),
      ContactPoint(
          position: Offset(-347.90418650544206, -220.79003563905454),
          direction: 2.575203015671126),
      ContactPoint(
          position: Offset(-361.1021239938752, -198.52058057749534),
          direction: 2.638086987060313),
      ContactPoint(
          position: Offset(-372.8731752493189, -175.46273761312221),
          direction: 2.7011449643108154),
      ContactPoint(
          position: Offset(-383.166624077048, -151.70683281489409),
          direction: 2.764333430739927),
      ContactPoint(
          position: Offset(-391.9386009527798, -127.3464214094154),
          direction: 2.827639035775448),
      ContactPoint(
          position: Offset(-399.1503660447552, -102.4794470671643),
          direction: 2.8909618615709323),
      ContactPoint(
          position: Offset(-404.7749991273511, -77.20736327840434),
          direction: 2.954157101209585),
      ContactPoint(
          position: Offset(-408.79401716179325, -51.63391834262335),
          direction: 3.017099836535886),
      ContactPoint(
          position: Offset(-411.20044332295606, -25.864060246354946),
          direction: 3.0795882423972163),
      ContactPoint(
          position: Offset(-411.9999999999962, -0.0003153083076711502),
          direction: 3.1415918575222594),
      ContactPoint(
          position: Offset(-411.2004845469956, 25.863428934131942),
          direction: 3.2035954115030454),
      ContactPoint(
          position: Offset(-408.79410533779395, 51.63325185669094),
          direction: 3.266083416634203),
      ContactPoint(
          position: Offset(-404.77515860238606, 77.2066389866778),
          direction: 3.329026405434709),
      ContactPoint(
          position: Offset(-399.15056492858497, 102.47869655598916),
          direction: 3.392221989285458),
      ContactPoint(
          position: Offset(-391.93882954359333, 127.34573213654784),
          direction: 3.455544805876479),
      ContactPoint(
          position: Offset(-383.16687278984864, 151.7061744336867),
          direction: 3.518850410642339),
      ContactPoint(
          position: Offset(-372.8734306790727, 175.46218653779),
          direction: 3.58203888191335),
      ContactPoint(
          position: Offset(-361.1024400007155, 198.5199563294504),
          direction: 3.6450971083088),
      ContactPoint(
          position: Offset(-347.9044660104924, 220.78957235446842),
          direction: 3.7079803539203735),
      ContactPoint(
          position: Offset(-333.33641737284916, 242.18543690541722),
          direction: 3.770690516594909),
      ContactPoint(
          position: Offset(-317.458622766308, 262.62624425764835),
          direction: 3.8332695242923944),
      ContactPoint(
          position: Offset(-300.335390663282, 282.03419269975166),
          direction: 3.895761796957894),
      ContactPoint(
          position: Offset(-282.03448721297326, 300.33502676925065),
          direction: 3.958221188705318),
      ContactPoint(
          position: Offset(-262.6265358509204, 317.45830336633344),
          direction: 4.020710402754923),
      ContactPoint(
          position: Offset(-242.18587487089715, 333.33604719977774),
          direction: 4.08328855945739),
      ContactPoint(
          position: Offset(-220.79011619515086, 347.9041271565097),
          direction: 4.1459974146853975),
      ContactPoint(
          position: Offset(-198.52067072008265, 361.1021274259364),
          direction: 4.208883448017893),
      ContactPoint(
          position: Offset(-175.4627392078514, 372.8731547022491),
          direction: 4.27193973846285),
      ContactPoint(
          position: Offset(-151.70673679986095, 383.1668033283451),
          direction: 4.335127422022438),
      ContactPoint(
          position: Offset(-127.34638878030266, 391.9387191065887),
          direction: 4.39843822140173),
      ContactPoint(
          position: Offset(-102.47912455858597, 399.1504685048728),
          direction: 4.461759679349729),
      ContactPoint(
          position: Offset(-77.20725754912151, 404.77505549293016),
          direction: 4.524954630444094),
      ContactPoint(
          position: Offset(-51.6337107918374, 408.7940336049516),
          direction: 4.587898216329279),
      ContactPoint(
          position: Offset(-25.863998142737326, 411.2003893009296),
          direction: 4.650384658402361),
      ContactPoint(
          position: Offset(-0.00028981628103117693, 411.9999994202751),
          direction: 4.7123877655215685),
      ContactPoint(
          position: Offset(25.86350825123992, 411.2004503640737),
          direction: 4.77439326472748),
      ContactPoint(
          position: Offset(51.63319262977629, 408.79403338017784),
          direction: 4.8368798952915295),
      ContactPoint(
          position: Offset(77.20667892827366, 404.7751218660493),
          direction: 4.899820943098116),
      ContactPoint(
          position: Offset(102.4785909183135, 399.1505940779387),
          direction: 4.963017104481238),
      ContactPoint(
          position: Offset(127.34583830445551, 391.9388411769012),
          direction: 5.026339739367649),
      ContactPoint(
          position: Offset(151.70619912992305, 383.1669324167285),
          direction: 5.089648951128762),
      ContactPoint(
          position: Offset(175.46206633134648, 372.8734133823554),
          direction: 5.1528353804188365),
      ContactPoint(
          position: Offset(198.5199549313599, 361.1025006465871),
          direction: 5.215893302089015),
      ContactPoint(
          position: Offset(220.78946749230568, 347.9044462792523),
          direction: 5.278778380096057),
      ContactPoint(
          position: Offset(242.18525260857257, 333.33649337435935),
          direction: 5.341486720602238),
      ContactPoint(
          position: Offset(262.6261254301783, 317.45861892127726),
          direction: 5.404066201963894),
      ContactPoint(
          position: Offset(282.03400184999623, 300.3354501846903),
          direction: 5.466557238296457),
      ContactPoint(
          position: Offset(300.3348922709057, 282.03456031825846),
          direction: 5.52901600287446),
      ContactPoint(
          position: Offset(317.4583028920167, 262.6265047466346),
          direction: 5.591506667580379),
      ContactPoint(
          position: Offset(333.3361730558001, 242.18563962759143),
          direction: 5.654085422395816),
      ContactPoint(
          position: Offset(347.9041243130336, 220.79004321341228),
          direction: 5.716793299884985),
      ContactPoint(
          position: Offset(361.1021899363369, 198.52057532984261),
          direction: 5.779680029605917),
      ContactPoint(
          position: Offset(372.8732213597413, 175.4625124966665),
          direction: 5.842737164198626),
      ContactPoint(
          position: Offset(383.1668023391649, 151.70664658408927),
          direction: 5.905923525047901),
      ContactPoint(
          position: Offset(391.9387794465581, 127.34620665646703),
          direction: 5.969234360604844),
      ContactPoint(
          position: Offset(399.1504702141315, 102.4790556874986),
          direction: 6.0325565804628285),
      ContactPoint(
          position: Offset(404.7750575177255, 77.20718467859076),
          direction: 6.095751862760124),
      ContactPoint(
          position: Offset(408.7940340544924, 51.63340086421675),
          direction: 6.158694844825943),
      ContactPoint(
          position: Offset(411.2003892729373, 25.863814328639158),
          direction: 6.221180947557674),
    ],
    holes: [
      GearHole(
          name: '0',
          angle: 2.3561983142799985,
          distance: 2.0496134670106378e-7),
      GearHole(
          name: '8', angle: 1.5707963449111604, distance: 8.000000144929004),
      GearHole(
          name: '9', angle: 2.3876104160129983, distance: 9.000000204860235),
      GearHole(
          name: '10', angle: 3.141592639096893, distance: 10.000000144930112),
      GearHole(
          name: '11', angle: -2.387610435351896, distance: 11.000000006438782),
      GearHole(
          name: '12', angle: -1.5707963388724062, distance: 11.999999855070998),
      GearHole(
          name: '13', angle: -0.8168140904286365, distance: 12.99999979513981),
      GearHole(
          name: '14',
          angle: 1.0352072830016957e-8,
          distance: 13.99999985506989),
      GearHole(
          name: '15', angle: 0.753982250518897, distance: 14.999999993561227),
      GearHole(
          name: '16', angle: 1.5707963358530286, distance: 16.000000144929004),
      GearHole(
          name: '17', angle: 2.3876104163495837, distance: 17.00000020486023),
      GearHole(
          name: '18', angle: 3.141592645538182, distance: 18.000000144930112),
      GearHole(
          name: '19', angle: -2.387610427510358, distance: 19.000000006438775),
      GearHole(
          name: '20', angle: -1.5707963340414024, distance: 19.999999855070996),
      GearHole(
          name: '21', angle: -0.8168140902399549, distance: 20.999999795139814),
      GearHole(
          name: '22',
          angle: 6.5876826852119965e-9,
          distance: 21.999999855069888),
      GearHole(
          name: '23', angle: 0.7539822457685156, distance: 22.99999999356122),
      GearHole(
          name: '24', angle: 1.5707963328336514, distance: 24.000000144929004),
      GearHole(
          name: '25', angle: 2.3876104164707543, distance: 25.000000204860235),
      GearHole(
          name: '26', angle: 3.1415926480156013, distance: 26.000000144930112),
      GearHole(
          name: '27', angle: -2.3876104243156573, distance: 27.000000006438782),
      GearHole(
          name: '28', angle: -1.5707963319709721, distance: 27.999999855070996),
      GearHole(
          name: '29', angle: -0.8168140901553732, distance: 28.99999979513981),
      GearHole(
          name: '30',
          angle: 4.830967294002098e-9,
          distance: 29.999999855069888),
      GearHole(
          name: '31', angle: 0.7539822434699442, distance: 30.999999993561225),
      GearHole(
          name: '32', angle: 1.5707963313239628, distance: 32.000000144929004),
      GearHole(
          name: '33', angle: 2.387610416533176, distance: 33.00000020486024),
      GearHole(
          name: '34', angle: 3.1415926493271757, distance: 34.00000014493011),
      GearHole(
          name: '35', angle: -2.387610422581391, distance: 35.00000000643878),
      GearHole(
          name: '36', angle: -1.570796330820733, distance: 35.999999855070996),
      GearHole(
          name: '37', angle: -0.8168140901073669, distance: 36.999999795139814),
      GearHole(
          name: '38', angle: 3.813921917987294e-9, distance: 37.99999985506989),
      GearHole(
          name: '39', angle: 0.7539822421143764, distance: 38.99999999356124),
      GearHole(
          name: '40', angle: 1.5707963304181496, distance: 40.000000144929004),
      GearHole(
          name: '41', angle: 2.387610416571238, distance: 41.00000020486023),
      GearHole(
          name: '42', angle: 3.141592650139103, distance: 42.00000014493011),
      GearHole(
          name: '43', angle: -2.3876104214924334, distance: 43.000000006438775),
      GearHole(
          name: '44', angle: -1.5707963300887633, distance: 43.999999855070996),
      GearHole(
          name: '45', angle: -0.8168140900764304, distance: 44.99999979513981),
      GearHole(
          name: '46',
          angle: 3.1506311475518774e-9,
          distance: 45.99999985506989),
      GearHole(
          name: '47', angle: 0.7539822412202786, distance: 46.999999993561225),
      GearHole(
          name: '48', angle: 1.5707963298142744, distance: 48.000000144929004),
      GearHole(
          name: '49', angle: 2.3876104165968717, distance: 49.000000204860235),
      GearHole(
          name: '50', angle: 3.1415926506912135, distance: 50.00000014493011),
      GearHole(
          name: '51', angle: -2.3876104207451094, distance: 51.00000000643878),
      GearHole(
          name: '52', angle: -1.5707963295820146, distance: 51.999999855070996),
      GearHole(
          name: '53', angle: -0.8168140900548324, distance: 52.9999997951398),
      GearHole(
          name: '54',
          angle: 2.6838709762914585e-9,
          distance: 53.99999985506989),
      GearHole(
          name: '55', angle: 0.7539822405862817, distance: 54.99999999356123),
      GearHole(
          name: '56', angle: 1.5707963293829348, distance: 56.000000144929004),
      GearHole(
          name: '57', angle: 2.38761041661531, distance: 57.000000204860235),
      GearHole(
          name: '58', angle: 3.1415926510910177, distance: 58.00000014493011),
      GearHole(
          name: '59', angle: -2.3876104202004496, distance: 59.00000000643877),
      GearHole(
          name: '60', angle: -1.5707963292103988, distance: 59.999999855070996),
      GearHole(name: '61', angle: -0.8168140900389, distance: 60.9999997951398),
      GearHole(
          name: '62',
          angle: 2.3375652722645703e-9,
          distance: 61.99999985506989),
      GearHole(
          name: '63', angle: 0.7539822401133003, distance: 62.999999993561225),
      GearHole(name: '64', angle: 1.57079632905943, distance: 64.000000144929),
      GearHole(
          name: '65', angle: 2.387610416629209, distance: 65.00000020486023),
      GearHole(
          name: '66', angle: 3.1415926513938994, distance: 66.00000014493011),
      GearHole(
          name: '67', angle: -2.3876104197858576, distance: 67.00000000643877),
      GearHole(
          name: '68', angle: -1.5707963289262221, distance: 67.999999855071),
      GearHole(
          name: '69', angle: -0.8168140900266619, distance: 68.99999979513981),
      GearHole(
          name: '70',
          angle: 2.0704149548812176e-9,
          distance: 69.99999985506989),
      GearHole(
          name: '71', angle: 0.7539822397469058, distance: 70.99999999356123),
      GearHole(name: '72', angle: 1.570796328807815, distance: 72.000000144929),
      GearHole(
          name: '73', angle: 2.387610416640062, distance: 73.00000020486024),
      GearHole(
          name: '74', angle: 3.1415926516312935, distance: 74.00000014493011),
      GearHole(
          name: '75', angle: -2.387610419459712, distance: 75.00000000643878),
      GearHole(
          name: '76', angle: -1.570796328701872, distance: 75.999999855071),
      GearHole(
          name: '77', angle: -0.8168140900169665, distance: 76.9999997951398),
      GearHole(
          name: '78',
          angle: 1.8580648848944106e-9,
          distance: 77.99999985506989),
      GearHole(
          name: '79', angle: 0.7539822394547182, distance: 78.99999999356123),
      GearHole(
          name: '80', angle: 1.5707963286065234, distance: 80.000000144929),
      GearHole(
          name: '81', angle: 2.3876104166487715, distance: 81.00000020486023),
      GearHole(
          name: '82', angle: 3.141592651822367, distance: 82.00000014493011),
      GearHole(
          name: '83', angle: -2.387610419196438, distance: 83.00000000643877),
      GearHole(
          name: '84', angle: -1.5707963285202553, distance: 83.999999855071),
      GearHole(
          name: '85', angle: -0.8168140900090965, distance: 84.9999997951398),
      GearHole(
          name: '86',
          angle: 1.6852216394966726e-9,
          distance: 85.99999985506989),
      GearHole(
          name: '87', angle: 0.753982239216266, distance: 86.99999999356123),
      GearHole(name: '88', angle: 1.57079632844183, distance: 88.000000144929),
      GearHole(
          name: '89', angle: 2.3876104166559147, distance: 89.00000020486023),
      GearHole(
          name: '90', angle: 3.1415926519794715, distance: 90.00000014493011),
      GearHole(
          name: '91', angle: -2.387610418979454, distance: 91.00000000643878),
      GearHole(
          name: '92', angle: -1.5707963283702242, distance: 91.999999855071),
    ],
    isRing: false,
    smallestConvexDiff: 0.062003107119207534,
    biggestConvexDiff: 0.06332282579548432,
    smallestConcaveDiff: 6.283185307179586,
    biggestConcaveDiff: 0);
