// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle63 = GearDefinition(
    id: 'circle63',
    image: 'images/gears/circle_63.png',
    thumbnailImage: 'images/gears/circle_63_thumb.png',
    size: Size(552, 552),
    toothCount: 63,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(
          position: Offset(263.69198617339134, -0.0770610049366951),
          direction: 0),
      ContactPoint(
          position: Offset(262.39937036541096, -26.35613335711898),
          direction: 0.09876952738560352),
      ContactPoint(
          position: Offset(258.50712823208806, -52.38900954309045),
          direction: 0.19851329353110891),
      ContactPoint(
          position: Offset(252.02809291864045, -77.90901095756821),
          direction: 0.298879646828758),
      ContactPoint(
          position: Offset(243.02092219407723, -102.65083367581634),
          direction: 0.39930944188852724),
      ContactPoint(
          position: Offset(231.58189882898915, -126.36291960585243),
          direction: 0.4994631648801864),
      ContactPoint(
          position: Offset(217.83619425173242, -148.8110648611659),
          direction: 0.5992102635663032),
      ContactPoint(
          position: Offset(201.9303161613614, -169.7788075725405),
          direction: 0.6985997508984756),
      ContactPoint(
          position: Offset(184.02675829116933, -189.06565779802773),
          direction: 0.7977975704764377),
      ContactPoint(
          position: Offset(164.30165038638881, -206.48567200632115),
          direction: 0.8970177590252169),
      ContactPoint(
          position: Offset(142.94455660580257, -221.86625752105178),
          direction: 0.9964820054378629),
      ContactPoint(
          position: Offset(120.15947180699996, -235.04829629717807),
          direction: 1.09633738449845),
      ContactPoint(
          position: Offset(96.16722816958506, -245.89002205065623),
          direction: 1.1965764653300752),
      ContactPoint(
          position: Offset(71.20668535111874, -254.27304344815383),
          direction: 1.2970299579095812),
      ContactPoint(
          position: Offset(45.53314389609213, -260.1091661521559),
          direction: 1.3973070597886137),
      ContactPoint(
          position: Offset(19.414255503331102, -263.35067902261284),
          direction: 1.4967966152296404),
      ContactPoint(
          position: Offset(-6.887063425239413, -263.99635858336694),
          direction: 1.595432346540572),
      ContactPoint(
          position: Offset(-33.12852838267159, -262.05557644264576),
          direction: 1.6944021596461933),
      ContactPoint(
          position: Offset(-59.05863922509781, -257.5134025513269),
          direction: 1.7943721085939321),
      ContactPoint(
          position: Offset(-84.40839328398715, -250.39515996699546),
          direction: 1.8947912421553523),
      ContactPoint(
          position: Offset(-108.91580945409888, -240.76996781241738),
          direction: 1.9951742490191586),
      ContactPoint(
          position: Offset(-132.33322399005053, -228.74152350765073),
          direction: 2.0952346810710356),
      ContactPoint(
          position: Offset(-154.4309812631249, -214.44135855055927),
          direction: 2.1948873203830317),
      ContactPoint(
          position: Offset(-174.99651867484263, -198.02003117895927),
          direction: 2.2942123048815626),
      ContactPoint(
          position: Offset(-193.83350061333962, -179.64406154639403),
          direction: 2.393384769287218),
      ContactPoint(
          position: Offset(-210.75939254419933, -159.4928678660255),
          direction: 2.4926450566655918),
      ContactPoint(
          position: Offset(-225.60479748205728, -137.75896114670053),
          direction: 2.5922010174184016),
      ContactPoint(
          position: Offset(-238.21431341740345, -114.65062586815428),
          direction: 2.6921640264729514),
      ContactPoint(
          position: Offset(-248.4512630343056, -90.39312748558518),
          direction: 2.792480595334121),
      ContactPoint(
          position: Offset(-256.2043881994662, -65.22993939964041),
          direction: 2.892930186438611),
      ContactPoint(
          position: Offset(-261.394709685428, -39.41963222844385),
          direction: 2.993076772524504),
      ContactPoint(
          position: Offset(-263.98542283103075, -13.231245748294697),
          direction: 3.092297418476547),
      ContactPoint(
          position: Offset(-263.9854093065382, 13.077422599729953),
          direction: 3.1908886349692955),
      ContactPoint(
          position: Offset(-261.39469080400335, 39.2656710838786),
          direction: 3.2901092321177385),
      ContactPoint(
          position: Offset(-256.20436312790054, 65.07594618093076),
          direction: 3.3902556985850105),
      ContactPoint(
          position: Offset(-248.45120586507983, 90.23919368007905),
          direction: 3.49070516403098),
      ContactPoint(
          position: Offset(-238.21426926181488, 114.49661521819226),
          direction: 3.591021701528515),
      ContactPoint(
          position: Offset(-225.60475705387665, 137.60494344374712),
          direction: 3.690984045030212),
      ContactPoint(
          position: Offset(-210.75936549153573, 159.3388505283664),
          direction: 3.790540824752205),
      ContactPoint(
          position: Offset(-193.8334085387866, 179.4900627586556),
          direction: 3.889801536335767),
      ContactPoint(
          position: Offset(-174.99646765079467, 197.8659625028683),
          direction: 3.9889744339443465),
      ContactPoint(
          position: Offset(-154.43083426129098, 214.28731049134763),
          direction: 4.088298196629286),
      ContactPoint(
          position: Offset(-132.33311428065016, 228.58748268407356),
          direction: 4.187950170597036),
      ContactPoint(
          position: Offset(-108.91584121575804, 240.61584069076108),
          direction: 4.288012339734376),
      ContactPoint(
          position: Offset(-84.40838040768077, 250.24100568576273),
          direction: 4.388393855587244),
      ContactPoint(
          position: Offset(-59.058682857092506, 257.35928232790025),
          direction: 4.488812077822652),
      ContactPoint(
          position: Offset(-33.12849637335998, 261.9014843012172),
          direction: 4.588783272800237),
      ContactPoint(
          position: Offset(-6.887025652146468, 263.84224124841853),
          direction: 4.687754837400467),
      ContactPoint(
          position: Offset(19.414375253186392, 263.1964948979127),
          direction: 4.786388498047856),
      ContactPoint(
          position: Offset(45.53326148160997, 259.9550508887112),
          direction: 4.885877867962282),
      ContactPoint(
          position: Offset(71.20666059009976, 254.11890360927447),
          direction: 4.986155847539115),
      ContactPoint(
          position: Offset(96.16731675900671, 245.73588976046005),
          direction: 5.086608576545957),
      ContactPoint(
          position: Offset(120.15945067174184, 234.89416756130248),
          direction: 5.186848801629967),
      ContactPoint(
          position: Offset(142.94464965224884, 221.7120735094824),
          direction: 5.286703450004215),
      ContactPoint(
          position: Offset(164.30164726020158, 206.33152197488835),
          direction: 5.386167214788161),
      ContactPoint(
          position: Offset(184.02681399303407, 188.91152573200753),
          direction: 5.485387115819567),
      ContactPoint(
          position: Offset(201.9304150801305, 169.62460049855457),
          direction: 5.584586510709025),
      ContactPoint(
          position: Offset(217.836226923951, 148.6568862907572),
          direction: 5.683975361975757),
      ContactPoint(
          position: Offset(231.58192809119012, 126.20878463807679),
          direction: 5.7837219238762),
      ContactPoint(
          position: Offset(243.02095477387078, 102.49667626135752),
          direction: 5.883876307315858),
      ContactPoint(
          position: Offset(252.02809370665491, 77.75488639011141),
          direction: 5.984305883369881),
      ContactPoint(
          position: Offset(258.5071285158761, 52.23491664005614),
          direction: 6.084672133565123),
      ContactPoint(
          position: Offset(262.3993704363601, 26.2019801136749),
          direction: 6.184415839752251),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(
          name: '8', angle: 1.5957296018233869, distance: 7.999999999999999),
      GearHole(name: '9', angle: 2.3935944027350806, distance: 9),
      GearHole(
          name: '10', angle: 3.091726103532812, distance: 9.999999999999998),
      GearHole(name: '11', angle: -2.39359440273508, distance: 11),
      GearHole(
          name: '12', angle: -1.5957296018233873, distance: 12.000000000000007),
      GearHole(name: '13', angle: -0.7978648009116931, distance: 13),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7978648009116941, distance: 14.999999999999996),
      GearHole(
          name: '16', angle: 1.5957296018233873, distance: 15.999999999999998),
      GearHole(
          name: '17', angle: 2.3935944027350806, distance: 17.000000000000004),
      GearHole(name: '18', angle: 3.0917261035328125, distance: 18),
      GearHole(name: '19', angle: -2.3935944027350806, distance: 19),
      GearHole(
          name: '20', angle: -1.5957296018233875, distance: 19.999999999999993),
      GearHole(
          name: '21', angle: -0.7978648009116932, distance: 21.000000000000004),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(
          name: '23', angle: 0.7978648009116937, distance: 22.999999999999996),
      GearHole(name: '24', angle: 1.595729601823387, distance: 24),
      GearHole(name: '25', angle: 2.3935944027350806, distance: 25),
      GearHole(
          name: '26', angle: 3.0917261035328125, distance: 25.999999999999996),
      GearHole(
          name: '27', angle: -2.39359440273508, distance: 27.000000000000004),
      GearHole(
          name: '28', angle: -1.5957296018233875, distance: 28.000000000000007),
      GearHole(
          name: '29', angle: -0.7978648009116937, distance: 28.999999999999996),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
      GearHole(
          name: '31', angle: 0.7978648009116937, distance: 30.999999999999996),
      GearHole(
          name: '32', angle: 1.5957296018233873, distance: 31.999999999999996),
      GearHole(name: '33', angle: 2.3935944027350806, distance: 33),
      GearHole(name: '34', angle: 3.0917261035328125, distance: 34),
      GearHole(
          name: '35', angle: -2.39359440273508, distance: 34.99999999999999),
      GearHole(
          name: '36', angle: -1.5957296018233873, distance: 35.99999999999999),
      GearHole(name: '37', angle: -0.7978648009116935, distance: 37),
      GearHole(name: '38', angle: -1.8698493046318425e-16, distance: 38),
      GearHole(name: '39', angle: 0.7978648009116935, distance: 39),
      GearHole(name: '40', angle: 1.595729601823387, distance: 40),
      GearHole(name: '41', angle: 2.39359440273508, distance: 41),
      GearHole(name: '42', angle: 3.0917261035328125, distance: 42),
      GearHole(
          name: '43', angle: -2.3935944027350806, distance: 42.99999999999999),
      GearHole(
          name: '44', angle: -1.5957296018233873, distance: 44.00000000000001),
      GearHole(
          name: '45', angle: -0.7978648009116933, distance: 44.99999999999999),
      GearHole(name: '46', angle: -3.089316242435218e-16, distance: 46),
      GearHole(
          name: '47', angle: 0.7978648009116938, distance: 46.99999999999999),
      GearHole(name: '48', angle: 1.5957296018233873, distance: 48),
      GearHole(name: '49', angle: 2.3935944027350806, distance: 49),
      GearHole(
          name: '50', angle: 3.0917261035328125, distance: 49.99999999999999),
      GearHole(name: '51', angle: -2.39359440273508, distance: 51),
      GearHole(
          name: '52', angle: -1.5957296018233875, distance: 51.99999999999999),
      GearHole(
          name: '53', angle: -0.7978648009116933, distance: 52.99999999999999),
      GearHole(name: '54', angle: -2.631639762074445e-16, distance: 54),
      GearHole(
          name: '55', angle: 0.7978648009116938, distance: 54.99999999999999),
    ]);
