// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle80 = GearDefinition(
    id: 'circle80',
    image: 'images/gears/circle_80.png',
    thumbnailImage: 'images/gears/circle_80_thumb.png',
    size: Size(688, 688),
    center: Offset(344, 344),
    toothCount: 80,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(
          position: Offset(331.99999987566844, 1.280568540096283e-9),
          direction: 0),
      ContactPoint(
          position: Offset(330.9927293866217, -26.041797221985902),
          direction: 0.07762975474061662),
      ContactPoint(
          position: Offset(327.95959175877607, -51.93420367081445),
          direction: 0.15595311861652306),
      ContactPoint(
          position: Offset(322.89916494728976, -77.51444188045997),
          direction: 0.23482909761418735),
      ContactPoint(
          position: Offset(315.8336229303281, -102.61794593291795),
          direction: 0.3139491648890118),
      ContactPoint(
          position: Offset(306.80462166977503, -127.08381456852811),
          direction: 0.3930602234527498),
      ContactPoint(
          position: Offset(295.87299913731584, -150.7584306286767),
          direction: 0.4719866373529644),
      ContactPoint(
          position: Offset(283.1128025722362, -173.49632505403127),
          direction: 0.5506611741161773),
      ContactPoint(
          position: Offset(268.60975911794435, -195.1604580469792),
          direction: 0.6290789091775908),
      ContactPoint(
          position: Offset(252.45804020911456, -215.62191622765758),
          direction: 0.7072918238820769),
      ContactPoint(
          position: Offset(234.75945572923342, -234.75945436677367),
          direction: 0.7853976262965023),
      ContactPoint(
          position: Offset(215.62196376973606, -252.45802887307354),
          direction: 0.863505968683735),
      ContactPoint(
          position: Offset(195.16039603838905, -268.60971823833273),
          direction: 0.9417159326482532),
      ContactPoint(
          position: Offset(173.49637790746525, -283.1128804578754),
          direction: 1.0201329564530628),
      ContactPoint(
          position: Offset(150.75853907942798, -295.87298326170463),
          direction: 1.0988109522136131),
      ContactPoint(
          position: Offset(127.08398030803608, -306.80457432698176),
          direction: 1.177734905796176),
      ContactPoint(
          position: Offset(102.61810063032537, -315.83365189239595),
          direction: 1.256846966297502),
      ContactPoint(
          position: Offset(77.51449468324037, -322.8991651030884),
          direction: 1.3359679240284308),
      ContactPoint(
          position: Offset(51.93422404439266, -327.9596163455989),
          direction: 1.414844053516469),
      ContactPoint(
          position: Offset(26.04185044319046, -330.99268522561766),
          direction: 1.493167214898695),
      ContactPoint(
          position: Offset(-0.00009210431781452106, -332),
          direction: 1.5707963623992196),
      ContactPoint(
          position: Offset(-26.041913300214926, -330.9926833151058),
          direction: 1.6484255701875412),
      ContactPoint(
          position: Offset(-51.93425541179638, -327.9596214962874),
          direction: 1.7267486507856376),
      ContactPoint(
          position: Offset(-77.51448236032633, -322.8991720895879),
          direction: 1.805624959815174),
      ContactPoint(
          position: Offset(-102.6180362135911, -315.83366832987883),
          direction: 1.8847453692255396),
      ContactPoint(
          position: Offset(-127.08392781807676, -306.8046115460711),
          direction: 1.9638571197084929),
      ContactPoint(
          position: Offset(-150.75857535793466, -295.8729918919701),
          direction: 2.04278221711923),
      ContactPoint(
          position: Offset(-173.49646699182838, -283.11281727633025),
          direction: 2.121459431441515),
      ContactPoint(
          position: Offset(-195.16057275371793, -268.609654745042),
          direction: 2.199877609341234),
      ContactPoint(
          position: Offset(-215.62197805093476, -252.45796347188738),
          direction: 2.2780882233085986),
      ContactPoint(
          position: Offset(-234.75950756067684, -234.75939515460044),
          direction: 2.356194812452774),
      ContactPoint(
          position: Offset(-252.45806837076506, -215.62184931436965),
          direction: 2.4343014741340605),
      ContactPoint(
          position: Offset(-268.6097284105541, -195.16044910027009),
          direction: 2.512511521259884),
      ContactPoint(
          position: Offset(-283.1128543939495, -173.4964167581631),
          direction: 2.5909299725329604),
      ContactPoint(
          position: Offset(-295.8730326865316, -150.75846348026528),
          direction: 2.6696072255156986),
      ContactPoint(
          position: Offset(-306.80458928295945, -127.08394174668342),
          direction: 2.748531969343938),
      ContactPoint(
          position: Offset(-315.83366201023165, -102.61802305660432),
          direction: 2.827643416002293),
      ContactPoint(
          position: Offset(-322.8991649539602, -77.51448069587917),
          direction: 2.906764152424632),
      ContactPoint(
          position: Offset(-327.9596274062342, -51.93416333728424),
          direction: 2.9856403630184305),
      ContactPoint(
          position: Offset(-330.9926887905635, -26.041817977859118),
          direction: 3.0639637147818855),
      ContactPoint(
          position: Offset(-331.9999999999998, 0.00012436451009131968),
          direction: 3.141592844666212),
      ContactPoint(
          position: Offset(-330.9926785469262, 26.041978889767336),
          direction: 3.2192222879471504),
      ContactPoint(
          position: Offset(-327.95959451506656, 51.93437841187553),
          direction: 3.2975450663931634),
      ContactPoint(
          position: Offset(-322.8991606648023, 77.51455897556461),
          direction: 3.376421324683694),
      ContactPoint(
          position: Offset(-315.8336514469405, 102.61810545196097),
          direction: 3.4555424255334364),
      ContactPoint(
          position: Offset(-306.8045685319545, 127.08398091260433),
          direction: 3.534654117796534),
      ContactPoint(
          position: Offset(-295.87295382513594, 150.75860584154432),
          direction: 3.6135785522489403),
      ContactPoint(
          position: Offset(-283.11270293236976, 173.49665623358968),
          direction: 3.6922563703294484),
      ContactPoint(
          position: Offset(-268.60958989648225, 195.1605880602914),
          direction: 3.7706739537429046),
      ContactPoint(
          position: Offset(-252.45794384611597, 215.6220352935402),
          direction: 3.8488841478119387),
      ContactPoint(
          position: Offset(-234.75930588791425, 234.75958157112802),
          direction: 3.9269917837701906),
      ContactPoint(
          position: Offset(-215.62187205482834, 252.4580390713502),
          direction: 4.0050969944758466),
      ContactPoint(
          position: Offset(-195.16040407593732, 268.6098152295267),
          direction: 4.083309356106615),
      ContactPoint(
          position: Offset(-173.49634285352215, 283.11280121494593),
          direction: 4.161727570100351),
      ContactPoint(
          position: Offset(-150.7584829307458, 295.87300378500294),
          direction: 4.240403171876785),
      ContactPoint(
          position: Offset(-127.08373969020178, 306.80462126050287),
          direction: 4.319328640556742),
      ContactPoint(
          position: Offset(-102.61802201026748, 315.83362316705086),
          direction: 4.3984398454785225),
      ContactPoint(
          position: Offset(-77.5145496426648, 322.8991038403535),
          direction: 4.477559812074414),
      ContactPoint(
          position: Offset(-51.934306784219295, 327.9595900864498),
          direction: 4.556434897139778),
      ContactPoint(
          position: Offset(-26.041826737583385, 330.9927295999448),
          direction: 4.634759319893988),
      ContactPoint(
          position: Offset(-0.00003064190969091553, 332.00000000128057),
          direction: 4.71238898038469),
      ContactPoint(
          position: Offset(26.04191747785927, 330.99272964380015),
          direction: 4.790018593750521),
      ContactPoint(
          position: Offset(51.934279934037974, 327.9595894707237),
          direction: 4.868343393977105),
      ContactPoint(
          position: Offset(77.51453496028233, 322.8991036429613),
          direction: 4.947218219391095),
      ContactPoint(
          position: Offset(102.61798061118142, 315.833621665064),
          direction: 5.026338520597023),
      ContactPoint(
          position: Offset(127.08385482772142, 306.80455666997284),
          direction: 5.105450093757263),
      ContactPoint(
          position: Offset(150.7584829242685, 295.8729426262189),
          direction: 5.184374811552182),
      ContactPoint(
          position: Offset(173.49633064472133, 283.11279918952175),
          direction: 5.263050713239477),
      ContactPoint(
          position: Offset(195.16056473545163, 268.609637173244),
          direction: 5.3414678895622805),
      ContactPoint(
          position: Offset(215.62191153442848, 252.45804424145297),
          direction: 5.419680303232849),
      ContactPoint(
          position: Offset(234.75939013662577, 234.7595123325504),
          direction: 5.497787143782138),
      ContactPoint(
          position: Offset(252.45810404700342, 215.621851916362),
          direction: 5.57589384274526),
      ContactPoint(
          position: Offset(268.60976100726583, 195.16040967689827),
          direction: 5.65410666558089),
      ContactPoint(
          position: Offset(283.11280556696954, 173.49632017929542),
          direction: 5.732524610007191),
      ContactPoint(
          position: Offset(295.8730050431207, 150.75832750908768),
          direction: 5.8111997522939465),
      ContactPoint(
          position: Offset(306.8045552857555, 127.08382747118746),
          direction: 5.890123919971921),
      ContactPoint(
          position: Offset(315.83362084401193, 102.61801339624337),
          direction: 5.969235579305266),
      ContactPoint(
          position: Offset(322.89910351734915, 77.51453508589447),
          direction: 6.048356068173181),
      ContactPoint(
          position: Offset(327.95959004879825, 51.93430610173249),
          direction: 6.127231271127062),
      ContactPoint(
          position: Offset(330.992729518188, 26.041795533158908),
          direction: 6.205555693813755),
    ],
    holes: [
      GearHole(
          name: '0',
          angle: -3.1312933923010497,
          distance: 3.1084539556113855e-8),
      GearHole(
          name: '8', angle: 1.5707963306802581, distance: 7.999999999679858),
      GearHole(name: '9', angle: 2.3561944926596, distance: 9.000000021752541),
      GearHole(
          name: '10', angle: -3.141592653557779, distance: 10.000000031082891),
      GearHole(
          name: '11', angle: -2.356194492169849, distance: 11.000000022205306),
      GearHole(
          name: '12', angle: -1.5707963293851377, distance: 12.000000000320142),
      GearHole(
          name: '13', angle: -0.785398165105548, distance: 12.999999978247455),
      GearHole(
          name: '14',
          angle: -2.2867295409632315e-11,
          distance: 13.999999968917109),
      GearHole(
          name: '15', angle: 0.7853981648476182, distance: 14.999999977794703),
      GearHole(
          name: '16', angle: 1.5707963287375775, distance: 15.999999999679858),
      GearHole(
          name: '17', angle: 2.356194491498539, distance: 17.000000021752545),
      GearHole(
          name: '18', angle: -3.1415926535720073, distance: 18.00000003108289),
      GearHole(
          name: '19', angle: -2.3561944913372166, distance: 19.0000000222053),
      GearHole(
          name: '20', angle: -1.5707963283490414, distance: 20.000000000320142),
      GearHole(
          name: '21', angle: -0.7853981644548439, distance: 20.999999978247452),
      GearHole(
          name: '22',
          angle: -1.4551915248926652e-11,
          distance: 21.99999996891711),
      GearHole(
          name: '23', angle: 0.7853981643432111, distance: 22.9999999777947),
      GearHole(
          name: '24', angle: 1.5707963280900172, distance: 23.999999999679858),
      GearHole(
          name: '25', angle: 2.356194491080557, distance: 25.000000021752548),
      GearHole(
          name: '26', angle: -3.1415926535774803, distance: 26.00000003108289),
      GearHole(
          name: '27', angle: -2.356194490997995, distance: 27.0000000222053),
      GearHole(
          name: '28', angle: -1.570796327905, distance: 28.000000000320142),
      GearHole(
          name: '29', angle: -0.7853981641631486, distance: 28.999999978247455),
      GearHole(
          name: '30',
          angle: -1.0671878207016626e-11,
          distance: 29.99999996891711),
      GearHole(
          name: '31', angle: 0.7853981640991431, distance: 30.9999999777947),
      GearHole(
          name: '32', angle: 1.5707963277662371, distance: 31.999999999679858),
      GearHole(
          name: '33', angle: 2.3561944908652324, distance: 33.00000002175255),
      GearHole(
          name: '34', angle: -3.141592653580377, distance: 34.00000003108289),
      GearHole(
          name: '35', angle: -2.3561944908138464, distance: 35.0000000222053),
      GearHole(
          name: '36', angle: -1.5707963276583103, distance: 36.00000000032014),
      GearHole(
          name: '37', angle: -0.7853981639975918, distance: 36.99999997824746),
      GearHole(
          name: '38',
          angle: -8.425167003701697e-12,
          distance: 37.99999996891711),
      GearHole(
          name: '39', angle: 0.7853981639552057, distance: 38.9999999777947),
      GearHole(
          name: '40', angle: 1.570796327571969, distance: 39.99999999967986),
      GearHole(
          name: '41', angle: 2.3561944907339374, distance: 41.00000002175255),
      GearHole(
          name: '42', angle: -3.1415926535821708, distance: 42.00000003108289),
      GearHole(
          name: '43', angle: -2.3561944906982184, distance: 43.00000002220529),
      GearHole(
          name: '44', angle: -1.5707963275013264, distance: 44.00000000032014),
      GearHole(
          name: '45', angle: -0.7853981638908996, distance: 44.999999978247445),
      GearHole(
          name: '46',
          angle: -6.959920567285226e-12,
          distance: 45.99999996891711),
      GearHole(
          name: '47', angle: 0.7853981638602682, distance: 46.99999997779471),
      GearHole(
          name: '48', angle: 1.570796327442457, distance: 47.99999999967986),
      GearHole(
          name: '49', angle: 2.356194490645514, distance: 49.00000002175255),
      GearHole(
          name: '50', angle: -3.1415926535833902, distance: 50.00000003108289),
      GearHole(
          name: '51', angle: -2.3561944906188654, distance: 51.000000022205306),
      GearHole(
          name: '52', angle: -1.5707963273926449, distance: 52.00000000032014),
      GearHole(
          name: '53', angle: -0.7853981638164166, distance: 52.99999997824746),
      GearHole(
          name: '54',
          angle: -5.928821223390201e-12,
          distance: 53.99999996891711),
      GearHole(
          name: '55', angle: 0.785398163792949, distance: 54.999999977794694),
      GearHole(
          name: '56', angle: 1.5707963273499483, distance: 55.99999999967986),
      GearHole(
          name: '57', angle: 2.3561944905819114, distance: 57.000000021752555),
      GearHole(
          name: '58', angle: -3.1415926535842735, distance: 58.00000003108289),
      GearHole(
          name: '59', angle: -2.356194490561032, distance: 59.0000000222053),
      GearHole(
          name: '60', angle: -1.570796327312945, distance: 60.00000000032014),
      GearHole(
          name: '61', angle: -0.7853981637614699, distance: 60.999999978247445),
      GearHole(
          name: '62',
          angle: -5.163812032891809e-12,
          distance: 61.99999996891711),
      GearHole(
          name: '63', angle: 0.7853981637427265, distance: 62.99999997779471),
      GearHole(
          name: '64', angle: 1.570796327280567, distance: 63.99999999967986),
      GearHole(
          name: '65', angle: 2.356194490533965, distance: 65.00000002175254),
      GearHole(
          name: '66', angle: -3.1415926535849428, distance: 66.00000003108289),
      GearHole(
          name: '67', angle: -2.35619449051701, distance: 67.00000002220531),
      GearHole(
          name: '68', angle: -1.5707963272519982, distance: 68.00000000032014),
      GearHole(
          name: '69', angle: -0.7853981637192642, distance: 68.99999997824744),
      GearHole(
          name: '70',
          angle: -4.573662086013551e-12,
          distance: 69.99999996891711),
      GearHole(
          name: '71', angle: 0.785398163703822, distance: 70.9999999777947),
      GearHole(
          name: '72', angle: 1.5707963272266035, distance: 71.99999999967986),
    ]);
