// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final circle40 = GearDefinition(
    id: 'circle40',
    image: 'images/gears/circle_40.png',
    thumbnailImage: 'images/gears/circle_40_thumb.png',
    size: Size(368, 368),
    toothCount: 40,
    entitlement: Entitlement.free,
    package: Package.free,
    points: [
      ContactPoint(position: Offset(172, 0), direction: 0),
      ContactPoint(
          position: Offset(169.9064662671248, -26.9022939571596),
          direction: 0.1562282800299899),
      ContactPoint(
          position: Offset(163.62355673151558, -53.16182460065294),
          direction: 0.3139446625529736),
      ContactPoint(
          position: Offset(153.28118462503454, -78.1058145603878),
          direction: 0.4718612264539148),
      ContactPoint(
          position: Offset(139.15701823304647, -101.1096413886663),
          direction: 0.6289769753677446),
      ContactPoint(
          position: Offset(121.62235993522641, -121.62237654981817),
          direction: 0.7853989176384646),
      ContactPoint(
          position: Offset(101.10960824465447, -139.1569993343562),
          direction: 0.9418188358469912),
      ContactPoint(
          position: Offset(78.10589241418137, -153.28116459821408),
          direction: 1.0989335268412717),
      ContactPoint(
          position: Offset(53.16190263481536, -163.62357094844936),
          direction: 1.256851511771501),
      ContactPoint(
          position: Offset(26.90230126191656, -169.90647896406819),
          direction: 1.414568717772978),
      ContactPoint(
          position: Offset(-0.00004514782698021653, -172.00000000064026),
          direction: 1.570796274416546),
      ContactPoint(
          position: Offset(-26.902319233278515, -169.90648115941173),
          direction: 1.7270241646514766),
      ContactPoint(
          position: Offset(-53.161871445158496, -163.62357879605617),
          direction: 1.8847410829336102),
      ContactPoint(
          position: Offset(-78.10590345869535, -153.2811724708523),
          direction: 2.042658732473855),
      ContactPoint(
          position: Offset(-101.10969654262513, -139.15696754136337),
          direction: 2.199774268570569),
      ContactPoint(
          position: Offset(-121.6223960094649, -121.62233666088622),
          direction: 2.3561948403761925),
      ContactPoint(
          position: Offset(-139.1570076956379, -101.10963012687635),
          direction: 2.5126152663112946),
      ContactPoint(
          position: Offset(-153.28119269403442, -78.10584780000178),
          direction: 2.669730458688204),
      ContactPoint(
          position: Offset(-163.6235769020517, -53.16186083741208),
          direction: 2.8276481584015953),
      ContactPoint(
          position: Offset(-169.90648449286127, -26.902270457591914),
          direction: 2.985365068758023),
      ContactPoint(
          position: Offset(-171.9999999378336, 0.00006494924514152817),
          direction: 3.1415929797638675),
      ContactPoint(
          position: Offset(-169.9064675161224, 26.90238136447965),
          direction: 3.2978205839095347),
      ContactPoint(
          position: Offset(-163.6235702026404, 53.16190640047873),
          direction: 3.4555377985446225),
      ContactPoint(
          position: Offset(-153.28114981133248, 78.10592574463062),
          direction: 3.613455716707067),
      ContactPoint(
          position: Offset(-139.15693408895117, 101.1097055842725),
          direction: 3.770570740905274),
      ContactPoint(
          position: Offset(-121.62230041346292, 121.6224246274938),
          direction: 3.9269904937406737),
      ContactPoint(
          position: Offset(-101.1096130495303, 139.1570471657008),
          direction: 4.0834117805176025),
      ContactPoint(
          position: Offset(-78.10584593801904, 153.28118418614113),
          direction: 4.240527673466895),
      ContactPoint(
          position: Offset(-53.161863821902365, 163.62355638271669),
          direction: 4.398444223708156),
      ContactPoint(
          position: Offset(-26.902338890345447, 169.90646639993582),
          direction: 4.556160771486109),
      ContactPoint(
          position: Offset(-0.000015258789064704363, 172),
          direction: 4.71238898038469),
      ContactPoint(
          position: Offset(26.902323350496097, 169.90646644420613),
          direction: 4.8686171655728145),
      ContactPoint(
          position: Offset(53.16184647683794, 163.6235545829611),
          direction: 5.026334222725791),
      ContactPoint(
          position: Offset(78.10585298291296, 153.28115007348242),
          direction: 5.184250946400853),
      ContactPoint(
          position: Offset(101.10969262325493, 139.15695877752472),
          direction: 5.341365732002236),
      ContactPoint(
          position: Offset(121.62233764615706, 121.62239502419469),
          direction: 5.497787359279919),
      ContactPoint(
          position: Offset(139.15702076600533, 101.10961501898564),
          direction: 5.654208690597433),
      ContactPoint(
          position: Offset(153.2811819802361, 78.10577396675058),
          direction: 5.8113235958456135),
      ContactPoint(
          position: Offset(163.62355463871776, 53.16186156390056),
          direction: 5.969240079884428),
      ContactPoint(
          position: Offset(169.90646644420613, 26.902338609285167),
          direction: 6.126957121991461),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.356194490192345, distance: 10.999999999999998),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(name: '13', angle: -0.7853981633974486, distance: 13),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974482, distance: 14.999999999999998),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(name: '17', angle: 2.356194490192345, distance: 17),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(
          name: '25', angle: 2.356194490192345, distance: 24.999999999999996),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(
          name: '29', angle: -0.7853981633974486, distance: 29.000000000000004),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
      GearHole(
          name: '31', angle: 0.7853981633974481, distance: 31.000000000000004),
      GearHole(name: '32', angle: 1.5707963267948966, distance: 32),
    ]);
