// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final heartRing144 = GearDefinition(
    id: 'heartRing144',
    image: 'images/gears/heart_ring_144.png',
    thumbnailImage: 'images/gears/heart_ring_144_thumb.png',
    size: Size(1332, 1196),
    center: Offset(666, 598),
    toothCount: 144,
    entitlement: Entitlement.specialgears,
    package: Package.specialgears,
    points: [
      ContactPoint(
          position: Offset(-253.81862312918753, -520.5832591444229),
          direction: 4.599605287405328),
      ContactPoint(
          position: Offset(-230.15312576720257, -516.6079912284027),
          direction: 4.501669675536758),
      ContactPoint(
          position: Offset(-206.71489922759466, -510.4877858323381),
          direction: 4.422374840790344),
      ContactPoint(
          position: Offset(-183.53614270492778, -502.6793448675615),
          direction: 4.362387843607191),
      ContactPoint(
          position: Offset(-160.56914291367337, -493.6311182150316),
          direction: 4.321103181777033),
      ContactPoint(
          position: Offset(-137.7068570196732, -483.76456795092156),
          direction: 4.2976903202517125),
      ContactPoint(
          position: Offset(-114.80054936650018, -473.47910552410514),
          direction: 4.291641121340711),
      ContactPoint(
          position: Offset(-91.60076421850995, -463.13543686237216),
          direction: 4.309918393004635),
      ContactPoint(
          position: Offset(-67.45502305870443, -453.356374445546),
          direction: 4.383027911893589),
      ContactPoint(
          position: Offset(-41.89965307208386, -446.1960608091771),
          direction: 4.497427480834073),
      ContactPoint(
          position: Offset(-15.52954564931022, -442.03844787789),
          direction: 4.624800550121267),
      ContactPoint(
          position: Offset(11.337924680945008, -441.55001748626836),
          direction: 4.7698498861091485),
      ContactPoint(
          position: Offset(37.872486199885884, -445.0911212342069),
          direction: 4.903371330471584),
      ContactPoint(
          position: Offset(63.62343166385583, -451.63339534496623),
          direction: 5.020225811218477),
      ContactPoint(
          position: Offset(88.06349845505777, -461.00756599577),
          direction: 5.104214162987931),
      ContactPoint(
          position: Offset(111.39873218526016, -471.3329962563553),
          direction: 5.132209960544648),
      ContactPoint(
          position: Offset(134.33542985469225, -481.65629544886576),
          direction: 5.129759711771627),
      ContactPoint(
          position: Offset(157.19360350545492, -491.64201053494685),
          direction: 5.10996453964849),
      ContactPoint(
          position: Offset(180.12850578830836, -500.89317479243135),
          direction: 5.072440644646676),
      ContactPoint(
          position: Offset(203.25715660732294, -508.9942826144597),
          direction: 5.016401116759415),
      ContactPoint(
          position: Offset(226.6415151661517, -515.501947165853),
          direction: 4.941113927740229),
      ContactPoint(
          position: Offset(250.26717076153818, -519.9579296300341),
          direction: 4.84687207745313),
      ContactPoint(
          position: Offset(274.0266888986831, -521.933513141776),
          direction: 4.736188686609649),
      ContactPoint(
          position: Offset(298.10675063238045, -521.0710569229151),
          direction: 4.646920175966697),
      ContactPoint(
          position: Offset(322.40182570530925, -518.7387825996591),
          direction: 4.582753794634637),
      ContactPoint(
          position: Offset(346.32849205183555, -514.7956068516412),
          direction: 4.505661036844448),
      ContactPoint(
          position: Offset(369.72856976697193, -508.8214137236898),
          direction: 4.420333565524787),
      ContactPoint(
          position: Offset(392.5692881588499, -500.89080731599677),
          direction: 4.3372677750690585),
      ContactPoint(
          position: Offset(414.7098970451786, -491.1068680721977),
          direction: 4.256478611097255),
      ContactPoint(
          position: Offset(436.0243205260256, -479.5797151429576),
          direction: 4.177795673310894),
      ContactPoint(
          position: Offset(456.39800336730065, -466.4212309848288),
          direction: 4.100909541778558),
      ContactPoint(
          position: Offset(475.726235150071, -451.74221916884886),
          direction: 4.025421722499622),
      ContactPoint(
          position: Offset(493.9104014773671, -435.65060253155843),
          direction: 3.950858030007617),
      ContactPoint(
          position: Offset(510.85475851949667, -418.2512459509412),
          direction: 3.8767043277880737),
      ContactPoint(
          position: Offset(526.4638896604541, -399.6468473720483),
          direction: 3.8024355487623906),
      ContactPoint(
          position: Offset(540.641513010633, -379.9390912920881),
          direction: 3.7275270404634244),
      ContactPoint(
          position: Offset(553.28795602948, -359.23175062425014),
          direction: 3.6514772394586057),
      ContactPoint(
          position: Offset(564.3010728626351, -337.63296263011),
          direction: 3.5738469442198473),
      ContactPoint(
          position: Offset(573.5769829859104, -315.25883808028595),
          direction: 3.4942673590091173),
      ContactPoint(
          position: Offset(581.0123181589867, -292.2358825440497),
          direction: 3.412475831716911),
      ContactPoint(
          position: Offset(586.5082571985372, -268.7033189473488),
          direction: 3.3283791133769527),
      ContactPoint(
          position: Offset(589.9767059441922, -244.81471959871973),
          direction: 3.2420820395325247),
      ContactPoint(
          position: Offset(591.3481045118497, -220.6436323228056),
          direction: 3.161725489841814),
      ContactPoint(
          position: Offset(590.9441231096716, -196.308426863198),
          direction: 3.0916635111897546),
      ContactPoint(
          position: Offset(588.929413897102, -172.1312186517501),
          direction: 3.015333613927492),
      ContactPoint(
          position: Offset(584.8155901851821, -148.09598407794715),
          direction: 2.94913022111498),
      ContactPoint(
          position: Offset(579.5413386500679, -124.02959092005958),
          direction: 2.9039230577355952),
      ContactPoint(
          position: Offset(573.20951932704, -100.19121890503594),
          direction: 2.8609776298263023),
      ContactPoint(
          position: Offset(565.8751238278771, -76.61730437969389),
          direction: 2.819998881843195),
      ContactPoint(
          position: Offset(557.5965560448614, -53.331031677185806),
          direction: 2.7811269154310296),
      ContactPoint(
          position: Offset(548.433951450131, -30.349109445431495),
          direction: 2.7444980366347553),
      ContactPoint(
          position: Offset(538.4509728070354, -7.680687545861051),
          direction: 2.710201687884134),
      ContactPoint(
          position: Offset(527.7104276606508, 14.669913959405779),
          direction: 2.6782216275076207),
      ContactPoint(
          position: Offset(516.2733850957751, 36.703272999603314),
          direction: 2.6485392067114653),
      ContactPoint(
          position: Offset(504.1987358766702, 58.42585496006106),
          direction: 2.6211548885471183),
      ContactPoint(
          position: Offset(491.5449643420753, 79.84712827691648),
          direction: 2.596003662440554),
      ContactPoint(
          position: Offset(478.3654886844804, 100.97987054222406),
          direction: 2.573006769595276),
      ContactPoint(
          position: Offset(464.71196332755545, 121.83989274864783),
          direction: 2.5521332365151697),
      ContactPoint(
          position: Offset(450.63348509411924, 142.44597196854073),
          direction: 2.5333361249507),
      ContactPoint(
          position: Offset(436.177308813928, 162.81797588114839),
          direction: 2.5165112514536094),
      ContactPoint(
          position: Offset(421.38605534762263, 182.97624773873562),
          direction: 2.5016005438590003),
      ContactPoint(
          position: Offset(406.3010295982965, 202.94505388942787),
          direction: 2.488623166916118),
      ContactPoint(
          position: Offset(390.96348659273525, 222.74903525210283),
          direction: 2.4775130876996823),
      ContactPoint(
          position: Offset(375.4108132359861, 242.41280306530578),
          direction: 2.468250761192208),
      ContactPoint(
          position: Offset(359.7577947076646, 261.8703361341546),
          direction: 2.450767285861447),
      ContactPoint(
          position: Offset(343.56819796298964, 280.9284944932507),
          direction: 2.436272646016463),
      ContactPoint(
          position: Offset(327.2320732732484, 300.0699809534555),
          direction: 2.4348229296629746),
      ContactPoint(
          position: Offset(310.8996632828937, 319.1853800675439),
          direction: 2.4315255898220296),
      ContactPoint(
          position: Offset(294.49507467465776, 338.1525692724072),
          direction: 2.4227827190176883),
      ContactPoint(
          position: Offset(277.91747548282706, 356.8819629436859),
          direction: 2.408633149878691),
      ContactPoint(
          position: Offset(261.0711896740415, 375.2810861484202),
          direction: 2.389031122764757),
      ContactPoint(
          position: Offset(243.86519732779564, 393.24959262328),
          direction: 2.363741639606072),
      ContactPoint(
          position: Offset(226.2102259128867, 410.6751433132995),
          direction: 2.3324936732057626),
      ContactPoint(
          position: Offset(208.023952012998, 427.43448698808777),
          direction: 2.2950106384489857),
      ContactPoint(
          position: Offset(189.23140578740572, 443.3890966984241),
          direction: 2.250982167992312),
      ContactPoint(
          position: Offset(169.76929798440466, 458.3862479699277),
          direction: 2.200200032115748),
      ContactPoint(
          position: Offset(149.59147100989264, 472.2604442309644),
          direction: 2.142608962735273),
      ContactPoint(
          position: Offset(128.67407068827566, 484.83794255618545),
          direction: 2.0784199695797305),
      ContactPoint(
          position: Offset(107.02118069469527, 495.9453412955151),
          direction: 2.008292586681211),
      ContactPoint(
          position: Offset(84.67118752793667, 505.42385259575997),
          direction: 1.9333318813934781),
      ContactPoint(
          position: Offset(61.69572996037005, 513.1405466369862),
          direction: 1.855069533638293),
      ContactPoint(
          position: Offset(38.19680240358604, 519.0044380490284),
          direction: 1.7753945446993615),
      ContactPoint(
          position: Offset(14.66622683403702, 522.9344133811389),
          direction: 1.6654149823046378),
      ContactPoint(
          position: Offset(-8.512945671497494, 523.5123195014384),
          direction: 1.508625556342051),
      ContactPoint(
          position: Offset(-31.913954403695833, 519.9824774686662),
          direction: 1.3826963215355654),
      ContactPoint(
          position: Offset(-55.50636570464217, 514.5091818744485),
          direction: 1.3029690919157453),
      ContactPoint(
          position: Offset(-78.5994643292757, 507.1700250245181),
          direction: 1.2242557984297378),
      ContactPoint(
          position: Offset(-101.08596755312168, 498.04691646879985),
          direction: 1.1484664635683455),
      ContactPoint(
          position: Offset(-122.88712401755959, 487.26408568440223),
          direction: 1.077225834017299),
      ContactPoint(
          position: Offset(-143.95832481002674, 474.9769405613784),
          direction: 1.0117514523476503),
      ContactPoint(
          position: Offset(-164.28835297342974, 461.3569451558905),
          direction: 0.9527668567085881),
      ContactPoint(
          position: Offset(-183.89543093956163, 446.57856940118586),
          direction: 0.9005679137467455),
      ContactPoint(
          position: Offset(-202.82189381515175, 430.80919102046164),
          direction: 0.8551514313614828),
      ContactPoint(
          position: Offset(-221.1279038165005, 414.2045387259422),
          direction: 0.8163370017392166),
      ContactPoint(
          position: Offset(-238.88623466971373, 396.9064302413053),
          direction: 0.7838183532167413),
      ContactPoint(
          position: Offset(-256.177979384566, 379.0405204259176),
          direction: 0.7573273826234486),
      ContactPoint(
          position: Offset(-273.09169652852944, 360.72225552338836),
          direction: 0.7365764837736251),
      ContactPoint(
          position: Offset(-289.71705589361954, 342.0538512356027),
          direction: 0.721275312516676),
      ContactPoint(
          position: Offset(-306.1483665752098, 323.12785556116705),
          direction: 0.7114058157184484),
      ContactPoint(
          position: Offset(-322.48757795781603, 304.0352287385227),
          direction: 0.7070264537300854),
      ContactPoint(
          position: Offset(-338.8362776925085, 284.8680842946403),
          direction: 0.7078863776997677),
      ContactPoint(
          position: Offset(-355.136886415447, 265.8889908664288),
          direction: 0.6942510766119749),
      ContactPoint(
          position: Offset(-370.8041559443324, 246.47034087121963),
          direction: 0.674991032332164),
      ContactPoint(
          position: Offset(-386.39657034431036, 226.83160214865998),
          direction: 0.6661462958670477),
      ContactPoint(
          position: Offset(-401.7818059569414, 207.05896611237688),
          direction: 0.6554125774500781),
      ContactPoint(
          position: Offset(-416.92190452959477, 187.12583988154972),
          direction: 0.6428364958714328),
      ContactPoint(
          position: Offset(-431.7782211245093, 167.00883560351184),
          direction: 0.6283528239675373),
      ContactPoint(
          position: Offset(-446.3076673966887, 146.68334073667253),
          direction: 0.6119145368534573),
      ContactPoint(
          position: Offset(-460.4679320343947, 126.12776803679643),
          direction: 0.5935030560661776),
      ContactPoint(
          position: Offset(-474.21268201698797, 105.32143111356284),
          direction: 0.5730611346276051),
      ContactPoint(
          position: Offset(-487.4944809774481, 84.24634585580829),
          direction: 0.5505273637038721),
      ContactPoint(
          position: Offset(-500.26159325727303, 62.88599495835639),
          direction: 0.5258194063185577),
      ContactPoint(
          position: Offset(-512.4602867194905, 41.22657367078921),
          direction: 0.4989044681757111),
      ContactPoint(
          position: Offset(-524.0345092753448, 19.258023286168665),
          direction: 0.4697203663226013),
      ContactPoint(
          position: Offset(-534.9246240460169, -3.0262999268904682),
          direction: 0.43820485134142384),
      ContactPoint(
          position: Offset(-545.0690948334633, -25.62899907928985),
          direction: 0.4043693840108773),
      ContactPoint(
          position: Offset(-554.4064315722466, -48.54707245978298),
          direction: 0.36824120803355687),
      ContactPoint(
          position: Offset(-562.8738295597435, -71.77142111372203),
          direction: 0.3298401211485853),
      ContactPoint(
          position: Offset(-570.4088244034021, -95.28718833142769),
          direction: 0.2892625406188136),
      ContactPoint(
          position: Offset(-576.9523090318983, -119.07312675343876),
          direction: 0.2467113366980067),
      ContactPoint(
          position: Offset(-582.4510282061538, -143.09991365710215),
          direction: 0.2023690546576189),
      ContactPoint(
          position: Offset(-586.8274136288339, -167.14911853336162),
          direction: 0.14104338278341366),
      ContactPoint(
          position: Offset(-589.3049122083052, -191.28820915430475),
          direction: 0.06546763790252541),
      ContactPoint(
          position: Offset(-590.0001457735119, -215.61173851044705),
          direction: 6.27825624697374),
      ContactPoint(
          position: Offset(-589.0718357204737, -239.83889352158494),
          direction: 6.200824034804838),
      ContactPoint(
          position: Offset(-586.0330799362875, -263.78060537622423),
          direction: 6.114094694798163),
      ContactPoint(
          position: Offset(-580.9499594192857, -287.3997836769811),
          direction: 6.0295199406091555),
      ContactPoint(
          position: Offset(-573.9082669295577, -310.5402160266857),
          direction: 5.947255719167305),
      ContactPoint(
          position: Offset(-565.004961296375, -333.05942070823716),
          direction: 5.867234207061435),
      ContactPoint(
          position: Offset(-554.3428828284552, -354.828625214648),
          direction: 5.789231018648642),
      ContactPoint(
          position: Offset(-542.0261545680695, -375.7297722849992),
          direction: 5.712895697456137),
      ContactPoint(
          position: Offset(-528.1575397619501, -395.65329448772184),
          direction: 5.637793799278574),
      ContactPoint(
          position: Offset(-512.8369213601974, -414.4947639298471),
          direction: 5.563427237854221),
      ContactPoint(
          position: Offset(-496.16123213561843, -432.1517927001149),
          direction: 5.489285181013292),
      ContactPoint(
          position: Offset(-478.2259360719425, -448.5225424955345),
          direction: 5.414848152010561),
      ContactPoint(
          position: Offset(-459.12649055665844, -463.50269721082634),
          direction: 5.339593884690613),
      ContactPoint(
          position: Offset(-438.9607827201443, -476.9850519120168),
          direction: 5.263040433013126),
      ContactPoint(
          position: Offset(-417.8322573166337, -488.85931195044765),
          direction: 5.184763514194579),
      ContactPoint(
          position: Offset(-395.8528880380802, -499.01351648452544),
          direction: 5.104430446797657),
      ContactPoint(
          position: Offset(-373.1461943411871, -507.3368548469776),
          direction: 5.021837098633844),
      ContactPoint(
          position: Offset(-349.84966481483406, -513.7240380085071),
          direction: 4.936954470465051),
      ContactPoint(
          position: Offset(-326.0802238488447, -518.086655966996),
          direction: 4.852958552165278),
      ContactPoint(
          position: Offset(-301.7502344356417, -520.509600421245),
          direction: 4.792578623669456),
      ContactPoint(
          position: Offset(-277.58356585110477, -522.0000030769532),
          direction: 4.713105098790521),
    ],
    holes: [],
    isRing: true);
