// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final oval50 = GearDefinition(
    id: 'oval50',
    image: 'images/gears/oval_50.png',
    thumbnailImage: 'images/gears/oval_50_thumb.png',
    size: Size(448, 316),
    center: Offset(224, 158),
    toothCount: 42,
    entitlement: Entitlement.ovalgears,
    package: Package.ovalgears,
    points: [
      ContactPoint(
          position: Offset(211.99999999999773, -0.9267281916774124),
          direction: 6.136549579593975e-7),
      ContactPoint(
          position: Offset(208.08981036032168, -29.006087361049563),
          direction: 0.2711344733956693),
      ContactPoint(
          position: Offset(197.09497061979468, -54.83157891048758),
          direction: 0.5173343204134424),
      ContactPoint(
          position: Offset(180.81957763397813, -77.14529848550544),
          direction: 0.7240792292657332),
      ContactPoint(
          position: Offset(161.01285637089063, -95.7619216804321),
          direction: 0.8930353193188498),
      ContactPoint(
          position: Offset(138.88917276380857, -110.96654582355144),
          direction: 1.032983338676674),
      ContactPoint(
          position: Offset(115.21836519334279, -123.11346283800766),
          direction: 1.1525017322482434),
      ContactPoint(
          position: Offset(90.49872071536578, -132.49810965256768),
          direction: 1.2580335019547597),
      ContactPoint(
          position: Offset(65.07426373673638, -139.3409394981974),
          direction: 1.3540679515335334),
      ContactPoint(
          position: Offset(39.202381964847966, -143.80020261995674),
          direction: 1.443673636599467),
      ContactPoint(
          position: Offset(13.0913190243341, -145.9895140028425),
          direction: 1.5289881842824986),
      ContactPoint(
          position: Offset(-13.091493527629916, -145.98950737648298),
          direction: 1.6126050245104668),
      ContactPoint(
          position: Offset(-39.20258544188283, -143.80017907829816),
          direction: 1.6979194465210679),
      ContactPoint(
          position: Offset(-65.07443831998498, -139.34090988150018),
          direction: 1.787525276884459),
      ContactPoint(
          position: Offset(-90.49889103882289, -132.4980630752685),
          direction: 1.8835593685566536),
      ContactPoint(
          position: Offset(-115.21849816530192, -123.11343319637533),
          direction: 1.989091915528073),
      ContactPoint(
          position: Offset(-138.8891619201588, -110.96652411660688),
          direction: 2.108609743319059),
      ContactPoint(
          position: Offset(-161.01283338806365, -95.76195915958822),
          direction: 2.2485569160587877),
      ContactPoint(
          position: Offset(-180.81961714664732, -77.14525995293187),
          direction: 2.4175143159371615),
      ContactPoint(
          position: Offset(-197.0949812301361, -54.8315133871269),
          direction: 2.6242580319985453),
      ContactPoint(
          position: Offset(-208.08986862062935, -29.006042132362957),
          direction: 2.870458132823517),
      ContactPoint(
          position: Offset(-211.9999999999898, -0.9266899208610383),
          direction: 3.141593957603778),
      ContactPoint(
          position: Offset(-208.0898015505747, 27.15270764575669),
          direction: 3.4127278651681685),
      ContactPoint(
          position: Offset(-197.0949282463051, 52.97815994124715),
          direction: 3.658927686163395),
      ContactPoint(
          position: Offset(-180.81954309180782, 75.29188758480188),
          direction: 3.865671909259555),
      ContactPoint(
          position: Offset(-161.01279729398266, 93.90851510744533),
          direction: 4.034628579594611),
      ContactPoint(
          position: Offset(-138.88911503563207, 109.11311671827691),
          direction: 4.174574931097553),
      ContactPoint(
          position: Offset(-115.21834572794971, 121.26009404743962),
          direction: 4.294094073693294),
      ContactPoint(
          position: Offset(-90.49871567673961, 130.64467534834995),
          direction: 4.3996265968384805),
      ContactPoint(
          position: Offset(-65.07415933139349, 137.4875755140463),
          direction: 4.495660399805101),
      ContactPoint(
          position: Offset(-39.202259321468745, 141.9468028037128),
          direction: 4.58526762024295),
      ContactPoint(
          position: Offset(-13.091149243867775, 144.13608441109918),
          direction: 4.6705873625505445),
      ContactPoint(
          position: Offset(13.091615719247628, 144.1357737645169),
          direction: 4.754201506251854),
      ContactPoint(
          position: Offset(39.20267700176271, 141.9465481840041),
          direction: 4.839517228352162),
      ContactPoint(
          position: Offset(65.07438197049325, 137.48693601947272),
          direction: 4.92911702827463),
      ContactPoint(
          position: Offset(90.49878830637607, 130.64452796752815),
          direction: 5.025141688231126),
      ContactPoint(
          position: Offset(115.21853313427769, 121.25998023971233),
          direction: 5.130682191987303),
      ContactPoint(
          position: Offset(138.88934539073077, 109.11300447735786),
          direction: 5.250203912913593),
      ContactPoint(
          position: Offset(161.01296224969468, 93.90836168127124),
          direction: 5.390151520431501),
      ContactPoint(
          position: Offset(180.81967079112118, 75.29171768646404),
          direction: 5.559106279742752),
      ContactPoint(
          position: Offset(197.09506623476213, 52.97800804563084),
          direction: 5.765851671245624),
      ContactPoint(
          position: Offset(208.08984446139294, 27.152533632061267),
          direction: 6.012051948785997),
    ],
    holes: [
      GearHole(
          name: '0', angle: 1.5707963267948966, distance: 0.23167893538872875),
      GearHole(
          name: '8', angle: 1.5707963267948966, distance: 8.231678935388729),
      GearHole(
          name: '9', angle: 2.338319382801964, distance: 9.165285950912224),
      GearHole(
          name: '10', angle: 3.1184289038487445, distance: 10.002683396424324),
      GearHole(
          name: '11', angle: -2.371311375812409, distance: 10.83741651460951),
      GearHole(
          name: '12', angle: -1.5707963267948966, distance: 11.768321064611271),
      GearHole(
          name: '13', angle: -0.772636354594643, distance: 12.83722359881782),
      GearHole(
          name: '14',
          angle: 0.016546985016361232,
          distance: 14.001916837672722),
      GearHole(
          name: '15', angle: 0.796201203421734, distance: 15.164706641318398),
      GearHole(
          name: '16', angle: 1.5707963267948966, distance: 16.23167893538873),
      GearHole(
          name: '17', angle: 2.346650183901936, distance: 17.16460353466785),
      GearHole(
          name: '18', angle: 3.1287223123096726, distance: 18.00149091406328),
      GearHole(
          name: '19', angle: -2.3648914569391497, distance: 18.836890634358625),
      GearHole(
          name: '20', angle: -1.570796326794897, distance: 19.76832106461127),
      GearHole(
          name: '21', angle: -0.7775359552346621, distance: 20.83682225738133),
      GearHole(
          name: '22', angle: 0.010530471437986319, distance: 22.00121985547853),
      GearHole(
          name: '23', angle: 0.7924703562689618, distance: 23.164401038179026),
      GearHole(
          name: '24', angle: 1.5707963267948966, distance: 24.23167893538873),
      GearHole(
          name: '25', angle: 2.349684372867058, distance: 25.164354997549122),
      GearHole(
          name: '26', angle: 3.132682161134855, distance: 26.001032193532296),
      GearHole(
          name: '27', angle: -2.3622989254001436, distance: 26.83667827489916),
      GearHole(
          name: '28', angle: -1.570796326794897, distance: 27.76832106461127),
      GearHole(
          name: '29', angle: -0.7797171059976329, distance: 28.836643595352058),
      GearHole(
          name: '30', angle: 0.007722477661700532, distance: 30.00089457214739),
      GearHole(
          name: '31', angle: 0.7906549075355949, distance: 31.1642523317652),
      GearHole(
          name: '33', angle: 2.3512547575205978, distance: 33.164226364910405),
      GearHole(
          name: '34', angle: 3.1347786727152616, distance: 34.000789330971465),
      GearHole(
          name: '38',
          angle: 0.006096738549014131,
          distance: 38.000706245135795),
      GearHole(
          name: '42', angle: 3.1360765444092356, distance: 42.00063898477144),
      GearHole(
          name: '46', angle: 0.005036456010246477, distance: 46.00058342161655),
    ],
    isRing: false);
