// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final oval45 = GearDefinition(
    id: 'oval45',
    image: 'images/gears/oval_45.png',
    thumbnailImage: 'images/gears/oval_45_thumb.png',
    size: Size(408, 288),
    center: Offset(204, 144),
    toothCount: 38,
    entitlement: Entitlement.ovalgears,
    package: Package.ovalgears,
    points: [
      ContactPoint(
          position: Offset(191.99999983235963, -0.2860035570570367),
          direction: 6.2831846885505),
      ContactPoint(
          position: Offset(187.66626631969416, -28.46963184325698),
          direction: 0.297549505187531),
      ContactPoint(
          position: Offset(175.6615636825778, -53.93366957091539),
          direction: 0.5627332563846119),
      ContactPoint(
          position: Offset(158.25324424211158, -75.35866199092172),
          direction: 0.7798418368467868),
      ContactPoint(
          position: Offset(137.4368434564129, -92.72788383622105),
          direction: 0.954044853543488),
      ContactPoint(
          position: Offset(114.48164896550549, -106.46524039506909),
          direction: 1.0973688715048073),
      ContactPoint(
          position: Offset(90.14976822600224, -116.98923820668833),
          direction: 1.220066062336298),
      ContactPoint(
          position: Offset(64.92569857084689, -124.615550164525),
          direction: 1.3292648780889706),
      ContactPoint(
          position: Offset(39.14800166528612, -129.56438136367495),
          direction: 1.4296902485077014),
      ContactPoint(
          position: Offset(13.078250828769368, -131.98713488034485),
          direction: 1.5244868261845568),
      ContactPoint(
          position: Offset(-13.078298115246515, -131.98713324637683),
          direction: 1.6171059254131297),
      ContactPoint(
          position: Offset(-39.14803320670978, -129.5643786432592),
          direction: 1.711902463038907),
      ContactPoint(
          position: Offset(-64.92576321819807, -124.61554268156657),
          direction: 1.8123280567410127),
      ContactPoint(
          position: Offset(-90.14978654284687, -116.98922385910156),
          direction: 1.9215268328603186),
      ContactPoint(
          position: Offset(-114.48166131120853, -106.46523815072958),
          direction: 2.0442241922890734),
      ContactPoint(
          position: Offset(-137.43685720161267, -92.72784651546542),
          direction: 2.1875487802375897),
      ContactPoint(
          position: Offset(-158.25331162895563, -75.35855865380954),
          direction: 2.361751303714123),
      ContactPoint(
          position: Offset(-175.6616266897487, -53.93355232595744),
          direction: 2.57885741839279),
      ContactPoint(
          position: Offset(-187.66642549250486, -28.469558202771704),
          direction: 2.844044247126543),
      ContactPoint(
          position: Offset(-191.99999999991647, -0.2858899133667465),
          direction: 3.1415963846976283),
      ContactPoint(
          position: Offset(-187.6662337201286, 27.89768346481611),
          direction: 3.439143252471421),
      ContactPoint(
          position: Offset(-175.66150297641, 53.361726867762016),
          direction: 3.704326953711152),
      ContactPoint(
          position: Offset(-158.25316779558267, 74.78667494054594),
          direction: 3.9214354524236366),
      ContactPoint(
          position: Offset(-137.43675065288699, 92.15590114652893),
          direction: 4.095637669156459),
      ContactPoint(
          position: Offset(-114.48149129098773, 105.8932975053617),
          direction: 4.238962032757214),
      ContactPoint(
          position: Offset(-90.14960028162385, 116.41726401783428),
          direction: 4.3616594313432415),
      ContactPoint(
          position: Offset(-64.92559148586204, 124.04354981094164),
          direction: 4.470857583923407),
      ContactPoint(
          position: Offset(-39.14792583406525, 128.99238084203088),
          direction: 4.571282891370183),
      ContactPoint(
          position: Offset(-13.078138296821832, 131.41513081826255),
          direction: 4.666083803748572),
      ContactPoint(
          position: Offset(13.07837071493865, 131.41491348021393),
          direction: 4.758700844648792),
      ContactPoint(
          position: Offset(39.148098461833015, 128.99225804493707),
          direction: 4.853495500043044),
      ContactPoint(
          position: Offset(64.92568283092126, 124.0433246565185),
          direction: 4.953919078218334),
      ContactPoint(
          position: Offset(90.14969380218828, 116.4172313550772),
          direction: 5.063115348810442),
      ContactPoint(
          position: Offset(114.48165002152889, 105.89321789287162),
          direction: 5.185816534552178),
      ContactPoint(
          position: Offset(137.43690612267335, 92.15580731276776),
          direction: 5.329140620259958),
      ContactPoint(
          position: Offset(158.25321380580073, 74.78665139162592),
          direction: 5.5033434799639025),
      ContactPoint(
          position: Offset(175.6615634200063, 53.36165565537327),
          direction: 5.720452009780996),
      ContactPoint(
          position: Offset(187.6662359613578, 27.89762462154453),
          direction: 5.985635847255128),
    ],
    holes: [
      GearHole(
          name: '0', angle: 1.570796912919468, distance: 0.07150274515153206),
      GearHole(
          name: '8', angle: 1.5707963319871785, distance: 8.07150274515152),
      GearHole(
          name: '9', angle: 2.350608148595967, distance: 9.050701328816844),
      GearHole(
          name: '10', angle: 3.134442500956861, distance: 10.000255670769349),
      GearHole(
          name: '11', angle: -2.360812054786713, distance: 10.949556686148584),
      GearHole(
          name: '12', angle: -1.5707963303082912, distance: 11.92849725484848),
      GearHole(
          name: '13', angle: -0.7814937636836756, distance: 12.949538597836012),
      GearHole(
          name: '14', angle: 0.00510729454721701, distance: 14.0001825512776),
      GearHole(
          name: '15', angle: 0.7887575012065393, distance: 15.050644970652648),
      GearHole(
          name: '16', angle: 1.570796329402588, distance: 16.07150274515152),
      GearHole(
          name: '17', angle: 2.353229197683973, distance: 17.050635068322833),
      GearHole(
          name: '18', angle: 3.1376202997625784, distance: 18.000142059197945),
      GearHole(
          name: '19', angle: -2.358862642166675, distance: 18.949507404727218),
      GearHole(
          name: '20', angle: -1.5707963288978914, distance: 19.92849725484848),
      GearHole(
          name: '21', angle: -0.7829847361924311, distance: 20.949500905920676),
      GearHole(
          name: '22',
          angle: 0.003250113341851726,
          distance: 22.000116154205767),
      GearHole(
          name: '23', angle: 0.7875916035749687, distance: 23.050615496641328),
      GearHole(
          name: '24', angle: 1.5707963285359394, distance: 24.07150274515152),
      GearHole(
          name: '25', angle: 2.354176172938417, distance: 25.050611128728853),
      GearHole(
          name: '26', angle: 3.138842554944534, distance: 26.000098361772768),
      GearHole(
          name: '27', angle: -2.3580705976873944, distance: 26.949487381774862),
      GearHole(
          name: '29', angle: -0.7836516703698359, distance: 28.94948404579083),
      GearHole(
          name: '30',
          angle: 0.002383420328543808,
          distance: 30.000085168678993),
      GearHole(
          name: '31', angle: 0.7870264773745231, distance: 31.050601210208004),
      GearHole(
          name: '34', angle: 3.139489634776502, distance: 34.00007522774635),
    ]);
