// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final oval62Noholes = GearDefinition(
    id: 'oval62Noholes',
    image: 'images/gears/oval_62_noholes.png',
    thumbnailImage: 'images/gears/oval_62_noholes_thumb.png',
    size: Size(544, 380),
    center: Offset(272, 190),
    toothCount: 52,
    entitlement: Entitlement.ovalgears,
    package: Package.ovalgears,
    points: [
      ContactPoint(
          position: Offset(259.9999999999978, -0.6666644650940874),
          direction: 6.283184697175954),
      ContactPoint(
          position: Offset(256.88675043661976, -28.31672605012692),
          direction: 0.2214572163218369),
      ContactPoint(
          position: Offset(247.91766850166704, -54.48992618523024),
          direction: 0.42918005624288735),
      ContactPoint(
          position: Offset(234.14174689211268, -78.15654083174343),
          direction: 0.6122601818674465),
      ContactPoint(
          position: Offset(216.7787218548215, -98.92463463425736),
          direction: 0.76824415072279),
      ContactPoint(
          position: Offset(196.8382370808547, -116.82109193601102),
          direction: 0.9005376244709424),
      ContactPoint(
          position: Offset(175.04995808489684, -132.0369940387084),
          direction: 1.0141991898930005),
      ContactPoint(
          position: Offset(151.92187540099002, -144.78993538788848),
          direction: 1.1138917583676777),
      ContactPoint(
          position: Offset(127.81221422217637, -155.27202646314984),
          direction: 1.2032973612151938),
      ContactPoint(
          position: Offset(102.9834680907427, -163.6389672492881),
          direction: 1.2851558233943496),
      ContactPoint(
          position: Offset(77.63701971111, -170.0124782531595),
          direction: 1.3615084989540733),
      ContactPoint(
          position: Offset(51.935347703975175, -174.4851474984133),
          direction: 1.4338444878566934),
      ContactPoint(
          position: Offset(26.016681281365305, -177.12902332865113),
          direction: 1.5032512538161704),
      ContactPoint(
          position: Offset(0.000016053305601128984, -177.99999999999997),
          direction: 1.570796260585185),
      ContactPoint(
          position: Offset(-26.01661988863022, -177.12902669070073),
          direction: 1.6383413699072822),
      ContactPoint(
          position: Offset(-51.935332865128615, -174.4851479173763),
          direction: 1.7077482010590748),
      ContactPoint(
          position: Offset(-77.63700547406765, -170.01247326777087),
          direction: 1.7800842416806768),
      ContactPoint(
          position: Offset(-102.98348439473786, -163.63895645192363),
          direction: 1.8564369209741827),
      ContactPoint(
          position: Offset(-127.81220232587148, -155.27201563188783),
          direction: 1.938295592630034),
      ContactPoint(
          position: Offset(-151.92189470935662, -144.7899066942368),
          direction: 2.0277012712599998),
      ContactPoint(
          position: Offset(-175.04995504127683, -132.0369577855339),
          direction: 2.127393164971558),
      ContactPoint(
          position: Offset(-196.83821621540508, -116.82110703347588),
          direction: 2.2410540272662),
      ContactPoint(
          position: Offset(-216.77868709828425, -98.92468847909203),
          direction: 2.3733484519870274),
      ContactPoint(
          position: Offset(-234.14172977987286, -78.15655872969056),
          direction: 2.529332202974802),
      ContactPoint(
          position: Offset(-247.91766607455048, -54.48997037733719),
          direction: 2.7124092465597855),
      ContactPoint(
          position: Offset(-256.886878990241, -28.31682842157825),
          direction: 2.9201358165362867),
      ContactPoint(
          position: Offset(-259.99999999992957, -0.6666154083539675),
          direction: 3.1415960800893474),
      ContactPoint(
          position: Offset(-256.88670712632467, 26.983395257078353),
          direction: 3.3630496579380464),
      ContactPoint(
          position: Offset(-247.91767744795226, 53.156613716390346),
          direction: 3.570772064145528),
      ContactPoint(
          position: Offset(-234.1417280606408, 76.8232328662449),
          direction: 3.7538533534907352),
      ContactPoint(
          position: Offset(-216.7787333603008, 97.59127574166237),
          direction: 3.909836796950632),
      ContactPoint(
          position: Offset(-196.8382356571311, 115.48776475307514),
          direction: 4.042130429457359),
      ContactPoint(
          position: Offset(-175.04993743793239, 130.70365000635996),
          direction: 4.155792372321426),
      ContactPoint(
          position: Offset(-151.92182572940885, 143.45660511249054),
          direction: 4.255485482115487),
      ContactPoint(
          position: Offset(-127.81207854939589, 153.93867756304365),
          direction: 4.344890548174774),
      ContactPoint(
          position: Offset(-102.98331551159133, 162.30564656462985),
          direction: 4.426748476225117),
      ContactPoint(
          position: Offset(-77.63699544763973, 168.679096638061),
          direction: 4.503100619741979),
      ContactPoint(
          position: Offset(-51.93530409032239, 173.1518312866395),
          direction: 4.57543695951683),
      ContactPoint(
          position: Offset(-26.016551197819208, 175.79566545889563),
          direction: 4.644844576701611),
      ContactPoint(
          position: Offset(0.00015839106835132072, 176.66665646187766),
          direction: 4.712392007114344),
      ContactPoint(
          position: Offset(26.01682327982982, 175.79550685164918),
          direction: 4.779940815727542),
      ContactPoint(
          position: Offset(51.9353995906978, 173.1514666345391),
          direction: 4.849340049747736),
      ContactPoint(
          position: Offset(77.63709173731597, 168.67900407920587),
          direction: 4.921677744578453),
      ContactPoint(
          position: Offset(102.9834569901147, 162.3052530986098),
          direction: 4.998028519668343),
      ContactPoint(
          position: Offset(127.81217242687649, 153.9386420676936),
          direction: 5.07988148874253),
      ContactPoint(
          position: Offset(151.92201247314728, 143.45651552178452),
          direction: 5.169292108044102),
      ContactPoint(
          position: Offset(175.04989562246118, 130.70370857697253),
          direction: 5.268985977201952),
      ContactPoint(
          position: Offset(196.8381468225077, 115.48782363365187),
          direction: 5.3826478203518615),
      ContactPoint(
          position: Offset(216.778721609272, 97.59129131810371),
          direction: 5.514941127009055),
      ContactPoint(
          position: Offset(234.1417145677363, 76.82321509298596),
          direction: 5.6709248633291365),
      ContactPoint(
          position: Offset(247.91766723656423, 53.156608267610096),
          direction: 5.854004997587078),
      ContactPoint(
          position: Offset(256.88672018379305, 26.983427080329598),
          direction: 6.0617281913015075),
    ],
    holes: [],
    isRing: false,
    smallestConvexDiff: 0.06754500676901465,
    biggestConvexDiff: 0.2214602635530607,
    smallestConcaveDiff: 6.283185307179586,
    biggestConcaveDiff: 0);
