// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';

final oval30 = GearDefinition(
    image: 'images/oval_30.png',
    size: Size(288, 288),
    toothCount: 25,
    points: [
      ContactPoint(
          position: Offset(131.99999999999943, 0.000003735296938697562),
          direction: 6.283184995904842),
      ContactPoint(
          position: Offset(125.16405988436989, -29.52708261073662),
          direction: 0.43132776099808634),
      ContactPoint(
          position: Offset(107.8837350932152, -53.31830321021351),
          direction: 0.7783636107967569),
      ContactPoint(
          position: Offset(85.28060291236778, -70.44735541353504),
          direction: 1.0320876961948917),
      ContactPoint(
          position: Offset(60.14441693440208, -82.03532425782682),
          direction: 1.2264329061738977),
      ContactPoint(
          position: Offset(33.74005526719446, -89.0046956435243),
          direction: 1.388897811283483),
      ContactPoint(
          position: Offset(6.772534934010317, -91.88236856383782),
          direction: 1.5352309561966333),
      ContactPoint(
          position: Offset(-20.29359322936872, -90.93290472359612),
          direction: 1.6782882977592903),
      ContactPoint(
          position: Offset(-47.049412140361454, -86.05715841662816),
          direction: 1.831123842968399),
      ContactPoint(
          position: Offset(-72.9298254503551, -76.86532051756649),
          direction: 2.0069711791546787),
      ContactPoint(
          position: Offset(-97.01986048402705, -62.65106536163352),
          direction: 2.2266710774718),
      ContactPoint(
          position: Offset(-117.46511193994894, -42.29525417551067),
          direction: 2.5237827152588115),
      ContactPoint(
          position: Offset(-130.22922421177523, -15.227146250804),
          direction: 2.919110457430296),
      ContactPoint(
          position: Offset(-130.22913942451987, 15.226997733871375),
          direction: 3.3640745457194243),
      ContactPoint(
          position: Offset(-117.46523704372412, 42.295080368136624),
          direction: 3.759398862722815),
      ContactPoint(
          position: Offset(-97.01998175405579, 62.65095886813432),
          direction: 4.056512709387656),
      ContactPoint(
          position: Offset(-72.92993916692107, 76.86527165189956),
          direction: 4.276213142436687),
      ContactPoint(
          position: Offset(-47.049509264586334, 86.0571235539351),
          direction: 4.452060983730847),
      ContactPoint(
          position: Offset(-20.29364461000598, 90.93289458570224),
          direction: 4.604899737054871),
      ContactPoint(
          position: Offset(6.772481581709513, 91.88219610526549),
          direction: 4.747956900181721),
      ContactPoint(
          position: Offset(33.73993593040679, 89.00455375852499),
          direction: 4.894287727511021),
      ContactPoint(
          position: Offset(60.14420750101135, 82.03517132629737),
          direction: 5.0567487192976746),
      ContactPoint(
          position: Offset(85.28049801662999, 70.44741596008313),
          direction: 5.251093352872579),
      ContactPoint(
          position: Offset(107.8837013426848, 53.318306488972254),
          direction: 5.504821312667085),
      ContactPoint(
          position: Offset(125.16404181124837, 29.527103984590493),
          direction: 5.851856985214547),
    ]);
