// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final oval42 = GearDefinition(
    id: 'oval42',
    image: 'images/gears/oval_42.png',
    thumbnailImage: 'images/gears/oval_42_thumb.png',
    size: Size(384, 272),
    center: Offset(192, 136),
    toothCount: 35,
    entitlement: Entitlement.ovalgears,
    package: Package.ovalgears,
    points: [
      ContactPoint(
          position: Offset(178.94274318218007, -0.07854380492781549),
          direction: 6.283184695018704),
      ContactPoint(
          position: Offset(174.15472500585298, -28.78884717469504),
          direction: 0.32082629312278144),
      ContactPoint(
          position: Offset(161.07498236035974, -54.295599805694835),
          direction: 0.60192030113482),
      ContactPoint(
          position: Offset(142.44678462531348, -75.24258440307882),
          direction: 0.8270823161741179),
      ContactPoint(
          position: Offset(120.48922859272602, -91.7847212065309),
          direction: 1.0052928874217297),
      ContactPoint(
          position: Offset(96.51710555565916, -104.46498265868311),
          direction: 1.1514987212232892),
      ContactPoint(
          position: Offset(71.29166470743057, -113.74998789530878),
          direction: 1.2772554847189213),
      ContactPoint(
          position: Offset(45.29572224547048, -119.96701905546138),
          direction: 1.3901510342154726),
      ContactPoint(
          position: Offset(18.87483748655353, -123.33385087293442),
          direction: 1.4950125798811413),
      ContactPoint(
          position: Offset(-7.705378451883712, -123.9962055948602),
          direction: 1.5959445710082463),
      ContactPoint(
          position: Offset(-34.23436938146024, -121.99631587092681),
          direction: 1.6982317381092633),
      ContactPoint(
          position: Offset(-60.48066532317157, -117.2263419608383),
          direction: 1.806633637933321),
      ContactPoint(
          position: Offset(-86.14090015108859, -109.50847665322948),
          direction: 1.9252118505799363),
      ContactPoint(
          position: Offset(-110.81291177259688, -98.57512757637964),
          direction: 2.0600238105743944),
      ContactPoint(
          position: Offset(-133.89902576738655, -84.03088508805402),
          direction: 2.22050919092674),
      ContactPoint(
          position: Offset(-154.40606763119865, -65.34903866631578),
          direction: 2.420301484764601),
      ContactPoint(
          position: Offset(-170.5990830717872, -42.07783653025325),
          direction: 2.6734844730026763),
      ContactPoint(
          position: Offset(-179.8403558803056, -14.66462660671949),
          direction: 2.9782936657919405),
      ContactPoint(
          position: Offset(-179.84017728525973, 14.507695362623197),
          direction: 3.3048951343506783),
      ContactPoint(
          position: Offset(-170.59911439939935, 41.92069473231484),
          direction: 3.6096985709185416),
      ContactPoint(
          position: Offset(-154.40610335939388, 65.19190971994583),
          direction: 3.8628834055596437),
      ContactPoint(
          position: Offset(-133.89911589367068, 83.8737208531793),
          direction: 4.062675467075755),
      ContactPoint(
          position: Offset(-110.81302016405678, 98.4179879467176),
          direction: 4.223160627173036),
      ContactPoint(
          position: Offset(-86.14099670421757, 109.3513610570712),
          direction: 4.357973012285727),
      ContactPoint(
          position: Offset(-60.48072898269987, 117.0692437228962),
          direction: 4.476552098205453),
      ContactPoint(
          position: Offset(-34.23443282167807, 121.83918679658751),
          direction: 4.5849533670100335),
      ContactPoint(
          position: Offset(-7.705378963698149, 123.83911897892106),
          direction: 4.6872457813781345),
      ContactPoint(
          position: Offset(18.874798516748207, 123.1764615160657),
          direction: 4.788177121823157),
      ContactPoint(
          position: Offset(45.29561189339035, 119.80971164514432),
          direction: 4.89303397303731),
      ContactPoint(
          position: Offset(71.29144636868435, 113.59264717849295),
          direction: 5.005925426767032),
      ContactPoint(
          position: Offset(96.51700980115069, 104.30791324950997),
          direction: 5.1316806339618655),
      ContactPoint(
          position: Offset(120.48916745799492, 91.62764757823805),
          direction: 5.277892409929931),
      ContactPoint(
          position: Offset(142.4468096286884, 75.08545284172713),
          direction: 5.4561023666273405),
      ContactPoint(
          position: Offset(161.0749830296969, 54.138511788419805),
          direction: 5.681265104553257),
      ContactPoint(
          position: Offset(174.15469485266024, 28.631789552811888),
          direction: 5.9623591103478315),
    ],
    holes: [
      GearHole(
          name: '0', angle: 3.0674317774701616, distance: 0.2650427161472235),
      GearHole(
          name: '8', angle: 1.6037427727106086, distance: 8.023992288432007),
      GearHole(
          name: '9', angle: 2.374996361711401, distance: 9.202410905131185),
      GearHole(
          name: '10', angle: 3.139679446008366, distance: 10.264332990042321),
      GearHole(
          name: '11', angle: -2.374163034698311, distance: 11.174816303536808),
      GearHole(
          name: '12', angle: -1.5928550365226142, distance: 11.983277545656376),
      GearHole(
          name: '13', angle: -0.7989147586415041, distance: 12.800384907585197),
      GearHole(
          name: '14',
          angle: 0.0014296901244635046,
          distance: 13.735699833523551),
      GearHole(
          name: '15', angle: 0.7989391544600788, distance: 14.828347077040922),
      GearHole(
          name: '16', angle: 1.5872942168933832, distance: 16.021818150517436),
      GearHole(
          name: '17', angle: 2.366252550067977, distance: 17.201654470834587),
      GearHole(
          name: '18', angle: 3.140517454163889, distance: 18.264324761724477),
      GearHole(
          name: '19', angle: -2.3666663469937195, distance: 19.174063655713738),
      GearHole(
          name: '20', angle: -1.58402425455065, distance: 19.98211040237739),
      GearHole(
          name: '21', angle: -0.7937161868458007, distance: 20.79993518536124),
      GearHole(
          name: '22',
          angle: 0.000903481148743805,
          distance: 21.735694666731682),
      GearHole(
          name: '23', angle: 0.7941938575307768, distance: 22.8278706712128),
      GearHole(
          name: '26', angle: 3.1408449552527182, distance: 26.264321546025375),
      GearHole(
          name: '27', angle: -2.363583465786835, distance: 27.173754152286968),
      GearHole(
          name: '30',
          angle: 0.0006604113654769915,
          distance: 29.735692280054913),
      GearHole(
          name: '34', angle: 3.141019527116365, distance: 34.264319831922585),
    ]);
