// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final pentagon80 = GearDefinition(
    id: 'pentagon80',
    image: 'images/gears/pentagon_80.png',
    thumbnailImage: 'images/gears/pentagon_80_thumb.png',
    size: Size(664, 664),
    toothCount: 77,
    entitlement: Entitlement.pentagongears,
    package: Package.pentagongears,
    points: [
      ContactPoint(
          position: Offset(321.10831069945345, 0.21139697900550597),
          direction: 6.283184051615081),
      ContactPoint(
          position: Offset(314.3945890723457, -27.386855758553114),
          direction: 0.27792756553275044),
      ContactPoint(
          position: Offset(306.6930512205989, -51.93178303796756),
          direction: 0.3302213144633077),
      ContactPoint(
          position: Offset(297.71748775339165, -76.0404033490264),
          direction: 0.38254434906236856),
      ContactPoint(
          position: Offset(287.4941990097136, -99.64671288436195),
          direction: 0.434849240499978),
      ContactPoint(
          position: Offset(276.0503564474164, -122.68619187019368),
          direction: 0.4871632924829017),
      ContactPoint(
          position: Offset(263.4176825558242, -145.09558446158397),
          direction: 0.5394520814744386),
      ContactPoint(
          position: Offset(249.6316608394752, -166.8140889708068),
          direction: 0.5917166491854591),
      ContactPoint(
          position: Offset(234.7298002485954, -187.78302194497365),
          direction: 0.6440003732049266),
      ContactPoint(
          position: Offset(218.75202444705994, -207.9441398839661),
          direction: 0.6962848710271938),
      ContactPoint(
          position: Offset(201.74296440374698, -227.24298575376355),
          direction: 0.7485566529388148),
      ContactPoint(
          position: Offset(183.74834238264157, -245.6268872031793),
          direction: 0.8008563893759355),
      ContactPoint(
          position: Offset(164.81685994125593, -263.0447374562642),
          direction: 0.8531781749337064),
      ContactPoint(
          position: Offset(145.0004189193241, -279.4485120989721),
          direction: 0.9054857866029193),
      ContactPoint(
          position: Offset(124.35370842046903, -294.79412567561695),
          direction: 0.9577973829782493),
      ContactPoint(
          position: Offset(101.52240014369777, -309.79797431873817),
          direction: 1.1436688912929593),
      ContactPoint(
          position: Offset(74.7123670609632, -317.0955039165513),
          direction: 1.425433974878458),
      ContactPoint(
          position: Offset(47.94717469691302, -317.99985815313465),
          direction: 1.5659341060263774),
      ContactPoint(
          position: Offset(22.227919494616597, -317.4525285501189),
          direction: 1.6182477537544244),
      ContactPoint(
          position: Offset(-3.427539333789537, -315.5602192303596),
          direction: 1.6705679268163172),
      ContactPoint(
          position: Offset(-28.94876073689565, -312.3295514441497),
          direction: 1.7228688001455241),
      ContactPoint(
          position: Offset(-54.266268070022534, -307.76889010028304),
          direction: 1.7751764235511125),
      ContactPoint(
          position: Offset(-79.31048989451583, -301.8908799325938),
          direction: 1.827459831769037),
      ContactPoint(
          position: Offset(-104.01310823292216, -294.7127434456791),
          direction: 1.8797195816844798),
      ContactPoint(
          position: Offset(-128.30733381543328, -286.25398072533034),
          direction: 1.9319989443968772),
      ContactPoint(
          position: Offset(-152.12622353141666, -276.53673201606824),
          direction: 1.9842905550601477),
      ContactPoint(
          position: Offset(-175.40469978159012, -265.5880471984939),
          direction: 2.0365726782420115),
      ContactPoint(
          position: Offset(-198.0794053811082, -253.4377155431332),
          direction: 2.088878965768476),
      ContactPoint(
          position: Offset(-220.0876517613936, -240.1179148005964),
          direction: 2.141205208896336),
      ContactPoint(
          position: Offset(-241.3691151755365, -225.66540855932803),
          direction: 2.19351189340093),
      ContactPoint(
          position: Offset(-262.2672399643367, -209.78459267758802),
          direction: 2.2894142866298997),
      ContactPoint(
          position: Offset(-281.81143439436573, -189.7437876089847),
          direction: 2.5698954873873525),
      ContactPoint(
          position: Offset(-292.01675482904494, -163.81785343609934),
          direction: 2.8016559820828864),
      ContactPoint(
          position: Offset(-299.9572106965134, -139.34910487895402),
          direction: 2.853953730786631),
      ContactPoint(
          position: Offset(-306.6075616475179, -114.49841366025542),
          direction: 2.906277549270267),
      ContactPoint(
          position: Offset(-311.94870720481885, -89.33389884917233),
          direction: 2.9585921453023083),
      ContactPoint(
          position: Offset(-315.96727402048015, -63.92488485980001),
          direction: 3.010884818839931),
      ContactPoint(
          position: Offset(-318.65216241022404, -38.340473513503085),
          direction: 3.0631833791643874),
      ContactPoint(
          position: Offset(-319.99589608497274, -12.650965072853714),
          direction: 3.1154631086794913),
      ContactPoint(
          position: Offset(-319.99590390996104, 13.07344675518859),
          direction: 3.167721574626729),
      ContactPoint(
          position: Offset(-318.6521857085377, 38.76298797741818),
          direction: 3.2200014916810327),
      ContactPoint(
          position: Offset(-315.96729951725854, 64.34742972680493),
          direction: 3.272300039980859),
      ContactPoint(
          position: Offset(-311.9487579841775, 89.75638159467772),
          direction: 3.324592617728287),
      ContactPoint(
          position: Offset(-306.60762388979845, 114.92091305051498),
          direction: 3.376907326453032),
      ContactPoint(
          position: Offset(-299.95727041933674, 139.771646621946),
          direction: 3.4292308413250963),
      ContactPoint(
          position: Offset(-292.01687802543427, 164.24027838318602),
          direction: 3.4815290436568),
      ContactPoint(
          position: Offset(-281.8115676965377, 190.1662084824722),
          direction: 3.7132845646487835),
      ContactPoint(
          position: Offset(-262.2676164971927, 210.2071310042154),
          direction: 3.9937656545390037),
      ContactPoint(
          position: Offset(-241.36944218601255, 226.0880379624712),
          direction: 4.089672739158585),
      ContactPoint(
          position: Offset(-220.08804409891596, 240.54049070721695),
          direction: 4.141980533027979),
      ContactPoint(
          position: Offset(-198.0795455188075, 253.8604396196697),
          direction: 4.194306072007523),
      ContactPoint(
          position: Offset(-175.4048799662056, 266.0107590854017),
          direction: 4.246612901362571),
      ContactPoint(
          position: Offset(-152.1263398563568, 276.9594525851847),
          direction: 4.298895274964547),
      ContactPoint(
          position: Offset(-128.3074947771277, 286.6766727218128),
          direction: 4.351185616831245),
      ContactPoint(
          position: Offset(-104.01321412851743, 295.13550756245195),
          direction: 4.40346580561522),
      ContactPoint(
          position: Offset(-79.31055981060176, 302.31359602985697),
          direction: 4.45572733952827),
      ContactPoint(
          position: Offset(-54.2664377146742, 308.1915416704345),
          direction: 4.508007432019145),
      ContactPoint(
          position: Offset(-28.94888040987296, 312.752331939826),
          direction: 4.560314136320239),
      ContactPoint(
          position: Offset(-3.427628628433385, 315.98300426170107),
          direction: 4.6126175694779565),
      ContactPoint(
          position: Offset(22.22782248047376, 317.8753035593261),
          direction: 4.664937097794924),
      ContactPoint(
          position: Offset(47.94706459986672, 318.422665936769),
          direction: 4.717249655775621),
      ContactPoint(
          position: Offset(74.71232636377063, 317.51835792296504),
          direction: 4.857750474957994),
      ContactPoint(
          position: Offset(101.5223618070074, 310.22080982798366),
          direction: 5.1395184941374685),
      ContactPoint(
          position: Offset(124.35368659738837, 295.2168604962493),
          direction: 5.325388810028884),
      ContactPoint(
          position: Offset(145.00041829325295, 279.8712611558923),
          direction: 5.377699454260502),
      ContactPoint(
          position: Offset(164.8169432447871, 263.46739404022344),
          direction: 5.430006219773203),
      ContactPoint(
          position: Offset(183.74845752588783, 246.04959670863008),
          direction: 5.482328113773702),
      ContactPoint(
          position: Offset(201.74296661147275, 227.6657777191045),
          direction: 5.534628924564089),
      ContactPoint(
          position: Offset(218.7520896626975, 208.36688344880622),
          direction: 5.586900979321857),
      ContactPoint(
          position: Offset(234.72974490640178, 188.20583922185975),
          direction: 5.639185724138425),
      ContactPoint(
          position: Offset(249.63165862330408, 167.2368560929226),
          direction: 5.6914683268982085),
      ContactPoint(
          position: Offset(263.4176864071665, 145.5183418530401),
          direction: 5.74373385051853),
      ContactPoint(
          position: Offset(276.0503528083601, 123.10890152888071),
          direction: 5.796021366884567),
      ContactPoint(
          position: Offset(287.494257454385, 100.06943650934562),
          direction: 5.848335554248777),
      ContactPoint(
          position: Offset(297.71749026584735, 76.46316092927907),
          direction: 5.900641519010572),
      ContactPoint(
          position: Offset(306.69305646518825, 52.354562079463605),
          direction: 5.952965340585983),
      ContactPoint(
          position: Offset(314.3945285865694, 27.809587139895513),
          direction: 6.005257908511961),
    ],
    holes: []);
