// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final pentagon64 = GearDefinition(
    id: 'pentagon64',
    image: 'images/gears/pentagon_64.png',
    thumbnailImage: 'images/gears/pentagon_64_thumb.png',
    size: Size(540, 536),
    center: Offset(261.8182716369629, 268.9283323287964),
    toothCount: 62,
    entitlement: Entitlement.pentagongears,
    package: Package.pentagongears,
    points: [
      ContactPoint(
          position: Offset(267.9999999999976, -0.000007595261187986528),
          direction: 6.329384323322529e-7),
      ContactPoint(
          position: Offset(261.1320088940295, -27.54594734572532),
          direction: 0.29057890968785394),
      ContactPoint(
          position: Offset(252.96955905235214, -51.9292632527943),
          direction: 0.35553438030111373),
      ContactPoint(
          position: Offset(243.240211758356, -75.7310940725971),
          direction: 0.42051687019853023),
      ContactPoint(
          position: Offset(231.98660552214542, -98.85083846222619),
          direction: 0.485464854811819),
      ContactPoint(
          position: Offset(219.25636181844538, -121.19150177535577),
          direction: 0.5504076823762265),
      ContactPoint(
          position: Offset(205.1031523412874, -142.65878909770268),
          direction: 0.6153406064255327),
      ContactPoint(
          position: Offset(189.58714953180476, -163.1625059007618),
          direction: 0.6802600913763976),
      ContactPoint(
          position: Offset(172.77367112194892, -182.61653513263667),
          direction: 0.7451825447290457),
      ContactPoint(
          position: Offset(154.73313972903256, -200.9389329908377),
          direction: 0.8101379579023202),
      ContactPoint(
          position: Offset(135.54066812916722, -218.05135708230006),
          direction: 0.8751179733063523),
      ContactPoint(
          position: Offset(115.27779226421487, -233.88130557222902),
          direction: 0.9400799584758612),
      ContactPoint(
          position: Offset(92.62532141786119, -249.12856275522114),
          direction: 1.138472152044951),
      ContactPoint(
          position: Offset(65.8281506423112, -256.3886737040884),
          direction: 1.4331760518540584),
      ContactPoint(
          position: Offset(39.06693949603872, -256.9269111638127),
          direction: 1.5861867623317432),
      ContactPoint(
          position: Offset(13.383066543090065, -255.69635764468933),
          direction: 1.6511508062412297),
      ContactPoint(
          position: Offset(-12.16689021903452, -252.8011528315511),
          direction: 1.7161238259634128),
      ContactPoint(
          position: Offset(-37.4747130855912, -248.25285840493652),
          direction: 1.7810827028853886),
      ContactPoint(
          position: Offset(-62.43368677905241, -242.07214401388194),
          direction: 1.846004946740468),
      ContactPoint(
          position: Offset(-86.93906459183376, -234.28542679529426),
          direction: 1.9109172017028504),
      ContactPoint(
          position: Offset(-110.88790353609899, -224.92549604380932),
          direction: 1.9758470796995296),
      ContactPoint(
          position: Offset(-134.17904627201133, -214.0308105743132),
          direction: 2.0408009039427046),
      ContactPoint(
          position: Offset(-156.7138434187933, -201.6472139171474),
          direction: 2.1057588336090447),
      ContactPoint(
          position: Offset(-178.39747546041153, -187.82683867204932),
          direction: 2.1707324555080874),
      ContactPoint(
          position: Offset(-199.5412797847797, -172.29665966165922),
          direction: 2.279186735031243),
      ContactPoint(
          position: Offset(-219.14159447032887, -152.33793647195228),
          direction: 2.572501479268521),
      ContactPoint(
          position: Offset(-229.12415883021163, -126.34043932320223),
          direction: 2.8168417037152667),
      ContactPoint(
          position: Offset(-236.5333180985684, -101.71770271356488),
          direction: 2.881801868228253),
      ContactPoint(
          position: Offset(-242.32762268898142, -76.66548233168034),
          direction: 2.9467833801752237),
      ContactPoint(
          position: Offset(-246.48325067741152, -51.290328070867716),
          direction: 3.011734352922344),
      ContactPoint(
          position: Offset(-248.98347892298827, -25.699293076240874),
          direction: 3.0766617447919806),
      ContactPoint(
          position: Offset(-249.81827163696246, 0.0001252848438916002),
          direction: 3.141592921467409),
      ContactPoint(
          position: Offset(-248.98346511127258, 25.699529036772482),
          direction: 3.206524153524609),
      ContactPoint(
          position: Offset(-246.48321934751124, 51.290593690517554),
          direction: 3.271451477011702),
      ContactPoint(
          position: Offset(-242.32757176663836, 76.66579425453713),
          direction: 3.336402500101038),
      ContactPoint(
          position: Offset(-236.53324800832232, 101.71801325318054),
          direction: 3.4013839014575398),
      ContactPoint(
          position: Offset(-229.1240997174264, 126.34068908453044),
          direction: 3.4663440976893245),
      ContactPoint(
          position: Offset(-219.14155107673645, 152.3380820028999),
          direction: 3.7106846392769324),
      ContactPoint(
          position: Offset(-199.54124559427203, 172.2967925080878),
          direction: 4.003998975194624),
      ContactPoint(
          position: Offset(-178.3973971151946, 187.8269826231363),
          direction: 4.112453829075898),
      ContactPoint(
          position: Offset(-156.71377855702298, 201.64730773754243),
          direction: 4.177426844242417),
      ContactPoint(
          position: Offset(-134.17898245922945, 214.03092267230153),
          direction: 4.242385375964931),
      ContactPoint(
          position: Offset(-110.88771577369695, 224.92559722264193),
          direction: 4.30733864972483),
      ContactPoint(
          position: Offset(-86.93895566501193, 234.28553435536423),
          direction: 4.372268292463239),
      ContactPoint(
          position: Offset(-62.43360286016179, 242.07219766537753),
          direction: 4.43718102069767),
      ContactPoint(
          position: Offset(-37.47472625602686, 248.252896997651),
          direction: 4.502102782243662),
      ContactPoint(
          position: Offset(-12.166902928263893, 252.80117609288624),
          direction: 4.567061695943014),
      ContactPoint(
          position: Offset(13.383078410197744, 255.69638816422014),
          direction: 4.632035493065238),
      ContactPoint(
          position: Offset(39.06704390730608, 256.92689324190786),
          direction: 4.696999616519168),
      ContactPoint(
          position: Offset(65.82809121758751, 256.38864868551804),
          direction: 4.850009390809205),
      ContactPoint(
          position: Offset(92.62539692058141, 249.12854536574588),
          direction: 5.144711682107156),
      ContactPoint(
          position: Offset(115.27767689309817, 233.88138269638017),
          direction: 5.343106039965271),
      ContactPoint(
          position: Offset(135.5406969054045, 218.0513356480095),
          direction: 5.408067144831922),
      ContactPoint(
          position: Offset(154.73314262062314, 200.93892260950003),
          direction: 5.473047681927474),
      ContactPoint(
          position: Offset(172.77370417346282, 182.61648660986623),
          direction: 5.538003073849281),
      ContactPoint(
          position: Offset(189.5871502177061, 163.1624745354411),
          direction: 5.602925306675814),
      ContactPoint(
          position: Offset(205.10315052009156, 142.6587764152329),
          direction: 5.667844437835401),
      ContactPoint(
          position: Offset(219.25645258998654, 121.19136571924757),
          direction: 5.7327775003385355),
      ContactPoint(
          position: Offset(231.98670057265068, 98.85067924445),
          direction: 5.797721077033143),
      ContactPoint(
          position: Offset(243.24021601020436, 75.73105404714033),
          direction: 5.8626693049207095),
      ContactPoint(
          position: Offset(252.9695867271333, 51.929148838538715),
          direction: 5.927650246311399),
      ContactPoint(
          position: Offset(261.1320390159527, 27.54593341000479),
          direction: 5.992606282411653),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.3561944901923444, distance: 11.000000000000004),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(
          name: '13', angle: -0.7853981633974483, distance: 13.000000000000004),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974483, distance: 15.000000000000002),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(
          name: '17', angle: 2.356194490192345, distance: 16.999999999999996),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: 0, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(name: '25', angle: 2.356194490192345, distance: 25),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(
          name: '29', angle: -0.7853981633974486, distance: 29.000000000000004),
      GearHole(name: '30', angle: -4.736951571734001e-16, distance: 30),
      GearHole(name: '31', angle: 0.785398163397448, distance: 31),
      GearHole(name: '32', angle: 1.5707963267948966, distance: 32),
      GearHole(name: '33', angle: 2.356194490192345, distance: 33),
      GearHole(name: '34', angle: 3.141592653589793, distance: 34),
      GearHole(name: '35', angle: -2.356194490192345, distance: 35),
      GearHole(name: '36', angle: -1.570796326794897, distance: 36),
      GearHole(
          name: '37', angle: -0.7853981633974485, distance: 37.00000000000001),
      GearHole(name: '38', angle: -3.739698609263685e-16, distance: 38),
      GearHole(
          name: '39', angle: 0.7853981633974481, distance: 39.00000000000001),
      GearHole(name: '40', angle: 1.5707963267948966, distance: 40),
      GearHole(name: '41', angle: 2.356194490192345, distance: 41),
      GearHole(name: '42', angle: 3.141592653589793, distance: 42),
      GearHole(
          name: '43', angle: -2.3561944901923453, distance: 42.99999999999999),
      GearHole(name: '44', angle: -1.5707963267948968, distance: 44),
      GearHole(
          name: '45', angle: -0.7853981633974485, distance: 44.99999999999999),
      GearHole(name: '46', angle: -3.089316242435218e-16, distance: 46),
      GearHole(name: '47', angle: 0.785398163397448, distance: 47),
      GearHole(name: '48', angle: 1.5707963267948966, distance: 48),
      GearHole(name: '49', angle: 2.356194490192345, distance: 49),
      GearHole(name: '50', angle: 3.141592653589793, distance: 50),
      GearHole(
          name: '51', angle: -2.356194490192345, distance: 51.00000000000001),
      GearHole(name: '52', angle: -1.5707963267948968, distance: 52),
      GearHole(
          name: '53', angle: -0.7853981633974486, distance: 53.00000000000001),
      GearHole(name: '54', angle: -2.631639762074445e-16, distance: 54),
      GearHole(
          name: '55', angle: 0.7853981633974482, distance: 54.99999999999999),
    ]);
