// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final pentagon60 = GearDefinition(
    id: 'pentagon60',
    image: 'images/gears/pentagon_60.png',
    thumbnailImage: 'images/gears/pentagon_60_thumb.png',
    size: Size(512, 508),
    center: Offset(246.95466995239258, 253.64927768707275),
    toothCount: 58,
    entitlement: Entitlement.pentagongears,
    package: Package.pentagongears,
    points: [
      ContactPoint(
          position: Offset(251.99999999997843, 0.00002275077036921211),
          direction: 6.283183411282056),
      ContactPoint(
          position: Offset(245.04906342257235, -27.634529297919002),
          direction: 0.2950629810497274),
      ContactPoint(
          position: Offset(236.68793333429164, -52.06331716599673),
          direction: 0.3644953096885146),
      ContactPoint(
          position: Offset(226.65152092981864, -75.85317567361206),
          direction: 0.43394737916861903),
      ContactPoint(
          position: Offset(214.9885103868951, -98.88914235018089),
          direction: 0.5033896803330125),
      ContactPoint(
          position: Offset(201.75552225877738, -121.06014883239209),
          direction: 0.5728072544512344),
      ContactPoint(
          position: Offset(187.0171394733986, -142.2599317366426),
          direction: 0.6421994796986512),
      ContactPoint(
          position: Offset(170.84440715853378, -162.3869205181543),
          direction: 0.7115961438521037),
      ContactPoint(
          position: Offset(153.31455526620252, -181.34406936169387),
          direction: 0.7810164378117586),
      ContactPoint(
          position: Offset(134.5115699430982, -199.03953104167735),
          direction: 0.8504630122502315),
      ContactPoint(
          position: Offset(114.52562932013704, -215.38745942707513),
          direction: 0.9199212270561432),
      ContactPoint(
          position: Offset(92.54662647459985, -230.84925323154664),
          direction: 1.077365493934452),
      ContactPoint(
          position: Offset(66.51055801121451, -240.77299069452994),
          direction: 1.3766442800834424),
      ContactPoint(
          position: Offset(39.11278435996415, -241.64882663890276),
          direction: 1.5794666881449615),
      ContactPoint(
          position: Offset(13.316848671105966, -240.52882903384798),
          direction: 1.6489142944668602),
      ContactPoint(
          position: Offset(-12.339107583667944, -237.62131550089526),
          direction: 1.7183595665174751),
      ContactPoint(
          position: Offset(-37.73137379235424, -232.9408458531821),
          direction: 1.7877881934941513),
      ContactPoint(
          position: Offset(-62.73756976550775, -226.5103336226245),
          direction: 1.857201337895816),
      ContactPoint(
          position: Offset(-87.2374790578889, -218.36121957345003),
          direction: 1.926599599825142),
      ContactPoint(
          position: Offset(-111.11344989687535, -208.53293006519107),
          direction: 1.9960026191891638),
      ContactPoint(
          position: Offset(-134.250482403938, -197.07221659757042),
          direction: 2.0654315306579925),
      ContactPoint(
          position: Offset(-156.53678914620141, -184.03351651969032),
          direction: 2.1348848058604286),
      ContactPoint(
          position: Offset(-177.86441268940476, -169.47944397475842),
          direction: 2.2043335558836805),
      ContactPoint(
          position: Offset(-199.63939783348818, -151.9500959712271),
          direction: 2.4531278229808757),
      ContactPoint(
          position: Offset(-212.58026172327726, -127.0348807299263),
          direction: 2.7509833922362743),
      ContactPoint(
          position: Offset(-220.70491202865338, -101.97841235787301),
          direction: 2.863880447980777),
      ContactPoint(
          position: Offset(-226.9172769697672, -76.91662148670154),
          direction: 2.9333342824914572),
      ContactPoint(
          position: Offset(-231.37546287372277, -51.48429049984802),
          direction: 3.0027722967181467),
      ContactPoint(
          position: Offset(-234.05866108349196, -25.804312861448764),
          direction: 3.0721838995785133),
      ContactPoint(
          position: Offset(-234.95466995239215, -0.00007950188193431145),
          direction: 3.1415923862617414),
      ContactPoint(
          position: Offset(-234.05867485779757, 25.80418470851084),
          direction: 3.211000899492195),
      ContactPoint(
          position: Offset(-231.37548302966576, 51.484221717291206),
          direction: 3.2804123585735407),
      ContactPoint(
          position: Offset(-226.91731976577637, 76.91652598578146),
          direction: 3.3498506884064563),
      ContactPoint(
          position: Offset(-220.70494788884594, 101.97835265368616),
          direction: 3.4193049745318946),
      ContactPoint(
          position: Offset(-212.58031538111103, 127.03474387861891),
          direction: 3.5321985201415065),
      ContactPoint(
          position: Offset(-199.6396344366325, 151.95001164193303),
          direction: 3.8300549704456777),
      ContactPoint(
          position: Offset(-177.86448789224684, 169.47949055259147),
          direction: 4.078851864115014),
      ContactPoint(
          position: Offset(-156.53690772826494, 184.03352152914766),
          direction: 4.148300092958979),
      ContactPoint(
          position: Offset(-134.25059596718353, 197.07226284731624),
          direction: 4.21775385962111),
      ContactPoint(
          position: Offset(-111.11353923958796, 208.53294632474783),
          direction: 4.287182890161489),
      ContactPoint(
          position: Offset(-87.2375926821043, 218.36125518869412),
          direction: 4.356585101695819),
      ContactPoint(
          position: Offset(-62.73770212692715, 226.510365603193),
          direction: 4.425984400836256),
      ContactPoint(
          position: Offset(-37.73138909301093, 232.94088735491223),
          direction: 4.495398412213168),
      ContactPoint(
          position: Offset(-12.339163680840723, 237.62129716140805),
          direction: 4.564826156681905),
      ContactPoint(
          position: Offset(13.316926676461414, 240.52886325933827),
          direction: 4.634269880310995),
      ContactPoint(
          position: Offset(39.112817792553926, 241.64887148687012),
          direction: 4.703718861961393),
      ContactPoint(
          position: Offset(66.51061713679749, 240.7730139581907),
          direction: 4.906540864917976),
      ContactPoint(
          position: Offset(92.54660555031164, 230.84931292209293),
          direction: 5.20582072096535),
      ContactPoint(
          position: Offset(114.52556770488802, 215.3874980158384),
          direction: 5.363264019359409),
      ContactPoint(
          position: Offset(134.51152437788946, 199.03961291287612),
          direction: 5.432720626499584),
      ContactPoint(
          position: Offset(153.3145922394134, 181.34413151378394),
          direction: 5.502169633527401),
      ContactPoint(
          position: Offset(170.84429831254218, 162.38701199368882),
          direction: 5.571590850853655),
      ContactPoint(
          position: Offset(187.01707140447758, 142.259986916829),
          direction: 5.640984848870589),
      ContactPoint(
          position: Offset(201.75546639075583, 121.06024763205562),
          direction: 5.710378847193494),
      ContactPoint(
          position: Offset(214.9885149669102, 98.88901196332641),
          direction: 5.7797964180368195),
      ContactPoint(
          position: Offset(226.65149061695578, 75.85314471427301),
          direction: 5.849237968585063),
      ContactPoint(
          position: Offset(236.68790490564115, 52.06325065590096),
          direction: 5.918690485817162),
      ContactPoint(
          position: Offset(245.04896858957486, 27.634601125703245),
          direction: 5.988121386120458),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.3561944901923444, distance: 11.000000000000004),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(
          name: '13', angle: -0.7853981633974483, distance: 13.000000000000004),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974483, distance: 15.000000000000002),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(
          name: '17', angle: 2.356194490192345, distance: 16.999999999999996),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(name: '25', angle: 2.356194490192345, distance: 25),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(
          name: '29', angle: -0.7853981633974486, distance: 29.000000000000004),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
      GearHole(name: '31', angle: 0.785398163397448, distance: 31),
      GearHole(name: '32', angle: 1.5707963267948966, distance: 32),
      GearHole(name: '33', angle: 2.356194490192345, distance: 33),
      GearHole(name: '34', angle: 3.141592653589793, distance: 34),
      GearHole(name: '35', angle: -2.356194490192345, distance: 35),
      GearHole(name: '36', angle: -1.570796326794897, distance: 36),
      GearHole(
          name: '37', angle: -0.7853981633974485, distance: 37.00000000000001),
      GearHole(name: '38', angle: -1.8698493046318425e-16, distance: 38),
      GearHole(
          name: '39', angle: 0.7853981633974481, distance: 39.00000000000001),
      GearHole(name: '40', angle: 1.5707963267948966, distance: 40),
      GearHole(name: '41', angle: 2.356194490192345, distance: 41),
      GearHole(name: '42', angle: 3.141592653589793, distance: 42),
      GearHole(name: '43', angle: -2.3561944901923453, distance: 43),
      GearHole(name: '44', angle: -1.5707963267948968, distance: 44),
      GearHole(
          name: '45', angle: -0.7853981633974485, distance: 44.99999999999999),
      GearHole(name: '46', angle: -3.089316242435218e-16, distance: 46),
      GearHole(name: '47', angle: 0.785398163397448, distance: 47),
      GearHole(name: '48', angle: 1.5707963267948966, distance: 48),
      GearHole(name: '49', angle: 2.356194490192345, distance: 49),
      GearHole(name: '50', angle: 3.141592653589793, distance: 50),
      GearHole(
          name: '51', angle: -2.356194490192345, distance: 51.00000000000001),
    ]);
