// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final pentagon62 = GearDefinition(
    id: 'pentagon62',
    image: 'images/gears/pentagon_62.png',
    thumbnailImage: 'images/gears/pentagon_62_thumb.png',
    size: Size(528, 524),
    center: Offset(254.38648986816406, 261.23310470581055),
    toothCount: 60,
    entitlement: Entitlement.pentagongears,
    package: Package.pentagongears,
    points: [
      ContactPoint(
          position: Offset(259.9999999999976, 0.0000075895855709516814),
          direction: 6.283184674714122),
      ContactPoint(
          position: Offset(253.09209945305346, -27.588917743902467),
          direction: 0.2927523950244826),
      ContactPoint(
          position: Offset(244.83330000260855, -51.99425099472461),
          direction: 0.35987025569468933),
      ContactPoint(
          position: Offset(234.9559372178765, -75.79071056477567),
          direction: 0.42699924561921954),
      ContactPoint(
          position: Offset(223.5046034207856, -98.87110933902675),
          direction: 0.49413164987314406),
      ContactPoint(
          position: Offset(210.53088907054732, -121.13090275566317),
          direction: 0.5612296631174685),
      ContactPoint(
          position: Offset(196.09480238114318, -142.47121386667533),
          direction: 0.6283182799238958),
      ContactPoint(
          position: Offset(180.25995462478255, -162.79528984716066),
          direction: 0.6954081894394815),
      ContactPoint(
          position: Offset(163.09870742618003, -182.01262656886678),
          direction: 0.762505686694233),
      ContactPoint(
          position: Offset(144.68666093528464, -200.0357238157182),
          direction: 0.8296361528587104),
      ContactPoint(
          position: Offset(125.10720823673941, -216.7831788171691),
          direction: 0.896765452419066),
      ContactPoint(
          position: Offset(104.4484559855213, -232.1794662635895),
          direction: 0.963885300791846),
      ContactPoint(
          position: Offset(80.3444983873498, -247.2746433698392),
          direction: 1.2566368028687114),
      ContactPoint(
          position: Offset(51.97126358869111, -249.23035496982538),
          direction: 1.5493882247222048),
      ContactPoint(
          position: Offset(26.208274551158805, -248.91742324357918),
          direction: 1.616507891484547),
      ContactPoint(
          position: Offset(0.5242245665169638, -246.8769832160266),
          direction: 1.6836371371653556),
      ContactPoint(
          position: Offset(-24.965178720784316, -243.11833342304362),
          direction: 1.7507683675644827),
      ContactPoint(
          position: Offset(-50.14459132606983, -237.65829343935485),
          direction: 1.8178663149554781),
      ContactPoint(
          position: Offset(-74.90145331019856, -230.5232539529532),
          direction: 1.8849553130101757),
      ContactPoint(
          position: Offset(-99.12402563678214, -221.74392540242013),
          direction: 1.9520445886040294),
      ContactPoint(
          position: Offset(-122.7039670744522, -211.36109058138717),
          direction: 2.019142471970473),
      ContactPoint(
          position: Offset(-145.5345876879275, -199.41963001145115),
          direction: 2.086273538961806),
      ContactPoint(
          position: Offset(-167.51283004361244, -185.97365296396072),
          direction: 2.1534030165544156),
      ContactPoint(
          position: Offset(-188.53940818626089, -171.08374542542415),
          direction: 2.220521942481893),
      ContactPoint(
          position: Offset(-210.34435783409398, -152.82420874580757),
          direction: 2.5132730024798655),
      ContactPoint(
          position: Offset(-220.97214918090734, -126.44400289205623),
          direction: 2.8060256533200993),
      ContactPoint(
          position: Offset(-228.63575073819035, -101.84519191496257),
          direction: 2.8731447385396827),
      ContactPoint(
          position: Offset(-234.63199433549815, -76.78767738476935),
          direction: 2.940273893231981),
      ContactPoint(
          position: Offset(-238.93396057819476, -51.38437947635144),
          direction: 3.007405457770709),
      ContactPoint(
          position: Offset(-241.5220231447282, -25.750039670431757),
          direction: 3.074503356134604),
      ContactPoint(
          position: Offset(-242.38648986816375, -0.00001801136463944048),
          direction: 3.141592424208495),
      ContactPoint(
          position: Offset(-241.52203477753943, 25.75002160290064),
          direction: 3.208681716455404),
      ContactPoint(
          position: Offset(-238.93396841925113, 51.384408426045056),
          direction: 3.275779717566627),
      ContactPoint(
          position: Offset(-234.6320011269629, 76.78774843860043),
          direction: 3.342910968270422),
      ContactPoint(
          position: Offset(-228.63577299738182, 101.84526356182026),
          direction: 3.4100401669972813),
      ContactPoint(
          position: Offset(-220.97220066696482, 126.44398982909408),
          direction: 3.477159174315029),
      ContactPoint(
          position: Offset(-210.34445968550037, 152.8241411651515),
          direction: 3.769910844604892),
      ContactPoint(
          position: Offset(-188.53959357437614, 171.08367685937318),
          direction: 4.062662327330122),
      ContactPoint(
          position: Offset(-167.51294008379548, 185.9736508365948),
          direction: 4.129781968415692),
      ContactPoint(
          position: Offset(-145.53473995115965, 199.41960349251264),
          direction: 4.196911799313279),
      ContactPoint(
          position: Offset(-122.70411667459035, 211.361065605316),
          direction: 4.2640417004708695),
      ContactPoint(
          position: Offset(-99.12429208254007, 221.74390731902517),
          direction: 4.331140085958856),
      ContactPoint(
          position: Offset(-74.90164628273259, 230.52324616808423),
          direction: 4.398230466602156),
      ContactPoint(
          position: Offset(-50.14470368340974, 237.65830157731304),
          direction: 4.465318515599112),
      ContactPoint(
          position: Offset(-24.965255217011812, 243.11837916260745),
          direction: 4.532416922481525),
      ContactPoint(
          position: Offset(0.5241015182006592, 246.87699073459154),
          direction: 4.5995480879922725),
      ContactPoint(
          position: Offset(26.20805818128021, 248.91745745020475),
          direction: 4.666677186553035),
      ContactPoint(
          position: Offset(51.97113425372542, 249.2303741988557),
          direction: 4.733796476930866),
      ContactPoint(
          position: Offset(80.34429726162132, 247.27471312114514),
          direction: 5.026546925342616),
      ContactPoint(
          position: Offset(104.44831333097522, 232.179579737955),
          direction: 5.319297918095809),
      ContactPoint(
          position: Offset(125.10702422988969, 216.783370272088),
          direction: 5.386419758620874),
      ContactPoint(
          position: Offset(144.68651601487232, 200.03584649799546),
          direction: 5.453550020484772),
      ContactPoint(
          position: Offset(163.0985825651403, 182.01270578432857),
          direction: 5.520679283799948),
      ContactPoint(
          position: Offset(180.2598342166038, 162.79540992562696),
          direction: 5.587777333927715),
      ContactPoint(
          position: Offset(196.09471399135958, 142.4712324014263),
          direction: 5.654867475683757),
      ContactPoint(
          position: Offset(210.53082543634918, 121.1309068898927),
          direction: 5.721955237118288),
      ContactPoint(
          position: Offset(223.50450880325025, 98.87117606335902),
          direction: 5.789053118791709),
      ContactPoint(
          position: Offset(234.95590129778532, 75.79072243856785),
          direction: 5.856184974470442),
      ContactPoint(
          position: Offset(244.83332869964065, 51.994179539375814),
          direction: 5.92331462067168),
      ContactPoint(
          position: Offset(253.0920694353557, 27.588977120600333),
          direction: 5.990433056501442),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.3561944901923444, distance: 11.000000000000004),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(
          name: '13', angle: -0.7853981633974483, distance: 13.000000000000004),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974483, distance: 15.000000000000002),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(
          name: '17', angle: 2.356194490192345, distance: 16.999999999999996),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(name: '25', angle: 2.356194490192345, distance: 25),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(
          name: '29', angle: -0.7853981633974486, distance: 29.000000000000004),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
      GearHole(name: '31', angle: 0.785398163397448, distance: 31),
      GearHole(name: '32', angle: 1.5707963267948966, distance: 32),
      GearHole(name: '33', angle: 2.356194490192345, distance: 33),
      GearHole(name: '34', angle: 3.141592653589793, distance: 34),
      GearHole(name: '35', angle: -2.356194490192345, distance: 35),
      GearHole(name: '36', angle: -1.570796326794897, distance: 36),
      GearHole(
          name: '37', angle: -0.7853981633974485, distance: 37.00000000000001),
      GearHole(name: '38', angle: -1.8698493046318425e-16, distance: 38),
      GearHole(
          name: '39', angle: 0.7853981633974481, distance: 39.00000000000001),
      GearHole(name: '40', angle: 1.5707963267948966, distance: 40),
      GearHole(name: '41', angle: 2.356194490192345, distance: 41),
      GearHole(name: '42', angle: 3.141592653589793, distance: 42),
      GearHole(name: '43', angle: -2.3561944901923453, distance: 43),
      GearHole(name: '44', angle: -1.5707963267948968, distance: 44),
      GearHole(
          name: '45', angle: -0.7853981633974485, distance: 44.99999999999999),
      GearHole(name: '46', angle: -3.089316242435218e-16, distance: 46),
      GearHole(name: '47', angle: 0.785398163397448, distance: 47),
      GearHole(name: '48', angle: 1.5707963267948966, distance: 48),
      GearHole(name: '49', angle: 2.356194490192345, distance: 49),
      GearHole(name: '50', angle: 3.141592653589793, distance: 50),
      GearHole(
          name: '51', angle: -2.356194490192345, distance: 51.00000000000001),
      GearHole(name: '52', angle: -1.5707963267948968, distance: 52),
      GearHole(
          name: '53', angle: -0.7853981633974486, distance: 53.00000000000001),
      GearHole(name: '54', angle: -2.631639762074445e-16, distance: 54),
    ],
    isRing: false,
    isRound: false,
    smallestConvexDiff: 0.06708776143453132,
    biggestConvexDiff: 0.2927530274899466,
    smallestConcaveDiff: 6.283185307179586,
    biggestConcaveDiff: 0);
