// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';
import 'package:flutter/material.dart';

class _Square68noholesClipper extends CustomClipper<Rect> {
  const _Square68noholesClipper();

  @override
  Rect getClip(Size size) {
    return Rect.fromCenter(
        center: Offset(295.9999632835388, 295.9999643388037),
        width: 592,
        height: 592);
  }

  @override
  bool shouldReclip(oldClipper) => false;
}

final square68Noholes = GearDefinition(
  id: 'square68Noholes',
  image: 'images/gears/square_68_noholes.png',
  thumbnailImage: 'images/gears/square_68_noholes_thumb.png',
  size: Size(592, 592),
  center: Offset(295.9999632835388, 295.9999643388037),
  toothCount: 64,
  entitlement: Entitlement.squaregears,
  package: Package.squaregears,
  points: [
    ContactPoint(position: Offset(284, 0), direction: 0),
    ContactPoint(
        position: Offset(275.2522187904823, -27.899779955884743),
        direction: 0.3557958821954914),
    ContactPoint(
        position: Offset(265.5405641282752, -51.76690195209495),
        direction: 0.4171467343474138),
    ContactPoint(
        position: Offset(254.38222424912217, -74.99381786021853),
        direction: 0.4785654305878291),
    ContactPoint(
        position: Offset(241.8189257086599, -97.491928933403),
        direction: 0.5399911915015085),
    ContactPoint(
        position: Offset(227.89853067693517, -119.17622725700518),
        direction: 0.6013908348734676),
    ContactPoint(
        position: Offset(212.67448285114236, -139.96541304838277),
        direction: 0.6627498646075924),
    ContactPoint(
        position: Offset(196.20496299760327, -159.78194805968332),
        direction: 0.7240742093903858),
    ContactPoint(
        position: Offset(178.55218139436786, -178.552117010844),
        direction: 0.7853975165266105),
    ContactPoint(
        position: Offset(159.78201458486717, -196.20494288396839),
        direction: 0.8467215066790139),
    ContactPoint(
        position: Offset(139.96544229018636, -212.674491476305),
        direction: 0.908046597052329),
    ContactPoint(
        position: Offset(119.17625062853885, -227.89853558040815),
        direction: 0.9694062141383029),
    ContactPoint(
        position: Offset(97.49192517085275, -241.8189127052089),
        direction: 1.030805500853596),
    ContactPoint(
        position: Offset(74.99378373856577, -254.38224137766406),
        direction: 1.0922312345581506),
    ContactPoint(
        position: Offset(51.766905896415146, -265.5405280480553),
        direction: 1.1536492329245362),
    ContactPoint(
        position: Offset(27.899863138735483, -275.2522038327231),
        direction: 1.2149998321669688),
    ContactPoint(
        position: Offset(0.00020179700867036245, -283.9999643382973),
        direction: 1.5707871397720385),
    ContactPoint(
        position: Offset(-27.89971667983107, -275.2526997566931),
        direction: 1.9265784445513852),
    ContactPoint(
        position: Offset(-51.76700132901305, -265.5411971928779),
        direction: 1.9879368201646015),
    ContactPoint(
        position: Offset(-74.99409354003464, -254.38290874396245),
        direction: 2.049360420794783),
    ContactPoint(
        position: Offset(-97.49227837595075, -241.81950722818135),
        direction: 2.110790336643454),
    ContactPoint(
        position: Offset(-119.17657393250505, -227.89900574054607),
        direction: 2.1721913558554853),
    ContactPoint(
        position: Offset(-139.96572496402786, -212.67482667947047),
        direction: 2.233553356074297),
    ContactPoint(
        position: Offset(-159.78218411805292, -196.2050570304744),
        direction: 2.294879821702381),
    ContactPoint(
        position: Offset(-178.55212249972686, -178.55216827609405),
        direction: 2.356194490192345),
    ContactPoint(
        position: Offset(-196.20505619021966, -159.78218506822475),
        direction: 2.4175090529817864),
    ContactPoint(
        position: Offset(-212.67484165711508, -139.96571006543468),
        direction: 2.4788355862330516),
    ContactPoint(
        position: Offset(-227.8990446142074, -119.17652709711304),
        direction: 2.5401977315601605),
    ContactPoint(
        position: Offset(-241.81961167355146, -97.49212337148953),
        direction: 2.601598878529748),
    ContactPoint(
        position: Offset(-254.38297139595275, -74.99398361194456),
        direction: 2.6630288521734657),
    ContactPoint(
        position: Offset(-265.5412138264759, -51.76698296784723),
        direction: 2.724452442999461),
    ContactPoint(
        position: Offset(-275.25272586249736, -27.899653401815964),
        direction: 2.7858107352252537),
    ContactPoint(
        position: Offset(-283.9999632829975, 0.00020553636704293828),
        direction: 3.141602152225849),
    ContactPoint(
        position: Offset(-275.2522140827736, 27.899833267980902),
        direction: 3.497389205721162),
    ContactPoint(
        position: Offset(-265.5404878445406, 51.76700208982984),
        direction: 3.5587401704560735),
    ContactPoint(
        position: Offset(-254.38217189038917, 74.99388055369839),
        direction: 3.6201582398613192),
    ContactPoint(
        position: Offset(-241.81887817122845, 97.49195602493286),
        direction: 3.6815835122248024),
    ContactPoint(
        position: Offset(-227.89846478195398, 119.17634529110481),
        direction: 3.7429830805422943),
    ContactPoint(
        position: Offset(-212.67443242094222, 139.96548004600834),
        direction: 3.8043431485037558),
    ContactPoint(
        position: Offset(-196.20489396359807, 159.78201814021108),
        direction: 3.8656678692119097),
    ContactPoint(
        position: Offset(-178.552016603016, 178.55223602583214),
        direction: 3.9269907091755396),
    ContactPoint(
        position: Offset(-159.7819037333455, 196.20501600379794),
        direction: 3.9883137609744916),
    ContactPoint(
        position: Offset(-139.96537887034657, 212.67454674336025),
        direction: 4.049639502732401),
    ContactPoint(
        position: Offset(-119.17616782366655, 227.89857056564773),
        direction: 4.110999525756344),
    ContactPoint(
        position: Offset(-97.49178657047932, 241.81898061478358),
        direction: 4.172396795449919),
    ContactPoint(
        position: Offset(-74.99381530199193, 254.38228661145737),
        direction: 4.233823789963575),
    ContactPoint(
        position: Offset(-51.76682461625882, 265.5405713519821),
        direction: 4.295243731836037),
    ContactPoint(
        position: Offset(-27.899728487439624, 275.2522209057174),
        direction: 4.356593604222046),
    ContactPoint(
        position: Offset(-0.000015078480542817632, 283.9999389648338),
        direction: 4.712390266976155),
    ContactPoint(
        position: Offset(27.899755138560003, 275.2521613073751),
        direction: 5.068184012814458),
    ContactPoint(
        position: Offset(51.76697991500496, 265.5405091155022),
        direction: 5.1295344760263895),
    ContactPoint(
        position: Offset(74.99381807691088, 254.3822241367046),
        direction: 5.1909544313156335),
    ContactPoint(
        position: Offset(97.4919637644729, 241.8188926054974),
        direction: 5.25238059097464),
    ContactPoint(
        position: Offset(119.17627863196095, 227.89847627041377),
        direction: 5.313778838947525),
    ContactPoint(
        position: Offset(139.96534447081496, 212.67458029087922),
        direction: 5.37513804766702),
    ContactPoint(
        position: Offset(159.78192445760234, 196.20501791736626),
        direction: 5.43646395907371),
    ContactPoint(
        position: Offset(178.55217590548858, 178.55211487033233),
        direction: 5.497787143782138),
    ContactPoint(
        position: Offset(196.20492888573307, 159.78201315939006),
        direction: 5.559110645637659),
    ContactPoint(
        position: Offset(212.67445510419003, 139.9654705338223),
        direction: 5.62043581782058),
    ContactPoint(
        position: Offset(227.89849995948077, 119.17625806587145),
        direction: 5.681794442866998),
    ContactPoint(
        position: Offset(241.81882705964276, 97.49209335990646),
        direction: 5.743192965466797),
    ContactPoint(
        position: Offset(254.38222303436729, 74.9939117544732),
        direction: 5.804619656769437),
    ContactPoint(
        position: Offset(265.5405647289405, 51.7669005966641),
        direction: 5.866038696379049),
    ContactPoint(
        position: Offset(275.2522187904823, 27.89985624983006),
        direction: 5.927389424984095),
  ],
  holes: [],
  isRing: false,
  isRound: false,
  smallestConvexDiff: 0.061314562789441585,
  biggestConvexDiff: 0.35579666275410915,
  smallestConcaveDiff: 6.283185307179586,
  biggestConcaveDiff: 0,
  ovalClipper: const _Square68noholesClipper(),
  pathClipper: null,
);
