// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final square75 = GearDefinition(
    id: 'square75',
    image: 'images/gears/square_75.png',
    thumbnailImage: 'images/gears/square_75_thumb.png',
    size: Size(648, 648),
    toothCount: 70,
    entitlement: Entitlement.squaregears,
    package: Package.squaregears,
    points: [
      ContactPoint(position: Offset(312, 0.1673111915588379), direction: 0),
      ContactPoint(
          position: Offset(303.2693720094124, -27.89414779848296),
          direction: 0.35053063198195744),
      ContactPoint(
          position: Offset(293.69216082209755, -51.97477152057606),
          direction: 0.40661726335929327),
      ContactPoint(
          position: Offset(282.7779797204065, -75.4803536453039),
          direction: 0.4627610920825376),
      ContactPoint(
          position: Offset(270.56236607444396, -98.33703288460991),
          direction: 0.5189281414391207),
      ContactPoint(
          position: Offset(257.0818814950648, -120.47128601425534),
          direction: 0.5750970144265342),
      ContactPoint(
          position: Offset(242.38144411170177, -141.81389612826513),
          direction: 0.6311998361663633),
      ContactPoint(
          position: Offset(226.50797397449477, -162.29871074547063),
          direction: 0.687282669326569),
      ContactPoint(
          position: Offset(209.51120003122065, -181.86156471166993),
          direction: 0.7433642825288267),
      ContactPoint(
          position: Offset(191.44482666674224, -200.44079379743354),
          direction: 0.7994224941214529),
      ContactPoint(
          position: Offset(172.3663812329522, -217.97887857264615),
          direction: 0.8554651332112275),
      ContactPoint(
          position: Offset(152.33516039799676, -234.42086290440793),
          direction: 0.9115327309062389),
      ContactPoint(
          position: Offset(131.41327512900443, -249.71444405921838),
          direction: 0.9676538551829594),
      ContactPoint(
          position: Offset(109.66580227139576, -263.8097960938512),
          direction: 1.023794451990491),
      ContactPoint(
          position: Offset(87.1618840886502, -276.66299320010097),
          direction: 1.0799372429645775),
      ContactPoint(
          position: Offset(63.971570465818516, -288.23298127767816),
          direction: 1.1361100803563478),
      ContactPoint(
          position: Offset(40.16866167260754, -298.48222302157217),
          direction: 1.1922395230471547),
      ContactPoint(
          position: Offset(14.16925495747744, -307.80679307226154),
          direction: 1.3912567967883893),
      ContactPoint(
          position: Offset(-14.169086284475753, -307.8071540030491),
          direction: 1.7503164017690231),
      ContactPoint(
          position: Offset(-40.16896178904723, -298.4828146642667),
          direction: 1.9493554137141915),
      ContactPoint(
          position: Offset(-63.971707565237175, -288.2331432354686),
          direction: 2.0054867579649063),
      ContactPoint(
          position: Offset(-87.16200287258587, -276.66344009268386),
          direction: 2.0616478911015292),
      ContactPoint(
          position: Offset(-109.66616483958225, -263.8102592045541),
          direction: 2.1178052901907476),
      ContactPoint(
          position: Offset(-131.4133648845701, -249.71449099623464),
          direction: 2.173944792537334),
      ContactPoint(
          position: Offset(-152.33522902373642, -234.4211652396239),
          direction: 2.2300478535950212),
      ContactPoint(
          position: Offset(-172.36683756838002, -217.97940986843443),
          direction: 2.2861239937761235),
      ContactPoint(
          position: Offset(-191.4452374842332, -200.44103439953255),
          direction: 2.3421824385448757),
      ContactPoint(
          position: Offset(-209.5112637918829, -181.8616111326357),
          direction: 2.39823434331861),
      ContactPoint(
          position: Offset(-226.5079959290807, -162.29892690546964),
          direction: 2.4542998405177148),
      ContactPoint(
          position: Offset(-242.38191392445782, -141.81425226656907),
          direction: 2.510389132001344),
      ContactPoint(
          position: Offset(-257.08220382775585, -120.47140363527227),
          direction: 2.566508203530989),
      ContactPoint(
          position: Offset(-270.56223428775377, -98.3371643642773),
          direction: 2.622657751767532),
      ContactPoint(
          position: Offset(-282.77852311440927, -75.48076234617001),
          direction: 2.67882618346269),
      ContactPoint(
          position: Offset(-293.692388685294, -51.97479997434153),
          direction: 2.7349755774826816),
      ContactPoint(
          position: Offset(-303.27002360957624, -27.89428329609699),
          direction: 2.7910662457962427),
      ContactPoint(
          position: Offset(-311.99999999886677, 0.16744558962036793),
          direction: 3.141606396559765),
      ContactPoint(
          position: Offset(-303.26934775065666, 28.228771321818446),
          direction: 3.4921233867420027),
      ContactPoint(
          position: Offset(-293.6921657845985, 52.309334632396634),
          direction: 3.548210076986141),
      ContactPoint(
          position: Offset(-282.77792289536734, 75.81502869234772),
          direction: 3.604355808124156),
      ContactPoint(
          position: Offset(-270.56225285138925, 98.67159497804221),
          direction: 3.6605237952621326),
      ContactPoint(
          position: Offset(-257.08171372517154, 120.80584724375274),
          direction: 3.716689656251892),
      ContactPoint(
          position: Offset(-242.38133572089515, 142.1484491992124),
          direction: 3.772791635384998),
      ContactPoint(
          position: Offset(-226.50786754077816, 162.63326233779776),
          direction: 3.8288742711728574),
      ContactPoint(
          position: Offset(-209.51116383285134, 182.19611564057237),
          direction: 3.8849557567389787),
      ContactPoint(
          position: Offset(-191.44475981567024, 200.77539152905388),
          direction: 3.941014936925998),
      ContactPoint(
          position: Offset(-172.36635798567505, 218.31343360386504),
          direction: 3.997056984207514),
      ContactPoint(
          position: Offset(-152.3352172252481, 234.75540805935128),
          direction: 4.053124219444506),
      ContactPoint(
          position: Offset(-131.4133147653991, 250.0490248949338),
          direction: 4.109247130058422),
      ContactPoint(
          position: Offset(-109.66590300870678, 264.1442734028935),
          direction: 4.16538769824101),
      ContactPoint(
          position: Offset(-87.16186337537515, 276.9975760106144),
          direction: 4.221528970146263),
      ContactPoint(
          position: Offset(-63.97154617268774, 288.567577337905),
          direction: 4.277703564001074),
      ContactPoint(
          position: Offset(-40.168717737167306, 298.81672435770804),
          direction: 4.333832622414813),
      ContactPoint(
          position: Offset(-14.16919742178252, 308.1413651008716),
          direction: 4.5328543233452505),
      ContactPoint(
          position: Offset(14.169104543470986, 308.14136534144893),
          direction: 4.891923525154851),
      ContactPoint(
          position: Offset(40.16865545597521, 298.81672485330597),
          direction: 5.090945226606381),
      ContactPoint(
          position: Offset(63.97146625452648, 288.56757902064294),
          direction: 5.147074063783611),
      ContactPoint(
          position: Offset(87.16169122714388, 276.9976475006192),
          direction: 5.203247142367962),
      ContactPoint(
          position: Offset(109.66579227761444, 264.1443978601708),
          direction: 5.259389880096263),
      ContactPoint(
          position: Offset(131.41329579040215, 250.0490274545049),
          direction: 5.315530454678996),
      ContactPoint(
          position: Offset(152.33521712513217, 234.75548099652522),
          direction: 5.371652122095833),
      ContactPoint(
          position: Offset(172.36635278296365, 218.31352967693442),
          direction: 5.427720402216618),
      ContactPoint(
          position: Offset(191.4448877018985, 200.7753932923676),
          direction: 5.483762813058134),
      ContactPoint(
          position: Offset(209.51117483572878, 182.1962118229406),
          direction: 5.5398216799817055),
      ContactPoint(
          position: Offset(226.5079135771463, 162.6333933866674),
          direction: 5.595902721628829),
      ContactPoint(
          position: Offset(242.38138999095852, 142.14857008709302),
          direction: 5.651986447437491),
      ContactPoint(
          position: Offset(257.0817594247523, 120.80596943252927),
          direction: 5.708088292753052),
      ContactPoint(
          position: Offset(270.5622987888877, 98.67172724660749),
          direction: 5.764256115500454),
      ContactPoint(
          position: Offset(282.7779172390353, 75.81503996242877),
          direction: 5.820423945132098),
      ContactPoint(
          position: Offset(293.6920967850593, 52.30949242756712),
          direction: 5.876567411320432),
      ContactPoint(
          position: Offset(303.26936989576524, 28.228775962433218),
          direction: 5.932654162270776),
    ],
    holes: []);
