// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final square32 = GearDefinition(
    id: 'square32',
    image: 'images/gears/square_32.png',
    thumbnailImage: 'images/gears/square_32_thumb.png',
    size: Size(304, 296),
    center: Offset(152, 148),
    toothCount: 30,
    entitlement: Entitlement.squaregears,
    package: Package.squaregears,
    points: [
      ContactPoint(
          position: Offset(139.9999804198742, -0.037811279296875),
          direction: 0),
      ContactPoint(
          position: Offset(130.08584737473828, -28.496174018709794),
          direction: 0.4253657168452447),
      ContactPoint(
          position: Offset(117.50671461356472, -52.03149018811499),
          direction: 0.5563488326120396),
      ContactPoint(
          position: Offset(101.96143714374432, -73.72153067329509),
          direction: 0.6872777680265845),
      ContactPoint(
          position: Offset(83.71969386416025, -93.19679298357906),
          direction: 0.8180999519750074),
      ContactPoint(
          position: Offset(63.09341961051004, -110.12699645616932),
          direction: 0.9489656333023877),
      ContactPoint(
          position: Offset(40.43202543980258, -124.2198132915055),
          direction: 1.0799498344773744),
      ContactPoint(
          position: Offset(14.499014077801027, -135.7145737967501),
          direction: 1.3523011214436327),
      ContactPoint(
          position: Offset(-14.49908261591578, -135.71471231985151),
          direction: 1.789285573458483),
      ContactPoint(
          position: Offset(-40.43219231268149, -124.21996684294454),
          direction: 2.061645514940916),
      ContactPoint(
          position: Offset(-63.093498831804865, -110.12700029795391),
          direction: 2.192625652126724),
      ContactPoint(
          position: Offset(-83.71995145358883, -93.19696299128994),
          direction: 2.3234915081414593),
      ContactPoint(
          position: Offset(-101.96161645130364, -73.72151842682001),
          direction: 2.4543182621147617),
      ContactPoint(
          position: Offset(-117.50690461351492, -52.03148237944726),
          direction: 2.585242341181106),
      ContactPoint(
          position: Offset(-130.08612266144905, -28.496127240989843),
          direction: 2.716230518258672),
      ContactPoint(
          position: Offset(-139.99999999982134, -0.03768476316378335),
          direction: 3.1415981103378634),
      ContactPoint(
          position: Offset(-130.08584698558778, 28.42058507340073),
          direction: 3.566958653648339),
      ContactPoint(
          position: Offset(-117.50672958750053, 51.95590479684901),
          direction: 3.697941390066485),
      ContactPoint(
          position: Offset(-101.96143229314173, 73.6459563877293),
          direction: 3.828870690777514),
      ContactPoint(
          position: Offset(-83.71966885795831, 93.12123439305647),
          direction: 3.9596929630930893),
      ContactPoint(
          position: Offset(-63.09340574392883, 110.05140388934106),
          direction: 4.09055903024276),
      ContactPoint(
          position: Offset(-40.432034958106854, 124.14418358918789),
          direction: 4.221542405329434),
      ContactPoint(
          position: Offset(-14.499034072519597, 135.6389581413418),
          direction: 4.49389606232444),
      ContactPoint(
          position: Offset(14.499033464448175, 135.63894279258147),
          direction: 4.930881933034596),
      ContactPoint(
          position: Offset(40.43202384150155, 124.14420017023392),
          direction: 5.2032353216798874),
      ContactPoint(
          position: Offset(63.09346328509122, 110.05136968182968),
          direction: 5.334219458392536),
      ContactPoint(
          position: Offset(83.71972510480865, 93.12116974772462),
          direction: 5.465085437764013),
      ContactPoint(
          position: Offset(101.96142211302231, 73.64595361319883),
          direction: 5.595907569109701),
      ContactPoint(
          position: Offset(117.5067007728664, 51.9559187549348),
          direction: 5.726836698344609),
      ContactPoint(
          position: Offset(130.0858481788229, 28.420549685187815),
          direction: 5.857819752715117),
    ],
    holes: [
      GearHole(
          name: '0', angle: 1.5713141649750018, distance: 0.009452821091635867),
      GearHole(
          name: '8', angle: 1.570796937951684, distance: 8.009452819825714),
      GearHole(
          name: '9', angle: 2.355452742421136, distance: 9.006690092003176),
      GearHole(
          name: '10', angle: 3.1406473723516437, distance: 10.000009362818398),
      GearHole(
          name: '11', angle: -2.3568028245176253, distance: 10.993321342463627),
      GearHole(
          name: '12', angle: -1.5707967350357703, distance: 11.99054718017678),
      GearHole(
          name: '13', angle: -0.7848839995797797, distance: 12.993314103176036),
      GearHole(
          name: '14',
          angle: 0.0006752015494890745,
          distance: 13.999998296247965),
      GearHole(
          name: '15', angle: 0.7858438058418805, distance: 15.006682181831522),
      GearHole(
          name: '16', angle: 1.5707966325537197, distance: 16.00945281982497),
      GearHole(
          name: '17', angle: 2.3558016628824667, distance: 17.00668892648806),
      GearHole(
          name: '18', angle: 3.141067497123984, distance: 18.000007377136235),
      GearHole(
          name: '19', angle: -2.3565465936832646, distance: 18.993320485677078),
      GearHole(
          name: '20', angle: -1.5707965716622039, distance: 19.99054718017638),
      GearHole(
          name: '21', angle: -0.7850799338898394, distance: 20.993313448687648),
    ]);
