// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final square64 = GearDefinition(
    id: 'square64',
    image: 'images/gears/square_64.png',
    thumbnailImage: 'images/gears/square_64_thumb.png',
    size: Size(560, 560),
    center: Offset(279.9999608397484, 279.9999902099371),
    toothCount: 60,
    entitlement: Entitlement.squaregears,
    package: Package.squaregears,
    points: [
      ContactPoint(
          position: Offset(267.99999999999756, 0.000007694835640944395),
          direction: 6.283184665943283),
      ContactPoint(
          position: Offset(259.15535793796823, -28.021832742553165),
          direction: 0.3598832947302135),
      ContactPoint(
          position: Offset(249.24123695932494, -51.9645303383879),
          direction: 0.4253338887927782),
      ContactPoint(
          position: Offset(237.7808312730943, -75.20760787620495),
          direction: 0.49084834840804614),
      ContactPoint(
          position: Offset(224.82313701756505, -97.65039114554911),
          direction: 0.5563590046239026),
      ContactPoint(
          position: Offset(210.42446880845358, -119.19678434246539),
          direction: 0.6218491971424589),
      ContactPoint(
          position: Offset(194.64701279110008, -139.75444547485398),
          direction: 0.6873026154722588),
      ContactPoint(
          position: Offset(177.55973379823126, -159.2361726412677),
          direction: 0.7527062532109259),
      ContactPoint(
          position: Offset(159.23620049222376, -177.55970577838175),
          direction: 0.8180903780589457),
      ContactPoint(
          position: Offset(139.7544461011529, -194.64698938884317),
          direction: 0.8834936438009482),
      ContactPoint(
          position: Offset(119.19677125137227, -210.42447869894787),
          direction: 0.9489469074074073),
      ContactPoint(
          position: Offset(97.65043164005849, -224.82309834062207),
          direction: 1.0144378404979841),
      ContactPoint(
          position: Offset(75.2076311711061, -237.78078744973973),
          direction: 1.0799486608530264),
      ContactPoint(
          position: Offset(51.96450809340363, -249.24119315763488),
          direction: 1.145461681187789),
      ContactPoint(
          position: Offset(28.02179209804412, -259.1553846172341),
          direction: 1.210912575138141),
      ContactPoint(
          position: Offset(0.00001626320539617521, -267.99999020977674),
          direction: 1.5707911568305146),
      ContactPoint(
          position: Offset(-28.02190181080178, -259.1556640217206),
          direction: 1.9306721851768112),
      ContactPoint(
          position: Offset(-51.96473408621244, -249.24156758926824),
          direction: 1.9961293121579775),
      ContactPoint(
          position: Offset(-75.20786910756087, -237.78110389990496),
          direction: 2.0616477318916697),
      ContactPoint(
          position: Offset(-97.65065416673006, -224.82325702514171),
          direction: 2.1271616764400134),
      ContactPoint(
          position: Offset(-119.19688621041483, -210.4244614154856),
          direction: 2.1926465815146354),
      ContactPoint(
          position: Offset(-139.7545712374952, -194.6471688305642),
          direction: 2.258089470017387),
      ContactPoint(
          position: Offset(-159.23660360601139, -177.56007740118991),
          direction: 2.3234960356248084),
      ContactPoint(
          position: Offset(-177.56021221147108, -159.2364531912969),
          direction: 2.3888935677471257),
      ContactPoint(
          position: Offset(-194.64731758387768, -139.75439113807792),
          direction: 2.4543000088089024),
      ContactPoint(
          position: Offset(-210.42460639993308, -119.1966824874032),
          direction: 2.51974294828151),
      ContactPoint(
          position: Offset(-224.82342011844293, -97.65040540152226),
          direction: 2.585227757772794),
      ContactPoint(
          position: Offset(-237.78119384575567, -75.20770882032078),
          direction: 2.650741976000859),
      ContactPoint(
          position: Offset(-249.24168024867217, -51.96450071595633),
          direction: 2.7162600788474283),
      ContactPoint(
          position: Offset(-259.15575716009783, -28.021678955393632),
          direction: 2.781718975825399),
      ContactPoint(
          position: Offset(-267.9999608393725, 0.000217053470417764),
          direction: 3.141600568852953),
      ContactPoint(
          position: Offset(-259.1553350858349, 28.02195213099769),
          direction: 3.5014770681346277),
      ContactPoint(
          position: Offset(-249.24115362229705, 51.96460692165631),
          direction: 3.566927964794461),
      ContactPoint(
          position: Offset(-237.78074508965122, 75.20769295169802),
          direction: 3.632440389967396),
      ContactPoint(
          position: Offset(-224.82309356183694, 97.6504575738371),
          direction: 3.6979506900627293),
      ContactPoint(
          position: Offset(-210.42444327380178, 119.19686432896128),
          direction: 3.7634422293144354),
      ContactPoint(
          position: Offset(-194.64692433142636, 139.7545425542309),
          direction: 3.828895864893072),
      ContactPoint(
          position: Offset(-177.55963347634918, 159.2362959284016),
          direction: 3.894299045737447),
      ContactPoint(
          position: Offset(-159.2360783604204, 177.5598279062905),
          direction: 3.9596830386697666),
      ContactPoint(
          position: Offset(-139.7543477785736, 194.64710938652354),
          direction: 4.02508702725188),
      ContactPoint(
          position: Offset(-119.1966599909321, 210.42454241458768),
          direction: 4.09054158154666),
      ContactPoint(
          position: Offset(-97.65030199596886, 224.8231144947526),
          direction: 4.156031237328452),
      ContactPoint(
          position: Offset(-75.20757774965672, 237.78077002894102),
          direction: 4.221540595028468),
      ContactPoint(
          position: Offset(-51.964533227423004, 249.24116770344946),
          direction: 4.287053431346476),
      ContactPoint(
          position: Offset(-28.02181101434642, 259.1553851483691),
          direction: 4.352504903072962),
      ContactPoint(
          position: Offset(-0.000007563943557260521, 267.99996948241943),
          direction: 4.712389621621815),
      ContactPoint(
          position: Offset(28.021875737041935, 259.1553589847042),
          direction: 5.072272027424129),
      ContactPoint(
          position: Offset(51.964476722630636, 249.2412335984418),
          direction: 5.137723547937657),
      ContactPoint(
          position: Offset(75.20763609631081, 237.780801983465),
          direction: 5.2032371117060086),
      ContactPoint(
          position: Offset(97.65045727798064, 224.8230823017346),
          direction: 5.26874698782422),
      ContactPoint(
          position: Offset(119.19686236241164, 210.42446757142093),
          direction: 5.334238354486987),
      ContactPoint(
          position: Offset(139.75450907820434, 194.6469496479403),
          direction: 5.399691872735632),
      ContactPoint(
          position: Offset(159.236255689194, 177.5597112467945),
          direction: 5.465094262516717),
      ContactPoint(
          position: Offset(177.55967345422593, 159.23629397369464),
          direction: 5.530479138220462),
      ContactPoint(
          position: Offset(194.6469801655184, 139.75453959578246),
          direction: 5.595882414828644),
      ContactPoint(
          position: Offset(210.4244370538428, 119.19689287998976),
          direction: 5.6613359330772886),
      ContactPoint(
          position: Offset(224.8231054833641, 97.65049959180607),
          direction: 5.726826142133591),
      ContactPoint(
          position: Offset(237.78080339438395, 75.20772500923742),
          direction: 5.7923374252920325),
      ContactPoint(
          position: Offset(249.2412388212539, 51.96452622803578),
          direction: 5.857851794420328),
      ContactPoint(
          position: Offset(259.1553274203901, 28.021909036498485),
          direction: 5.923302012449373),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.3561944901923444, distance: 11.000000000000004),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(
          name: '13', angle: -0.7853981633974483, distance: 13.000000000000004),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974483, distance: 15.000000000000002),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(
          name: '17', angle: 2.356194490192345, distance: 16.999999999999996),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: 0, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(name: '25', angle: 2.356194490192345, distance: 25),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(
          name: '29', angle: -0.7853981633974486, distance: 29.000000000000004),
      GearHole(name: '30', angle: -4.736951571734001e-16, distance: 30),
      GearHole(name: '31', angle: 0.785398163397448, distance: 31),
      GearHole(name: '32', angle: 1.5707963267948966, distance: 32),
      GearHole(name: '33', angle: 2.356194490192345, distance: 33),
      GearHole(name: '34', angle: 3.141592653589793, distance: 34),
      GearHole(name: '35', angle: -2.356194490192345, distance: 35),
      GearHole(name: '36', angle: -1.570796326794897, distance: 36),
      GearHole(
          name: '37', angle: -0.7853981633974485, distance: 37.00000000000001),
      GearHole(name: '38', angle: -3.739698609263685e-16, distance: 38),
      GearHole(
          name: '39', angle: 0.7853981633974481, distance: 39.00000000000001),
      GearHole(name: '40', angle: 1.5707963267948966, distance: 40),
      GearHole(name: '41', angle: 2.356194490192345, distance: 41),
      GearHole(name: '42', angle: 3.141592653589793, distance: 42),
      GearHole(
          name: '43', angle: -2.3561944901923453, distance: 42.99999999999999),
      GearHole(name: '44', angle: -1.5707963267948968, distance: 44),
      GearHole(
          name: '45', angle: -0.7853981633974485, distance: 44.99999999999999),
      GearHole(name: '46', angle: -3.089316242435218e-16, distance: 46),
      GearHole(name: '47', angle: 0.785398163397448, distance: 47),
      GearHole(name: '48', angle: 1.5707963267948966, distance: 48),
      GearHole(name: '49', angle: 2.356194490192345, distance: 49),
      GearHole(name: '50', angle: 3.141592653589793, distance: 50),
      GearHole(
          name: '51', angle: -2.356194490192345, distance: 51.00000000000001),
      GearHole(name: '52', angle: -1.5707963267948968, distance: 52),
      GearHole(name: '54', angle: -2.631639762074445e-16, distance: 54),
      GearHole(name: '56', angle: 1.5707963267948966, distance: 56),
      GearHole(name: '58', angle: 3.141592653589793, distance: 58),
    ]);
