// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';

final squiggle = GearDefinition(
    image: 'images/squiggle.png',
    size: Size(448, 448),
    toothCount: 51,
    points: [
      ContactPoint(
          position: Offset(211.99403241238386, 9.621600091589398),
          direction: 0.031538553904333355),
      ContactPoint(
          position: Offset(210.02001156693754, -16.980946004058183),
          direction: 0.14260097908944758),
      ContactPoint(
          position: Offset(204.3568892630609, -43.33367846859705),
          direction: 0.27664760406240685),
      ContactPoint(
          position: Offset(195.35838841766156, -68.65798529547936),
          direction: 0.4039602129732902),
      ContactPoint(
          position: Offset(183.29014346952158, -92.62867273870312),
          direction: 0.5280051115277153),
      ContactPoint(
          position: Offset(168.37431179881992, -114.92640843854232),
          direction: 0.6511523775918047),
      ContactPoint(
          position: Offset(150.82906915353286, -135.22617725600776),
          direction: 0.7746977187414084),
      ContactPoint(
          position: Offset(130.90364649321, -153.20635402997456),
          direction: 0.8988706489473124),
      ContactPoint(
          position: Offset(108.90281839681994, -168.5743169106984),
          direction: 1.0228963277399306),
      ContactPoint(
          position: Offset(85.19312140302448, -181.10281929051155),
          direction: 1.145179121575806),
      ContactPoint(
          position: Offset(60.18685533988182, -190.66455926085686),
          direction: 1.263681885169067),
      ContactPoint(
          position: Offset(34.30763183130165, -197.24954161110605),
          direction: 1.3763643162637438),
      ContactPoint(
          position: Offset(7.777825059235178, -200.97491327026333),
          direction: 1.4961107451761837),
      ContactPoint(
          position: Offset(-21.089623576392114, -200.92045325337492),
          direction: 1.8024810181840198),
      ContactPoint(
          position: Offset(-48.243792544849825, -187.18720545911762),
          direction: 2.236886124848416),
      ContactPoint(
          position: Offset(-67.77972070692552, -164.38787305586112),
          direction: 2.6454087273807696),
      ContactPoint(
          position: Offset(-76.1618812001625, -136.01988993474362),
          direction: 3.0115832681619046),
      ContactPoint(
          position: Offset(-75.64141973460787, -107.97420338224015),
          direction: 3.2408002455060227),
      ContactPoint(
          position: Offset(-71.21253753264949, -83.13119217269958),
          direction: 3.231539442762103),
      ContactPoint(
          position: Offset(-71.06307078209842, -60.4707667183347),
          direction: 3.0099783044641484),
      ContactPoint(
          position: Offset(-76.73485012920457, -39.55682834865989),
          direction: 2.709615419508294),
      ContactPoint(
          position: Offset(-88.95229258913643, -21.666109242534827),
          direction: 2.4091609197442327),
      ContactPoint(
          position: Offset(-106.3935784369164, -6.984937053603797),
          direction: 2.198623657836662),
      ContactPoint(
          position: Offset(-127.01088200274727, 5.69735825080987),
          direction: 2.1026425647564606),
      ContactPoint(
          position: Offset(-149.2210706192304, 18.15112907916729),
          direction: 2.1108060935032498),
      ContactPoint(
          position: Offset(-171.74410324327025, 32.60881052513797),
          direction: 2.2285723192752407),
      ContactPoint(
          position: Offset(-192.38485442475664, 51.83818492108512),
          direction: 2.4717119472199256),
      ContactPoint(
          position: Offset(-206.71441901182504, 77.22159859122203),
          direction: 2.7996816070801502),
      ContactPoint(
          position: Offset(-211.64507424481275, 105.67554957235329),
          direction: 3.1023023747374125),
      ContactPoint(
          position: Offset(-208.77656489580673, 135.12123850952779),
          direction: 3.459884218934846),
      ContactPoint(
          position: Offset(-192.93852609080636, 160.85096106669948),
          direction: 3.9220920645432527),
      ContactPoint(
          position: Offset(-168.4399018590188, 176.7337388584249),
          direction: 4.250387927706075),
      ContactPoint(
          position: Offset(-142.86189873369653, 186.32068406633095),
          direction: 4.415151522274282),
      ContactPoint(
          position: Offset(-117.07854755673836, 192.57615863324045),
          direction: 4.513090484201072),
      ContactPoint(
          position: Offset(-91.27619750786536, 196.77277088582778),
          direction: 4.578087989998195),
      ContactPoint(
          position: Offset(-65.50230498914723, 199.5572188739512),
          direction: 4.624780438094283),
      ContactPoint(
          position: Offset(-39.77171962671248, 201.30215101602082),
          direction: 4.660212781203661),
      ContactPoint(
          position: Offset(-14.08805255230493, 202.24508886695617),
          direction: 4.688210838344332),
      ContactPoint(
          position: Offset(11.549478065006817, 202.54481947520046),
          direction: 4.711044419316069),
      ContactPoint(
          position: Offset(37.141895947561444, 202.3149310658878),
          direction: 4.730052319523956),
      ContactPoint(
          position: Offset(62.69220000980543, 201.64197937466025),
          direction: 4.746191116855876),
      ContactPoint(
          position: Offset(88.20375597213783, 200.58866542373275),
          direction: 4.760161247958669),
      ContactPoint(
          position: Offset(113.89219126988738, 199.18991821245993),
          direction: 4.790232270925106),
      ContactPoint(
          position: Offset(140.42274291048503, 196.44353563826726),
          direction: 4.90373089720665),
      ContactPoint(
          position: Offset(168.59128864658476, 187.92748618348156),
          direction: 5.254723644472314),
      ContactPoint(
          position: Offset(189.85141163194183, 166.04614948736744),
          direction: 5.716190218768226),
      ContactPoint(
          position: Offset(200.41170508329205, 139.42430087777333),
          direction: 5.995523947657523),
      ContactPoint(
          position: Offset(205.89333640615084, 113.13362462449598),
          direction: 6.120907301675654),
      ContactPoint(
          position: Offset(209.0373982640162, 87.15178954372377),
          direction: 6.188413988470872),
      ContactPoint(
          position: Offset(210.8332120722418, 61.33973717448066),
          direction: 6.230951048029903),
      ContactPoint(
          position: Offset(211.7363544969891, 35.63610071684674),
          direction: 6.260504355942139),
    ]);
