// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final triangle52 = GearDefinition(
    id: 'triangle52',
    image: 'images/gears/triangle_52.png',
    thumbnailImage: 'images/gears/triangle_52_thumb.png',
    size: Size(416, 416),
    toothCount: 46,
    entitlement: Entitlement.trianglegears,
    package: Package.trianglegears,
    points: [
      ContactPoint(
          position: Offset(197.2530517578125, -0.5779609680175781),
          direction: 0),
      ContactPoint(
          position: Offset(184.33837540135173, -28.76156963135964),
          direction: 0.5117124280764163),
      ContactPoint(
          position: Offset(170.7064764747006, -50.90685851726175),
          direction: 0.5920052667524702),
      ContactPoint(
          position: Offset(155.3379189068783, -71.88692740719245),
          direction: 0.6724831672662521),
      ContactPoint(
          position: Offset(138.33174807656417, -91.56309273350624),
          direction: 0.7529689908717803),
      ContactPoint(
          position: Offset(119.79997581860542, -109.80804779416948),
          direction: 0.8333630369822984),
      ContactPoint(
          position: Offset(99.86510219811444, -126.50612548803745),
          direction: 0.9136283138997019),
      ContactPoint(
          position: Offset(78.65759073844403, -141.55269652732653),
          direction: 0.9937876705287305),
      ContactPoint(
          position: Offset(56.31433419935061, -154.85343747509305),
          direction: 1.0738993325159276),
      ContactPoint(
          position: Offset(32.978091244071024, -166.32375826141745),
          direction: 1.1540355131675657),
      ContactPoint(
          position: Offset(8.797190350641442, -175.88884389678614),
          direction: 1.2342662986152177),
      ContactPoint(
          position: Offset(-16.074302531257118, -183.48400224571216),
          direction: 1.3146165833845478),
      ContactPoint(
          position: Offset(-41.47686437215526, -189.05727339008584),
          direction: 1.39507573472941),
      ContactPoint(
          position: Offset(-67.24576464761981, -192.5695504483075),
          direction: 1.4755742547761734),
      ContactPoint(
          position: Offset(-93.21220457749276, -193.99867827697273),
          direction: 1.5559541162047203),
      ContactPoint(
          position: Offset(-122.44750301604368, -192.67188541935752),
          direction: 1.912739419130494),
      ContactPoint(
          position: Offset(-145.25414345160544, -174.4914052443235),
          direction: 2.4487539038139023),
      ContactPoint(
          position: Offset(-159.14361402455643, -150.6849233954629),
          direction: 2.6596047454948275),
      ContactPoint(
          position: Offset(-170.26312183848086, -127.17552592757015),
          direction: 2.740043213916297),
      ContactPoint(
          position: Offset(-179.45632628810142, -102.84747057281577),
          direction: 2.820545100476039),
      ContactPoint(
          position: Offset(-186.66328773722458, -77.85970603825639),
          direction: 2.900976690912575),
      ContactPoint(
          position: Offset(-191.84074257806014, -52.37551160320289),
          direction: 2.981277928159302),
      ContactPoint(
          position: Offset(-194.9587348164048, -26.559673201047584),
          direction: 3.061467613798684),
      ContactPoint(
          position: Offset(-195.9999999999983, -0.5778324944832228),
          direction: 3.1415931871916145),
      ContactPoint(
          position: Offset(-194.95870704224538, 25.403993488215647),
          direction: 3.221718808739959),
      ContactPoint(
          position: Offset(-191.84068335669548, 51.219861440542),
          direction: 3.301908423577988),
      ContactPoint(
          position: Offset(-186.66322003129343, 76.7039330711953),
          direction: 3.382209615029478),
      ContactPoint(
          position: Offset(-179.456216639314, 101.69180893856966),
          direction: 3.4626409559678075),
      ContactPoint(
          position: Offset(-170.26297364369157, 126.01987101254912),
          direction: 3.5431427832833244),
      ContactPoint(
          position: Offset(-159.14353695495714, 149.5290944948505),
          direction: 3.623580701128195),
      ContactPoint(
          position: Offset(-145.25406491685766, 173.33558831238236),
          direction: 3.8344336865072526),
      ContactPoint(
          position: Offset(-122.44728886064956, 191.51603285439472),
          direction: 4.370447959697595),
      ContactPoint(
          position: Offset(-93.21194755173417, 192.8428057407372),
          direction: 4.727232264854289),
      ContactPoint(
          position: Offset(-67.24557307431522, 191.4136338754913),
          direction: 4.807613038620296),
      ContactPoint(
          position: Offset(-41.47671491018367, 187.90130924550968),
          direction: 4.888110599335968),
      ContactPoint(
          position: Offset(-16.07424666545021, 182.32805477871065),
          direction: 4.968569592946503),
      ContactPoint(
          position: Offset(8.797229932441542, 174.73286309268457),
          direction: 5.048918461673283),
      ContactPoint(
          position: Offset(32.97810816962612, 165.16785378655715),
          direction: 5.129148555317651),
      ContactPoint(
          position: Offset(56.31439711603804, 153.69751451874055),
          direction: 5.2092861530282795),
      ContactPoint(
          position: Offset(78.65766384844108, 140.39675147296083),
          direction: 5.289398837270409),
      ContactPoint(
          position: Offset(99.86519928679877, 125.35010772785341),
          direction: 5.36955757596836),
      ContactPoint(
          position: Offset(119.80010062823517, 108.65202418762567),
          direction: 5.449822578596975),
      ContactPoint(
          position: Offset(138.33190391923523, 90.4069994777556),
          direction: 5.530216712956731),
      ContactPoint(
          position: Offset(155.33795302353096, 70.73097043385216),
          direction: 5.610702621384386),
      ContactPoint(
          position: Offset(170.70653861978315, 49.750843377955015),
          direction: 5.69118020617897),
      ContactPoint(
          position: Offset(184.33837638607662, 27.605645941925015),
          direction: 5.771473046685919),
    ],
    holes: []);
