// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final triangle42 = GearDefinition(
    id: 'triangle42',
    image: 'images/gears/triangle_42.png',
    thumbnailImage: 'images/gears/triangle_42_thumb.png',
    size: Size(344, 340),
    center: Offset(153.92980194091797, 170.3508071899414),
    toothCount: 37,
    entitlement: Entitlement.trianglegears,
    package: Package.trianglegears,
    points: [
      ContactPoint(position: Offset(180, 0), direction: 0),
      ContactPoint(
          position: Offset(166.70548946867805, -28.36412276997156),
          direction: 0.5312465934578112),
      ContactPoint(
          position: Offset(152.24565954719654, -50.38047587830327),
          direction: 0.6311541043029836),
      ContactPoint(
          position: Offset(135.65767281275907, -70.84363381467595),
          direction: 0.7312152168297015),
      ContactPoint(
          position: Offset(117.10942887138167, -89.546745129182),
          direction: 0.8311786249076052),
      ContactPoint(
          position: Offset(96.7905117975142, -106.30589565585946),
          direction: 0.9309558372558815),
      ContactPoint(
          position: Offset(74.90590855566727, -120.9588559887103),
          direction: 1.030596728466202),
      ContactPoint(
          position: Offset(51.67300647594192, -133.3629373152712),
          direction: 1.1302161883232067),
      ContactPoint(
          position: Offset(27.32035295941583, -143.39481032662002),
          direction: 1.2299360393233858),
      ContactPoint(
          position: Offset(2.087273389762453, -150.95101512606828),
          direction: 1.329841109223013),
      ContactPoint(
          position: Offset(-23.775825510248648, -155.95046677533077),
          direction: 1.4298879668477618),
      ContactPoint(
          position: Offset(-50.00844586256575, -158.3407674261598),
          direction: 1.5298875582760667),
      ContactPoint(
          position: Offset(-79.58226696978672, -157.4572775187605),
          direction: 1.9055302238421952),
      ContactPoint(
          position: Offset(-102.55973163192922, -139.0274060191875),
          direction: 2.4625720152157715),
      ContactPoint(
          position: Offset(-116.0701407624947, -114.63244874369306),
          direction: 2.6922137706605778),
      ContactPoint(
          position: Offset(-126.31292780895741, -90.36352234716263),
          direction: 2.7922599241533756),
      ContactPoint(
          position: Offset(-134.07957727215052, -65.19310652195723),
          direction: 2.8922716925530976),
      ContactPoint(
          position: Offset(-139.29569412444033, -39.37530992572973),
          direction: 2.992111688648249),
      ContactPoint(
          position: Offset(-141.91492130789572, -13.168421742414203),
          direction: 3.091786848203128),
      ContactPoint(
          position: Offset(-141.91491745691275, 13.16839195277702),
          direction: 3.1913985197135206),
      ContactPoint(
          position: Offset(-139.29569467429855, 39.37529101592582),
          direction: 3.29107331084899),
      ContactPoint(
          position: Offset(-134.07959275292117, 65.19305224437583),
          direction: 3.3909135396568018),
      ContactPoint(
          position: Offset(-126.31292940658763, 90.36351796134927),
          direction: 3.490924994048017),
      ContactPoint(
          position: Offset(-116.07018927058448, 114.63236297097141),
          direction: 3.590971012484844),
      ContactPoint(
          position: Offset(-102.5598020490306, 139.02734115468402),
          direction: 3.8206100223831285),
      ContactPoint(
          position: Offset(-79.58240974633861, 157.45736842069164),
          direction: 4.37765056384038),
      ContactPoint(
          position: Offset(-50.00860102336665, 158.34091248996899),
          direction: 4.753297534314796),
      ContactPoint(
          position: Offset(-23.77586962864067, 155.95058263131756),
          direction: 4.85329876417426),
      ContactPoint(
          position: Offset(2.0871480950245402, 150.9510827407646),
          direction: 4.953345230654492),
      ContactPoint(
          position: Offset(27.32028974780834, 143.39487594847165),
          direction: 5.053249075413548),
      ContactPoint(
          position: Offset(51.67301661944116, 133.36296642995572),
          direction: 5.15296864757719),
      ContactPoint(
          position: Offset(74.90600453377151, 120.95887240829671),
          direction: 5.25258900872536),
      ContactPoint(
          position: Offset(96.7905498600112, 106.30588241080801),
          direction: 5.352230253706393),
      ContactPoint(
          position: Offset(117.109431158628, 89.5467811892963),
          direction: 5.452006940288906),
      ContactPoint(
          position: Offset(135.6576455468617, 70.84366070762835),
          direction: 5.551970496135641),
      ContactPoint(
          position: Offset(152.24565480378303, 50.38048999766218),
          direction: 5.652030532990577),
      ContactPoint(
          position: Offset(166.70548993655197, 28.3641677500833),
          direction: 5.7519387906835595),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.356194490192345, distance: 10.999999999999998),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(name: '13', angle: -0.7853981633974486, distance: 13),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974482, distance: 14.999999999999998),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(name: '17', angle: 2.356194490192345, distance: 17),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(
          name: '25', angle: 2.356194490192345, distance: 24.999999999999996),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(
          name: '29', angle: -0.7853981633974486, distance: 29.000000000000004),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
    ]);
