// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final triangle40 = GearDefinition(
    id: 'triangle40',
    image: 'images/gears/triangle_40.png',
    thumbnailImage: 'images/gears/triangle_40_thumb.png',
    size: Size(332, 328),
    center: Offset(147.70754623413086, 163.52409744262695),
    toothCount: 35,
    entitlement: Entitlement.trianglegears,
    package: Package.trianglegears,
    points: [
      ContactPoint(
          position: Offset(171.99999999998886, 0.000016347242687778427),
          direction: 6.2831839449093625),
      ContactPoint(
          position: Offset(158.52828502598925, -28.540192669395797),
          direction: 0.5369548289359347),
      ContactPoint(
          position: Offset(143.7475910852064, -50.629948216837946),
          direction: 0.6425923860512599),
      ContactPoint(
          position: Offset(126.71601734609725, -71.0366697839828),
          direction: 0.7483618613881129),
      ContactPoint(
          position: Offset(107.62686736258958, -89.53070248567184),
          direction: 0.8539966540081156),
      ContactPoint(
          position: Offset(86.69777491850203, -105.90976083317382),
          direction: 0.9594334710000156),
      ContactPoint(
          position: Offset(64.16356778549019, -119.99646573167584),
          direction: 1.0647471163658038),
      ContactPoint(
          position: Offset(40.27350400148888, -131.63727340929478),
          direction: 1.1700875698089686),
      ContactPoint(
          position: Offset(15.289571118780005, -140.70068193839242),
          direction: 1.2755900488130711),
      ContactPoint(
          position: Offset(-10.512707624044753, -147.080678788429),
          direction: 1.3812838027471486),
      ContactPoint(
          position: Offset(-36.84518572007671, -150.70078299489273),
          direction: 1.4870511795940784),
      ContactPoint(
          position: Offset(-64.9580953896729, -151.3868729214249),
          direction: 1.722171609544347),
      ContactPoint(
          position: Offset(-92.61562028826452, -140.6526098967485),
          direction: 2.2853691368303606),
      ContactPoint(
          position: Offset(-108.17304564092838, -115.21097078387857),
          direction: 2.6665188833280435),
      ContactPoint(
          position: Offset(-119.0658385097301, -90.9657960647047),
          direction: 2.772244546988836),
      ContactPoint(
          position: Offset(-127.33723203387655, -65.70553797380828),
          direction: 2.8779918896093593),
      ContactPoint(
          position: Offset(-132.89746243564696, -39.71581118554561),
          direction: 2.983559832734576),
      ContactPoint(
          position: Offset(-135.69091615477066, -13.287395308964939),
          direction: 3.088939825420977),
      ContactPoint(
          position: Offset(-135.69090843019703, 13.287427632542984),
          direction: 3.194245632467462),
      ContactPoint(
          position: Offset(-132.8974621743683, 39.71584334265555),
          direction: 3.299625612796694),
      ContactPoint(
          position: Offset(-127.33720041742471, 65.70567174521213),
          direction: 3.4051937690180116),
      ContactPoint(
          position: Offset(-119.06578622501976, 90.96595338606362),
          direction: 3.5109405014123025),
      ContactPoint(
          position: Offset(-108.17303691612537, 115.21107972503246),
          direction: 3.6166666234213167),
      ContactPoint(
          position: Offset(-92.61563366444331, 140.652632625021),
          direction: 3.997814694678377),
      ContactPoint(
          position: Offset(-64.95820980966242, 151.38697359382414),
          direction: 4.561012413124534),
      ContactPoint(
          position: Offset(-36.84527084067901, 150.70086447095957),
          direction: 4.796134665481624),
      ContactPoint(
          position: Offset(-10.51272472004465, 147.08074780538308),
          direction: 4.901901348540476),
      ContactPoint(
          position: Offset(15.289565316686506, 140.70075618200653),
          direction: 5.007594752997587),
      ContactPoint(
          position: Offset(40.27348887098354, 131.63736872238172),
          direction: 5.113097748980617),
      ContactPoint(
          position: Offset(64.16348098982408, 119.99657372160779),
          direction: 5.218438644040768),
      ContactPoint(
          position: Offset(86.6976960651707, 105.90986562399956),
          direction: 5.323751575719357),
      ContactPoint(
          position: Offset(107.62683453631887, 89.53078842085566),
          direction: 5.429188397981214),
      ContactPoint(
          position: Offset(126.71595740757039, 71.03677541448224),
          direction: 5.534823580095589),
      ContactPoint(
          position: Offset(143.7475274484597, 50.63005850372234),
          direction: 5.640592559357924),
      ContactPoint(
          position: Offset(158.5282242568344, 28.540329551659838),
          direction: 5.746230521578628),
    ],
    holes: [
      GearHole(name: '0', angle: 0, distance: 0),
      GearHole(name: '8', angle: 1.5707963267948966, distance: 8),
      GearHole(
          name: '9', angle: 2.356194490192345, distance: 9.000000000000002),
      GearHole(name: '10', angle: -3.141592653589793, distance: 10),
      GearHole(
          name: '11', angle: -2.356194490192345, distance: 10.999999999999998),
      GearHole(name: '12', angle: -1.5707963267948966, distance: 12),
      GearHole(name: '13', angle: -0.7853981633974486, distance: 13),
      GearHole(name: '14', angle: 0, distance: 14),
      GearHole(
          name: '15', angle: 0.7853981633974482, distance: 14.999999999999998),
      GearHole(name: '16', angle: 1.5707963267948966, distance: 16),
      GearHole(name: '17', angle: 2.356194490192345, distance: 17),
      GearHole(name: '18', angle: -3.141592653589793, distance: 18),
      GearHole(
          name: '19', angle: -2.3561944901923453, distance: 18.999999999999996),
      GearHole(name: '20', angle: -1.570796326794897, distance: 20),
      GearHole(name: '21', angle: -0.7853981633974487, distance: 21),
      GearHole(name: '22', angle: -3.2297397080004555e-16, distance: 22),
      GearHole(name: '23', angle: 0.7853981633974481, distance: 23),
      GearHole(name: '24', angle: 1.5707963267948966, distance: 24),
      GearHole(
          name: '25', angle: 2.356194490192345, distance: 24.999999999999996),
      GearHole(name: '26', angle: -3.141592653589793, distance: 26),
      GearHole(
          name: '27', angle: -2.356194490192345, distance: 27.000000000000004),
      GearHole(name: '28', angle: -1.570796326794897, distance: 28),
      GearHole(name: '30', angle: -2.3684757858670006e-16, distance: 30),
    ]);
