// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final triangle64 = GearDefinition(
    id: 'triangle64',
    image: 'images/gears/triangle_64.png',
    thumbnailImage: 'images/gears/triangle_64_thumb.png',
    size: Size(504, 496),
    center: Offset(252, 248),
    toothCount: 56,
    entitlement: Entitlement.trianglegears,
    package: Package.trianglegears,
    points: [
      ContactPoint(
          position: Offset(238.46532440185547, -0.7291679382324219),
          direction: 0),
      ContactPoint(
          position: Offset(225.6690952662399, -29.090969513570784),
          direction: 0.49738571728279357),
      ContactPoint(
          position: Offset(212.46374535553377, -51.61471857348148),
          direction: 0.5632805737085693),
      ContactPoint(
          position: Offset(197.80011283047787, -73.22007815824206),
          direction: 0.6293565243300572),
      ContactPoint(
          position: Offset(181.74027300263484, -93.80969878376435),
          direction: 0.6954902603593327),
      ContactPoint(
          position: Offset(164.3551640447142, -113.29273984259576),
          direction: 0.7615965168597016),
      ContactPoint(
          position: Offset(145.72210676257026, -131.5846780532949),
          direction: 0.827628794518871),
      ContactPoint(
          position: Offset(125.92427740235016, -148.6075432831931),
          direction: 0.8935748754947372),
      ContactPoint(
          position: Offset(105.0489347906853, -164.28907800090929),
          direction: 0.9594488232157126),
      ContactPoint(
          position: Offset(83.18770932011442, -178.56278961125307),
          direction: 1.025267405487332),
      ContactPoint(
          position: Offset(60.435456958946, -191.3681483006317),
          direction: 1.091067700762543),
      ContactPoint(
          position: Offset(36.8900872377619, -202.64984354060311),
          direction: 1.1568940629983846),
      ContactPoint(
          position: Offset(12.652797265854048, -212.3579867962042),
          direction: 1.2227875927715548),
      ContactPoint(
          position: Offset(-12.172637237700743, -220.44842750760404),
          direction: 1.2887692581081618),
      ContactPoint(
          position: Offset(-37.478588261264505, -226.88350742213208),
          direction: 1.3548272402837345),
      ContactPoint(
          position: Offset(-63.1550462726117, -231.63344380158162),
          direction: 1.420948770684845),
      ContactPoint(
          position: Offset(-89.0894122444213, -234.6756680113645),
          direction: 1.4870768655670963),
      ContactPoint(
          position: Offset(-115.16682169761575, -235.99812231986422),
          direction: 1.5531057968158448),
      ContactPoint(
          position: Offset(-142.83578428989372, -235.4204622793964),
          direction: 1.7501577318825232),
      ContactPoint(
          position: Offset(-170.06289738839686, -224.66512949626946),
          direction: 2.270779932854503),
      ContactPoint(
          position: Offset(-186.1654411183468, -200.0907208199178),
          direction: 2.613716291796938),
      ContactPoint(
          position: Offset(-198.56724079126127, -177.11369496944442),
          direction: 2.679685414326844),
      ContactPoint(
          position: Offset(-209.4258109412201, -153.36661597340722),
          direction: 2.7457951085981804),
      ContactPoint(
          position: Offset(-218.6909212061335, -128.95340003836492),
          direction: 2.8119253398381274),
      ContactPoint(
          position: Offset(-226.3229613024997, -103.98197253893997),
          direction: 2.8780114272669817),
      ContactPoint(
          position: Offset(-232.28957970402544, -78.56207770889102),
          direction: 2.944021290117904),
      ContactPoint(
          position: Offset(-236.56772835839604, -52.805312939120235),
          direction: 3.0099346027002483),
      ContactPoint(
          position: Offset(-239.14105538953453, -26.823591256865747),
          direction: 3.0757796120687955),
      ContactPoint(
          position: Offset(-239.99999999999997, -0.7291688427170385),
          direction: 3.141592578216075),
      ContactPoint(
          position: Offset(-239.14105930405756, 25.365223348203447),
          direction: 3.2074055686186713),
      ContactPoint(
          position: Offset(-236.56774000295604, 51.34689925487441),
          direction: 3.273250577225056),
      ContactPoint(
          position: Offset(-232.28961081324604, 77.1035557714452),
          direction: 3.339163765882611),
      ContactPoint(
          position: Offset(-226.3229939581003, 102.52352192822735),
          direction: 3.405173196067771),
      ContactPoint(
          position: Offset(-218.69096851381332, 127.4949528748562),
          direction: 3.4712595731545193),
      ContactPoint(
          position: Offset(-209.4258352313115, 151.9082538536934),
          direction: 3.537389895566356),
      ContactPoint(
          position: Offset(-198.56727456120234, 175.65532204227014),
          direction: 3.6034992846925524),
      ContactPoint(
          position: Offset(-186.16550958548314, 198.63233950566456),
          direction: 3.6694690480433696),
      ContactPoint(
          position: Offset(-170.06296580886897, 223.2067412141688),
          direction: 4.012399582163038),
      ContactPoint(
          position: Offset(-142.83609491380088, 233.96225825910966),
          direction: 4.533023236991751),
      ContactPoint(
          position: Offset(-115.16705283579843, 234.5399505153017),
          direction: 4.7300793223054205),
      ContactPoint(
          position: Offset(-89.0895654415508, 233.21748095921765),
          direction: 4.79610839066414),
      ContactPoint(
          position: Offset(-63.1551944561492, 230.17526747743494),
          direction: 4.86223690768378),
      ContactPoint(
          position: Offset(-37.47866326962169, 225.4252895192363),
          direction: 4.92835817657616),
      ContactPoint(
          position: Offset(-12.172730403395196, 218.99023324229356),
          direction: 4.994415909129438),
      ContactPoint(
          position: Offset(12.652523406951289, 210.89983373524302),
          direction: 5.06039778526395),
      ContactPoint(
          position: Offset(36.889989944707544, 201.19164751483737),
          direction: 5.126290721702285),
      ContactPoint(
          position: Offset(60.43533642767078, 189.9099565819541),
          direction: 5.19211775098946),
      ContactPoint(
          position: Offset(83.18758611852616, 177.10459937993497),
          direction: 5.257917791412498),
      ContactPoint(
          position: Offset(105.04887228192466, 162.83085759825062),
          direction: 5.323736334001658),
      ContactPoint(
          position: Offset(125.92427190906545, 147.14928048829552),
          direction: 5.389609844281128),
      ContactPoint(
          position: Offset(145.7220483516909, 130.1264923532331),
          direction: 5.4555568096607825),
      ContactPoint(
          position: Offset(164.3551300813198, 111.83448387395516),
          direction: 5.5215883742054945),
      ContactPoint(
          position: Offset(181.74020781910335, 92.35155098321107),
          direction: 5.58769450730968),
      ContactPoint(
          position: Offset(197.80014585515931, 71.76178461493305),
          direction: 5.653829137787626),
      ContactPoint(
          position: Offset(212.46368965026477, 50.15652684524426),
          direction: 5.719905565284672),
      ContactPoint(
          position: Offset(225.66909743431722, 27.632644902476148),
          direction: 5.785799968563619),
    ],
    holes: [
      GearHole(
          name: '14', angle: 0.027544854793354633, distance: 6.618841862335097),
      GearHole(
          name: '0', angle: 3.1169091306052628, distance: 7.385918817967827),
      GearHole(
          name: '13', angle: -1.3726858571131821, distance: 9.189847569731288),
      GearHole(
          name: '8', angle: 2.3049336998828114, distance: 11.021273453577901),
      GearHole(
          name: '15', angle: 1.2805079187391382, distance: 11.25999659288468),
      GearHole(
          name: '12', angle: -2.1292496746994987, distance: 13.934733192860806),
      GearHole(
          name: '22', angle: 0.01247115521676181, distance: 14.617467811013691),
      GearHole(
          name: '9', angle: 2.6971875219113484, distance: 15.226646289897358),
      GearHole(
          name: '21', angle: -1.0999694834147697, distance: 16.457649358202186),
      GearHole(
          name: '11', angle: -2.6771559607858206, distance: 16.95815233732019),
      GearHole(
          name: '10', angle: 3.1311066449011906, distance: 17.384624665960835),
      GearHole(
          name: '16', angle: 1.9988610647016876, distance: 17.787218452907993),
      GearHole(
          name: '23', angle: 1.0757062267111217, distance: 18.689923597072166),
      GearHole(
          name: '20', angle: -1.9274431019941707, distance: 21.14852518269979),
      GearHole(
          name: '30',
          angle: 0.008060018058000223,
          distance: 22.617065742784657),
      GearHole(
          name: '17', angle: 2.5802075267617726, distance: 22.922692538072575),
      GearHole(
          name: '29', angle: -0.9974725684234987, distance: 24.19204717340328),
      GearHole(
          name: '19', angle: -2.5747104680966766, distance: 24.679003422001013),
      GearHole(
          name: '24', angle: 1.8671392204198993, distance: 25.28441836476371),
      GearHole(
          name: '18', angle: 3.1344113098854436, distance: 25.384323453047003),
      GearHole(
          name: '31', angle: 0.9890347163723854, distance: 26.454469657451373),
      GearHole(
          name: '28', angle: -1.8302442915098376, distance: 28.780956301873598),
      GearHole(
          name: '38', angle: 0.005954006371944474, distance: 30.61687378588587),
      GearHole(
          name: '25', angle: 2.522427148744842, distance: 30.774159763547914),
      GearHole(
          name: '37', angle: -0.944920001152483, distance: 32.0570752016276),
      GearHole(
          name: '27', angle: -2.5213811207519607, distance: 32.535019426927),
      GearHole(
          name: '32', angle: 1.796325813773886, distance: 33.01845671434887),
      GearHole(
          name: '26', angle: 3.1361321940661187, distance: 33.38416659977436),
      GearHole(
          name: '39', angle: 0.9418869553447469, distance: 34.327316901407194),
      GearHole(
          name: '36', angle: -1.7740942337400027, distance: 36.57084595545238),
      GearHole(
          name: '46',
          angle: 0.0047205579949363835,
          distance: 38.61676136120541),
      GearHole(
          name: '33', angle: 2.488203266137144, distance: 38.68653493283851),
      GearHole(
          name: '45', angle: -0.9131261107002794, distance: 39.97570505351272),
      GearHole(
          name: '35', angle: -2.4888519703956904, distance: 40.44751869173061),
      GearHole(
          name: '40', angle: 1.7525233475010051, distance: 40.85505055131201),
      GearHole(
          name: '34', angle: 3.1371877564312523, distance: 41.384070388907716),
      GearHole(
          name: '44', angle: -1.737736801953481, distance: 44.43545996323767),
      GearHole(
          name: '54', angle: 0.003910454792809335, distance: 46.61668752320041),
      GearHole(
          name: '41', angle: 2.4656186260867834, distance: 46.628822214024424),
      GearHole(
          name: '43', angle: -2.4669825659847358, distance: 48.38880084818466),
      GearHole(
          name: '48', angle: 1.7228578117913265, distance: 48.74476204991865),
      GearHole(
          name: '42', angle: 3.137901328893659, distance: 49.38400534937042),
    ]);
