// THIS FILE IS AUTO-GENERATED
// ---------------------------
//
// Do not edit by hand.
//
// This file is generated by the Node application
// in the `gear_generator` directory.

import 'dart:ui';
import 'package:inspiral/models/contact_point.dart';
import 'package:inspiral/models/gear_definition.dart';
import 'package:inspiral/models/models.dart';

final triangle32 = GearDefinition(
    id: 'triangle32',
    image: 'images/gears/triangle_32.png',
    thumbnailImage: 'images/gears/triangle_32_thumb.png',
    size: Size(276, 272),
    center: Offset(138, 136),
    toothCount: 28,
    entitlement: Entitlement.trianglegears,
    package: Package.trianglegears,
    points: [
      ContactPoint(
          position: Offset(125.2326622009249, -0.5580915131878512),
          direction: 6.283184621053232),
      ContactPoint(
          position: Offset(111.30434176452968, -29.205568177714824),
          direction: 0.5633708779023223),
      ContactPoint(
          position: Offset(95.47668015829166, -50.942809934322995),
          direction: 0.6954765092286763),
      ContactPoint(
          position: Offset(76.92117467121489, -70.4034803252377),
          direction: 0.8275858552626616),
      ContactPoint(
          position: Offset(55.968567610229016, -87.25111632506871),
          direction: 0.9594211727232391),
      ContactPoint(
          position: Offset(32.98682102451655, -101.20038303764528),
          direction: 1.0910806792504477),
      ContactPoint(
          position: Offset(8.372061676611068, -112.01301117916195),
          direction: 1.2228316044488547),
      ContactPoint(
          position: Offset(-17.453900912357902, -119.49596606386591),
          direction: 1.3548589260482924),
      ContactPoint(
          position: Offset(-44.0423839628796, -123.51028552675282),
          direction: 1.4870273611015294),
      ContactPoint(
          position: Offset(-74.15448855739757, -123.38010196710623),
          direction: 1.893624952957584),
      ContactPoint(
          position: Offset(-97.40700469439989, -104.53831404322582),
          direction: 2.485359860409142),
      ContactPoint(
          position: Offset(-110.24908913498038, -79.18997538965739),
          direction: 2.74580536486597),
      ContactPoint(
          position: Offset(-118.95414050445427, -53.748181019586085),
          direction: 2.877973411680724),
      ContactPoint(
          position: Offset(-124.231884222003, -27.384244358960842),
          direction: 3.0099006446309335),
      ContactPoint(
          position: Offset(-125.99999999999991, -0.5581011063774316),
          direction: 3.1415925402836824),
      ContactPoint(
          position: Offset(-124.23189019722192, 26.268004807242242),
          direction: 3.273284501879295),
      ContactPoint(
          position: Offset(-118.9541565361544, 52.6319252567276),
          direction: 3.4052116483188826),
      ContactPoint(
          position: Offset(-110.24910326925662, 78.07375801378224),
          direction: 3.5373793608298403),
      ContactPoint(
          position: Offset(-97.40706129878504, 103.42206273996061),
          direction: 3.797822404806914),
      ContactPoint(
          position: Offset(-74.15464484216382, 122.26396415201992),
          direction: 4.389558018120825),
      ContactPoint(
          position: Offset(-44.04245937035684, 122.39416034550857),
          direction: 4.796158020210346),
      ContactPoint(
          position: Offset(-17.45393991578214, 118.37982588613438),
          direction: 4.928326308063399),
      ContactPoint(
          position: Offset(8.371923287171885, 110.89690362309769),
          direction: 5.060353608736037),
      ContactPoint(
          position: Offset(32.98675601804096, 100.08425808956099),
          direction: 5.192104254878215),
      ContactPoint(
          position: Offset(55.96853307643261, 86.1349768673577),
          direction: 5.323763725735652),
      ContactPoint(
          position: Offset(76.921139730775, 69.28736119035622),
          direction: 5.45559895134414),
      ContactPoint(
          position: Offset(95.47664964071353, 49.826701993649166),
          direction: 5.58770879795091),
      ContactPoint(
          position: Offset(111.30431417724968, 28.0894403391721),
          direction: 5.719814886531363),
    ],
    holes: [
      GearHole(
          name: '0', angle: 3.1038177837651446, distance: 3.694470031337205),
      GearHole(
          name: '8', angle: 1.9966140919730166, distance: 8.937645540032628),
      GearHole(
          name: '14',
          angle: 0.013534553389460708,
          distance: 10.309109768498097),
      GearHole(
          name: '13', angle: -1.0248045790617366, distance: 10.592942156275456),
      GearHole(
          name: '9', angle: 2.567512531826039, distance: 11.975573158398769),
      GearHole(
          name: '12', angle: -1.8725621074588894, distance: 12.421775651340035),
      GearHole(
          name: '15', angle: 0.9990281415558033, distance: 12.77862451303045),
      GearHole(
          name: '10', angle: 3.1314026306318805, distance: 13.692545337073383),
      GearHole(
          name: '11', angle: -2.554074461588458, distance: 13.780786480285796),
      GearHole(
          name: '16', angle: 1.7956723728539057, distance: 16.556385680035408),
      GearHole(
          name: '22',
          angle: 0.007620765459157332,
          distance: 18.308697196213984),
      GearHole(
          name: '21', angle: -0.9218736105660706, distance: 18.46249008863973),
      GearHole(
          name: '17', angle: 2.482957422338642, distance: 19.868599239132045),
      GearHole(
          name: '20', angle: -1.7545870795345555, distance: 20.200695813397314),
      GearHole(
          name: '19', angle: -2.481473830654672, distance: 21.681786604072126),
      GearHole(
          name: '18', angle: 3.135160601340609, distance: 21.69228316715645),
    ]);
